export type DomainDef = { emoji: string; labels: Record<string, string> };

export const DOMAIN_COLORS: Record<string, { bg: string; accent: string }> = {
  emotions:  { bg: "linear-gradient(145deg, #fffbeb 0%, #fde68a 100%)", accent: "#b45309" },
  relations: { bg: "linear-gradient(145deg, #eff6ff 0%, #bfdbfe 100%)", accent: "#2563eb" },
  money:     { bg: "linear-gradient(145deg, #fefce8 0%, #fef08a 100%)", accent: "#a16207" },
  wisdom:    { bg: "linear-gradient(145deg, #f5f3ff 0%, #ddd6fe 100%)", accent: "#7c3aed" },
  speech:    { bg: "linear-gradient(145deg, #f0fdf4 0%, #bbf7d0 100%)", accent: "#15803d" },
  morality:  { bg: "linear-gradient(145deg, #fff7ed 0%, #fed7aa 100%)", accent: "#c2410c" },
  nature:    { bg: "linear-gradient(145deg, #ecfdf5 0%, #a7f3d0 100%)", accent: "#047857" },
  time:      { bg: "linear-gradient(145deg, #faf5ff 0%, #e9d5ff 100%)", accent: "#7e22ce" },
  work:      { bg: "linear-gradient(145deg, #fff1f2 0%, #fecdd3 100%)", accent: "#be123c" },
  humor:     { bg: "linear-gradient(145deg, #fef3c7 0%, #fcd34d 100%)", accent: "#92400e" },
  pleasure:  { bg: "linear-gradient(145deg, #fdf2f8 0%, #f5d0fe 100%)", accent: "#a21caf" },
  travel:    { bg: "linear-gradient(145deg, #ecfeff 0%, #a5f3fc 100%)", accent: "#0e7490" },
  luck:      { bg: "linear-gradient(145deg, #f0fdf4 0%, #86efac 100%)", accent: "#15803d" },
  knowledge: { bg: "linear-gradient(145deg, #f0f9ff 0%, #bae6fd 100%)", accent: "#0369a1" },
  justice:   { bg: "linear-gradient(145deg, #fff1f2 0%, #fda4af 100%)", accent: "#9f1239" },
  conflict:  { bg: "linear-gradient(145deg, #fff7ed 0%, #fdba74 100%)", accent: "#c2410c" },
  ambition:  { bg: "linear-gradient(145deg, #fefce8 0%, #fde047 100%)", accent: "#854d0e" },
  body:      { bg: "linear-gradient(145deg, #fdf4ff 0%, #e9d5ff 100%)", accent: "#7e22ce" },
  change:    { bg: "linear-gradient(145deg, #ecfeff 0%, #67e8f9 100%)", accent: "#0e7490" },
  food:      { bg: "linear-gradient(145deg, #fff7ed 0%, #fcd34d 100%)", accent: "#92400e" },
};

export const DOMAIN_DEFS: Record<string, DomainDef> = {
  emotions:  { emoji: "🎭", labels: { fr: "Émotions",        en: "Emotions",          es: "Emociones",        it: "Emozioni",        tr: "Duygular",      de: "Gefühle",              ja: "感情" } },
  relations: { emoji: "👥", labels: { fr: "Relations",       en: "Relationships",     es: "Relaciones",       it: "Relazioni",       tr: "İlişkiler",     de: "Beziehungen",          ja: "人間関係" } },
  money:     { emoji: "💰", labels: { fr: "Argent & pouvoir",en: "Money & power",     es: "Dinero & poder",   it: "Denaro & potere", tr: "Para & güç",    de: "Geld & Macht",         ja: "お金と権力" } },
  wisdom:    { emoji: "🦉", labels: { fr: "Esprit & sagesse",en: "Mind & wisdom",     es: "Mente & sabiduría",it: "Mente & saggezza",tr: "Akıl & bilgelik",de: "Geist & Weisheit",    ja: "知恵" } },
  speech:    { emoji: "💬", labels: { fr: "Parole",          en: "Speech",            es: "Palabra",          it: "Parola",          tr: "Söz",           de: "Sprache",              ja: "言葉" } },
  morality:  { emoji: "🪷", labels: { fr: "Morale & société",en: "Morality",          es: "Moral & sociedad", it: "Morale",          tr: "Ahlak",         de: "Moral & Gesellschaft", ja: "道徳と社会" } },
  nature:    { emoji: "🌿", labels: { fr: "Nature & corps",  en: "Nature & body",     es: "Naturaleza",       it: "Natura & corpo",  tr: "Doğa & beden",  de: "Natur & Körper",       ja: "自然と身体" } },
  time:      { emoji: "⏰", labels: { fr: "Temps & destin",  en: "Time & fate",       es: "Tiempo & destino", it: "Tempo & destino", tr: "Zaman & kader", de: "Zeit & Schicksal",     ja: "時間と運命" } },
  work:      { emoji: "💼", labels: { fr: "Travail & effort",en: "Work & effort",     es: "Trabajo & esfuerzo",it: "Lavoro & sforzo",tr: "Çalışma",       de: "Arbeit & Fleiß",       ja: "仕事と努力" } },
  humor:     { emoji: "😂", labels: { fr: "Humour & absurde",en: "Humor & absurdity", es: "Humor & absurdo",  it: "Umorismo",        tr: "Mizah",         de: "Humor & Absurdes",     ja: "ユーモアと不条理" } },
  pleasure:  { emoji: "🍷", labels: { fr: "Plaisirs & excès",en: "Pleasures & excess",es: "Placeres",         it: "Piaceri",         tr: "Zevk",          de: "Genuss & Exzess",      ja: "喜びと過剰" } },
  travel:    { emoji: "✈️", labels: { fr: "Voyage & exil",   en: "Travel & exile",    es: "Viaje & exilio",   it: "Viaggio",         tr: "Seyahat",       de: "Reise & Exil",         ja: "旅と放浪" } },
  luck:      { emoji: "🍀", labels: { fr: "Chance & risque", en: "Luck & risk",       es: "Suerte & riesgo",  it: "Fortuna",         tr: "Şans & risk",   de: "Glück & Risiko",       ja: "幸運とリスク" } },
  knowledge: { emoji: "📖", labels: { fr: "Savoir",          en: "Knowledge",         es: "Saber",            it: "Sapere",          tr: "Bilgi",         de: "Wissen",               ja: "知識" } },
  justice:   { emoji: "⚖️", labels: { fr: "Justice & loi",   en: "Justice & law",     es: "Justicia & ley",   it: "Giustizia",       tr: "Adalet",        de: "Gerechtigkeit & Recht",ja: "正義と法" } },
  conflict:  { emoji: "⚔️", labels: { fr: "Conflit",         en: "Conflict",          es: "Conflicto",        it: "Conflitto",       tr: "Çatışma",       de: "Konflikt",             ja: "対立" } },
  ambition:  { emoji: "🚀", labels: { fr: "Ambition",        en: "Ambition",          es: "Ambición",         it: "Ambizione",       tr: "Hırs",          de: "Ehrgeiz",              ja: "野心" } },
  body:      { emoji: "🫀", labels: { fr: "Corps & santé",   en: "Body & health",     es: "Cuerpo & salud",   it: "Corpo & salute",  tr: "Beden & sağlık",de: "Körper & Gesundheit",  ja: "身体と健康" } },
  change:    { emoji: "🦋", labels: { fr: "Changement",      en: "Change",            es: "Cambio",           it: "Cambiamento",     tr: "Değişim",       de: "Wandel",               ja: "変化" } },
  food:      { emoji: "🍽️", labels: { fr: "Nourriture",      en: "Food",              es: "Comida",           it: "Cibo",            tr: "Yemek",         de: "Essen",                ja: "食べ物" } },
};
