export type UILang = "fr" | "en" | "es" | "it" | "tr" | "de";

export type EditorialDomain = {
  slug: string;
  emoji: string;
  bg: string;
  border: string;
  labels: Record<UILang, string>;
  desc: Record<UILang, string>;
};

export const EDITORIAL_DOMAINS: EditorialDomain[] = [
  {
    slug: "wisdom",
    emoji: "🧠",
    bg: "linear-gradient(135deg, #f5f3ff 0%, #ddd6fe 100%)",
    border: "#c4b5fd",
    labels: {
      fr: "La sagesse des âges",
      en: "The ancient wisdom",
      es: "La sabiduría de los siglos",
      it: "La saggezza dei secoli",
      tr: "Çağların bilgeliği",
      de: "Die Weisheit der Zeiten",
    },
    desc: {
      fr: "Proverbes, maximes et vérités qui traversent le temps",
      en: "Proverbs, maxims and truths that stand the test of time",
      es: "Proverbios, máximas y verdades atemporales",
      it: "Proverbi, massime e verità senza tempo",
      tr: "Zaman aşımına uğramayan atasözleri ve özdeyişler",
      de: "Sprichwörter, Maximen und zeitlose Wahrheiten",
    },
  },
  {
    slug: "speech",
    emoji: "🗣️",
    bg: "linear-gradient(135deg, #f0fdf4 0%, #bbf7d0 100%)",
    border: "#86efac",
    labels: {
      fr: "Le poids des mots",
      en: "The weight of words",
      es: "El peso de las palabras",
      it: "Il peso delle parole",
      tr: "Sözlerin ağırlığı",
      de: "Das Gewicht der Worte",
    },
    desc: {
      fr: "Parler, mentir, convaincre, se taire",
      en: "Speaking, lying, convincing, staying silent",
      es: "Hablar, mentir, convencer, callar",
      it: "Parlare, mentire, convincere, tacere",
      tr: "Konuşmak, yalan söylemek, ikna etmek",
      de: "Reden, lügen, überzeugen, schweigen",
    },
  },
  {
    slug: "morality",
    emoji: "🤥",
    bg: "linear-gradient(135deg, #ede8f5 0%, #dfd5f0 100%)",
    border: "#c9b8e8",
    labels: {
      fr: "Les travers humains",
      en: "Human flaws",
      es: "Los defectos humanos",
      it: "I difetti umani",
      tr: "İnsan kusurları",
      de: "Die menschlichen Schwächen",
    },
    desc: {
      fr: "Mentir, se vanter, esquiver, se trahir",
      en: "Lie, boast, dodge, betray yourself",
      es: "Mentir, presumir, esquivar",
      it: "Mentire, vantarsi, eludere",
      tr: "Yalan söylemek, böbürlenmek",
      de: "Lügen, prahlen, ausweichen, sich verraten",
    },
  },
  {
    slug: "time",
    emoji: "⏳",
    bg: "linear-gradient(135deg, #faf5ff 0%, #e9d5ff 100%)",
    border: "#d8b4fe",
    labels: {
      fr: "Le temps & le destin",
      en: "Time & fate",
      es: "El tiempo & el destino",
      it: "Il tempo & il destino",
      tr: "Zaman & kader",
      de: "Zeit & Schicksal",
    },
    desc: {
      fr: "Attendre, vieillir, regretter, saisir l'instant",
      en: "Wait, age, regret, seize the moment",
      es: "Esperar, envejecer, arrepentirse",
      it: "Aspettare, invecchiare, rimpiangere",
      tr: "Beklemek, yaşlanmak, pişman olmak",
      de: "Warten, altern, bereuen, den Moment ergreifen",
    },
  },
  {
    slug: "emotions",
    emoji: "💛",
    bg: "linear-gradient(135deg, #fffbeb 0%, #fde68a 100%)",
    border: "#fcd34d",
    labels: {
      fr: "Les tempêtes intérieures",
      en: "Inner storms",
      es: "Las tormentas interiores",
      it: "Le tempeste interiori",
      tr: "İç fırtınalar",
      de: "Die inneren Stürme",
    },
    desc: {
      fr: "Joie, colère, peur, tristesse — et tout ce qui déborde",
      en: "Joy, anger, fear, grief — and everything in between",
      es: "Alegría, ira, miedo, tristeza — y todo lo demás",
      it: "Gioia, rabbia, paura, tristezza — e tutto il resto",
      tr: "Sevinç, öfke, korku, üzüntü — ve aralarındaki her şey",
      de: "Freude, Wut, Angst, Trauer — und alles dazwischen",
    },
  },
  {
    slug: "work",
    emoji: "😤",
    bg: "linear-gradient(135deg, #dce8f5 0%, #c8dcee 100%)",
    border: "#b0cde4",
    labels: {
      fr: "L'effort & les épreuves",
      en: "Effort & hardship",
      es: "El esfuerzo",
      it: "Lo sforzo & le prove",
      tr: "Çaba & zorluk",
      de: "Mühe & Bewährung",
    },
    desc: {
      fr: "Souffrir, persévérer, tomber, se relever",
      en: "Suffer, persist, fall, rise",
      es: "Sufrir, perseverar, caer",
      it: "Soffrire, resistere, cadere",
      tr: "Acı çekmek, dayanmak, kalkmak",
      de: "Leiden, durchhalten, fallen, wieder aufstehen",
    },
  },
  {
    slug: "humor",
    emoji: "🎭",
    bg: "linear-gradient(135deg, #fef3c7 0%, #fcd34d 100%)",
    border: "#fbbf24",
    labels: {
      fr: "Le rire & l'absurde",
      en: "Laughter & the absurd",
      es: "La risa & el absurdo",
      it: "Il riso & l'assurdo",
      tr: "Gülüş & saçmalık",
      de: "Lachen & Absurdität",
    },
    desc: {
      fr: "Se moquer, exagérer, tourner en dérision",
      en: "Mock, exaggerate, make light of things",
      es: "Burlarse, exagerar, ridiculizar",
      it: "Deridere, esagerare, scherzare",
      tr: "Alay etmek, abartmak, hafife almak",
      de: "Spotten, übertreiben, ins Lächerliche ziehen",
    },
  },
  {
    slug: "luck",
    emoji: "🎲",
    bg: "linear-gradient(135deg, #f0fdf4 0%, #86efac 100%)",
    border: "#4ade80",
    labels: {
      fr: "La chance & le risque",
      en: "Luck & risk",
      es: "La suerte & el riesgo",
      it: "La fortuna & il rischio",
      tr: "Şans & risk",
      de: "Glück & Risiko",
    },
    desc: {
      fr: "Tenter, espérer, perdre, rebondir",
      en: "Try, hope, lose, bounce back",
      es: "Intentar, esperar, perder",
      it: "Tentare, sperare, perdere",
      tr: "Denemek, ummak, kaybetmek",
      de: "Wagen, hoffen, verlieren, wieder aufstehen",
    },
  },
  {
    slug: "relations",
    emoji: "❤️",
    bg: "linear-gradient(135deg, #fdecea 0%, #f7d6d3 100%)",
    border: "#f0b8b3",
    labels: {
      fr: "L'amour & les liens",
      en: "Love & bonds",
      es: "El amor & los lazos",
      it: "L'amore & i legami",
      tr: "Aşk & bağlar",
      de: "Liebe & Bindungen",
    },
    desc: {
      fr: "Aimer, trahir, se perdre, s'attacher",
      en: "Love, betray, lose yourself",
      es: "Amar, traicionar, perderse",
      it: "Amare, tradire, perdersi",
      tr: "Sevmek, ihanet, kaybolmak",
      de: "Lieben, verraten, sich verlieren, sich binden",
    },
  },
  {
    slug: "nature",
    emoji: "🌿",
    bg: "linear-gradient(135deg, #ecfdf5 0%, #a7f3d0 100%)",
    border: "#6ee7b7",
    labels: {
      fr: "La terre & les bêtes",
      en: "Earth & creatures",
      es: "La tierra & las bestias",
      it: "La terra & le bestie",
      tr: "Toprak & hayvanlar",
      de: "Erde & Tiere",
    },
    desc: {
      fr: "Animaux, saisons, paysages — la nature comme miroir",
      en: "Animals, seasons, landscapes — nature as a mirror",
      es: "Animales, estaciones, paisajes",
      it: "Animali, stagioni, paesaggi",
      tr: "Hayvanlar, mevsimler, manzaralar",
      de: "Tiere, Jahreszeiten, Landschaften — die Natur als Spiegel",
    },
  },
  {
    slug: "pleasure",
    emoji: "🍷",
    bg: "linear-gradient(135deg, #fdf2f8 0%, #f5d0fe 100%)",
    border: "#e879f9",
    labels: {
      fr: "Les plaisirs & les excès",
      en: "Pleasures & excess",
      es: "Los placeres & los excesos",
      it: "I piaceri & gli eccessi",
      tr: "Zevkler & aşırılıklar",
      de: "Genuss & Ausschweifungen",
    },
    desc: {
      fr: "Manger, boire, profiter, dépasser les bornes",
      en: "Eat, drink, enjoy, go too far",
      es: "Comer, beber, disfrutar, pasarse",
      it: "Mangiare, bere, godere, esagerare",
      tr: "Yemek, içmek, eğlenmek, aşırıya kaçmak",
      de: "Essen, trinken, genießen, über die Stränge schlagen",
    },
  },
  {
    slug: "body",
    emoji: "🫀",
    bg: "linear-gradient(135deg, #fdf4ff 0%, #e9d5ff 100%)",
    border: "#d8b4fe",
    labels: {
      fr: "Le corps qui parle",
      en: "The body speaks",
      es: "El cuerpo habla",
      it: "Il corpo parla",
      tr: "Konuşan beden",
      de: "Der Körper spricht",
    },
    desc: {
      fr: "Mains, pieds, yeux, ventre — le corps comme langage",
      en: "Hands, feet, eyes, belly — the body as language",
      es: "Manos, pies, ojos — el cuerpo como lenguaje",
      it: "Mani, piedi, occhi — il corpo come linguaggio",
      tr: "Eller, ayaklar, gözler — beden bir dil olarak",
      de: "Hände, Füße, Augen, Bauch — der Körper als Sprache",
    },
  },
  {
    slug: "ambition",
    emoji: "👑",
    bg: "linear-gradient(135deg, #fefce8 0%, #fde047 100%)",
    border: "#facc15",
    labels: {
      fr: "La soif de réussir",
      en: "The hunger to rise",
      es: "La sed de triunfar",
      it: "La sete di successo",
      tr: "Başarıya olan susuzluk",
      de: "Der Hunger nach Erfolg",
    },
    desc: {
      fr: "Vouloir, grimper, dominer, se brûler les ailes",
      en: "Want, climb, dominate, fly too close to the sun",
      es: "Querer, ascender, dominar",
      it: "Volere, salire, dominare",
      tr: "İstemek, tırmanmak, egemen olmak",
      de: "Wollen, aufsteigen, beherrschen, sich die Flügel verbrennen",
    },
  },
  {
    slug: "conflict",
    emoji: "🔥",
    bg: "linear-gradient(135deg, #fff7ed 0%, #fdba74 100%)",
    border: "#fb923c",
    labels: {
      fr: "La guerre & les mots",
      en: "War & words",
      es: "La guerra & las palabras",
      it: "La guerra & le parole",
      tr: "Savaş & kelimeler",
      de: "Krieg & Worte",
    },
    desc: {
      fr: "S'affronter, blesser, résister, se réconcilier",
      en: "Clash, wound, resist, reconcile",
      es: "Enfrentarse, herir, resistir",
      it: "Scontrarsi, ferire, resistere",
      tr: "Çatışmak, incitmek, direnmek",
      de: "Zusammenstoßen, verletzen, widerstehen, versöhnen",
    },
  },
  {
    slug: "travel",
    emoji: "🌍",
    bg: "linear-gradient(135deg, #ecfeff 0%, #a5f3fc 100%)",
    border: "#67e8f9",
    labels: {
      fr: "Les chemins du monde",
      en: "Roads of the world",
      es: "Los caminos del mundo",
      it: "I cammini del mondo",
      tr: "Dünyanın yolları",
      de: "Die Wege der Welt",
    },
    desc: {
      fr: "Partir, errer, s'exiler, revenir",
      en: "Leave, wander, exile yourself, return",
      es: "Partir, vagar, exiliarse, volver",
      it: "Partire, vagare, esiliarsi, tornare",
      tr: "Gitmek, dolaşmak, sürgüne gitmek, dönmek",
      de: "Aufbrechen, umherirren, ins Exil gehen, zurückkehren",
    },
  },
  {
    slug: "money",
    emoji: "💰",
    bg: "linear-gradient(135deg, #fdf5dc 0%, #f7e9b8 100%)",
    border: "#e8d57a",
    labels: {
      fr: "L'argent & la réussite",
      en: "Money & success",
      es: "El dinero & el éxito",
      it: "I soldi & il successo",
      tr: "Para & başarı",
      de: "Geld & Erfolg",
    },
    desc: {
      fr: "Gagner, perdre, mériter, gaspiller",
      en: "Earn, lose, deserve, waste",
      es: "Ganar, perder, merecer",
      it: "Guadagnare, perdere, meritare",
      tr: "Kazanmak, kaybetmek, hak etmek",
      de: "Verdienen, verlieren, verdienen, verschwenden",
    },
  },
];

export const EDITORIAL_DOMAIN_MAP: Record<string, EditorialDomain> = Object.fromEntries(
  EDITORIAL_DOMAINS.map((d) => [d.slug, d])
);
