export type UILang = "fr" | "en" | "es" | "it" | "tr" | "de" | "ja";

export type EditorialDomain = {
  slug: string;
  emoji: string;
  bg: string;
  border: string;
  labels: Record<UILang, string>;
  desc: Record<UILang, string>;
};

export const EDITORIAL_DOMAINS: EditorialDomain[] = [
  {
    slug: "wisdom",
    emoji: "🧠",
    bg: "linear-gradient(135deg, #f5f3ff 0%, #ddd6fe 100%)",
    border: "#c4b5fd",
    labels: {
      fr: "La sagesse des âges",
      en: "The ancient wisdom",
      es: "La sabiduría de los siglos",
      it: "La saggezza dei secoli",
      tr: "Çağların bilgeliği",
      de: "Die Weisheit der Zeiten",
      ja: "歳月の知恵",
    },
    desc: {
      fr: "Proverbes, maximes et vérités qui traversent le temps",
      en: "Proverbs, maxims and truths that stand the test of time",
      es: "Proverbios, máximas y verdades atemporales",
      it: "Proverbi, massime e verità senza tempo",
      tr: "Zaman aşımına uğramayan atasözleri ve özdeyişler",
      de: "Sprichwörter, Maximen und zeitlose Wahrheiten",
      ja: "時を超えることわざと格言",
    },
  },
  {
    slug: "speech",
    emoji: "🗣️",
    bg: "linear-gradient(135deg, #f0fdf4 0%, #bbf7d0 100%)",
    border: "#86efac",
    labels: {
      fr: "Le poids des mots",
      en: "The weight of words",
      es: "El peso de las palabras",
      it: "Il peso delle parole",
      tr: "Sözlerin ağırlığı",
      de: "Das Gewicht der Worte",
      ja: "言葉の重み",
    },
    desc: {
      fr: "Parler, mentir, convaincre, se taire",
      en: "Speaking, lying, convincing, staying silent",
      es: "Hablar, mentir, convencer, callar",
      it: "Parlare, mentire, convincere, tacere",
      tr: "Konuşmak, yalan söylemek, ikna etmek",
      de: "Reden, lügen, überzeugen, schweigen",
      ja: "語る、嘘をつく、説得する、沈黙する",
    },
  },
  {
    slug: "morality",
    emoji: "🤥",
    bg: "linear-gradient(135deg, #ede8f5 0%, #dfd5f0 100%)",
    border: "#c9b8e8",
    labels: {
      fr: "Les travers humains",
      en: "Human flaws",
      es: "Los defectos humanos",
      it: "I difetti umani",
      tr: "İnsan kusurları",
      de: "Die menschlichen Schwächen",
      ja: "人の弱さ",
    },
    desc: {
      fr: "Mentir, se vanter, esquiver, se trahir",
      en: "Lie, boast, dodge, betray yourself",
      es: "Mentir, presumir, esquivar",
      it: "Mentire, vantarsi, eludere",
      tr: "Yalan söylemek, böbürlenmek",
      de: "Lügen, prahlen, ausweichen, sich verraten",
      ja: "嘘をつく、自慢する、誤魔化す",
    },
  },
  {
    slug: "time",
    emoji: "⏳",
    bg: "linear-gradient(135deg, #faf5ff 0%, #e9d5ff 100%)",
    border: "#d8b4fe",
    labels: {
      fr: "Le temps & le destin",
      en: "Time & fate",
      es: "El tiempo & el destino",
      it: "Il tempo & il destino",
      tr: "Zaman & kader",
      de: "Zeit & Schicksal",
      ja: "時間と運命",
    },
    desc: {
      fr: "Attendre, vieillir, regretter, saisir l'instant",
      en: "Wait, age, regret, seize the moment",
      es: "Esperar, envejecer, arrepentirse",
      it: "Aspettare, invecchiare, rimpiangere",
      tr: "Beklemek, yaşlanmak, pişman olmak",
      de: "Warten, altern, bereuen, den Moment ergreifen",
      ja: "待つ、老いる、後悔する、瞬間をつかむ",
    },
  },
  {
    slug: "emotions",
    emoji: "💛",
    bg: "linear-gradient(135deg, #fffbeb 0%, #fde68a 100%)",
    border: "#fcd34d",
    labels: {
      fr: "Les tempêtes intérieures",
      en: "Inner storms",
      es: "Las tormentas interiores",
      it: "Le tempeste interiori",
      tr: "İç fırtınalar",
      de: "Die inneren Stürme",
      ja: "心の嵐",
    },
    desc: {
      fr: "Joie, colère, peur, tristesse — et tout ce qui déborde",
      en: "Joy, anger, fear, grief — and everything in between",
      es: "Alegría, ira, miedo, tristeza — y todo lo demás",
      it: "Gioia, rabbia, paura, tristezza — e tutto il resto",
      tr: "Sevinç, öfke, korku, üzüntü — ve aralarındaki her şey",
      de: "Freude, Wut, Angst, Trauer — und alles dazwischen",
      ja: "喜び、怒り、恐れ、悲しみ",
    },
  },
  {
    slug: "work",
    emoji: "😤",
    bg: "linear-gradient(135deg, #dce8f5 0%, #c8dcee 100%)",
    border: "#b0cde4",
    labels: {
      fr: "L'effort & les épreuves",
      en: "Effort & hardship",
      es: "El esfuerzo",
      it: "Lo sforzo & le prove",
      tr: "Çaba & zorluk",
      de: "Mühe & Bewährung",
      ja: "努力と試練",
    },
    desc: {
      fr: "Souffrir, persévérer, tomber, se relever",
      en: "Suffer, persist, fall, rise",
      es: "Sufrir, perseverar, caer",
      it: "Soffrire, resistere, cadere",
      tr: "Acı çekmek, dayanmak, kalkmak",
      de: "Leiden, durchhalten, fallen, wieder aufstehen",
      ja: "苦しむ、耐える、倒れる、立ち上がる",
    },
  },
  {
    slug: "humor",
    emoji: "🎭",
    bg: "linear-gradient(135deg, #fef3c7 0%, #fcd34d 100%)",
    border: "#fbbf24",
    labels: {
      fr: "Le rire & l'absurde",
      en: "Laughter & the absurd",
      es: "La risa & el absurdo",
      it: "Il riso & l'assurdo",
      tr: "Gülüş & saçmalık",
      de: "Lachen & Absurdität",
      ja: "笑いと不条理",
    },
    desc: {
      fr: "Se moquer, exagérer, tourner en dérision",
      en: "Mock, exaggerate, make light of things",
      es: "Burlarse, exagerar, ridiculizar",
      it: "Deridere, esagerare, scherzare",
      tr: "Alay etmek, abartmak, hafife almak",
      de: "Spotten, übertreiben, ins Lächerliche ziehen",
      ja: "からかう、誇張する、笑い飛ばす",
    },
  },
  {
    slug: "luck",
    emoji: "🎲",
    bg: "linear-gradient(135deg, #f0fdf4 0%, #86efac 100%)",
    border: "#4ade80",
    labels: {
      fr: "La chance & le risque",
      en: "Luck & risk",
      es: "La suerte & el riesgo",
      it: "La fortuna & il rischio",
      tr: "Şans & risk",
      de: "Glück & Risiko",
      ja: "運とリスク",
    },
    desc: {
      fr: "Tenter, espérer, perdre, rebondir",
      en: "Try, hope, lose, bounce back",
      es: "Intentar, esperar, perder",
      it: "Tentare, sperare, perdere",
      tr: "Denemek, ummak, kaybetmek",
      de: "Wagen, hoffen, verlieren, wieder aufstehen",
      ja: "試みる、望む、失う、立ち直る",
    },
  },
  {
    slug: "relations",
    emoji: "❤️",
    bg: "linear-gradient(135deg, #fdecea 0%, #f7d6d3 100%)",
    border: "#f0b8b3",
    labels: {
      fr: "L'amour & les liens",
      en: "Love & bonds",
      es: "El amor & los lazos",
      it: "L'amore & i legami",
      tr: "Aşk & bağlar",
      de: "Liebe & Bindungen",
      ja: "愛と絆",
    },
    desc: {
      fr: "Aimer, trahir, se perdre, s'attacher",
      en: "Love, betray, lose yourself",
      es: "Amar, traicionar, perderse",
      it: "Amare, tradire, perdersi",
      tr: "Sevmek, ihanet, kaybolmak",
      de: "Lieben, verraten, sich verlieren, sich binden",
      ja: "愛する、裏切る、迷う、絆を結ぶ",
    },
  },
  {
    slug: "nature",
    emoji: "🌿",
    bg: "linear-gradient(135deg, #ecfdf5 0%, #a7f3d0 100%)",
    border: "#6ee7b7",
    labels: {
      fr: "La terre & les bêtes",
      en: "Earth & creatures",
      es: "La tierra & las bestias",
      it: "La terra & le bestie",
      tr: "Toprak & hayvanlar",
      de: "Erde & Tiere",
      ja: "大地と生き物",
    },
    desc: {
      fr: "Animaux, saisons, paysages — la nature comme miroir",
      en: "Animals, seasons, landscapes — nature as a mirror",
      es: "Animales, estaciones, paisajes",
      it: "Animali, stagioni, paesaggi",
      tr: "Hayvanlar, mevsimler, manzaralar",
      de: "Tiere, Jahreszeiten, Landschaften — die Natur als Spiegel",
      ja: "動物、季節、風景 — 自然は鏡",
    },
  },
  {
    slug: "pleasure",
    emoji: "🍷",
    bg: "linear-gradient(135deg, #fdf2f8 0%, #f5d0fe 100%)",
    border: "#e879f9",
    labels: {
      fr: "Les plaisirs & les excès",
      en: "Pleasures & excess",
      es: "Los placeres & los excesos",
      it: "I piaceri & gli eccessi",
      tr: "Zevkler & aşırılıklar",
      de: "Genuss & Ausschweifungen",
      ja: "喜びと過剰",
    },
    desc: {
      fr: "Manger, boire, profiter, dépasser les bornes",
      en: "Eat, drink, enjoy, go too far",
      es: "Comer, beber, disfrutar, pasarse",
      it: "Mangiare, bere, godere, esagerare",
      tr: "Yemek, içmek, eğlenmek, aşırıya kaçmak",
      de: "Essen, trinken, genießen, über die Stränge schlagen",
      ja: "食べる、飲む、楽しむ、度を超す",
    },
  },
  {
    slug: "body",
    emoji: "🫀",
    bg: "linear-gradient(135deg, #fdf4ff 0%, #e9d5ff 100%)",
    border: "#d8b4fe",
    labels: {
      fr: "Le corps qui parle",
      en: "The body speaks",
      es: "El cuerpo habla",
      it: "Il corpo parla",
      tr: "Konuşan beden",
      de: "Der Körper spricht",
      ja: "体が語る",
    },
    desc: {
      fr: "Mains, pieds, yeux, ventre — le corps comme langage",
      en: "Hands, feet, eyes, belly — the body as language",
      es: "Manos, pies, ojos — el cuerpo como lenguaje",
      it: "Mani, piedi, occhi — il corpo come linguaggio",
      tr: "Eller, ayaklar, gözler — beden bir dil olarak",
      de: "Hände, Füße, Augen, Bauch — der Körper als Sprache",
      ja: "手、足、目、腹 — 体という言語",
    },
  },
  {
    slug: "ambition",
    emoji: "👑",
    bg: "linear-gradient(135deg, #fefce8 0%, #fde047 100%)",
    border: "#facc15",
    labels: {
      fr: "La soif de réussir",
      en: "The hunger to rise",
      es: "La sed de triunfar",
      it: "La sete di successo",
      tr: "Başarıya olan susuzluk",
      de: "Der Hunger nach Erfolg",
      ja: "成功への飢え",
    },
    desc: {
      fr: "Vouloir, grimper, dominer, se brûler les ailes",
      en: "Want, climb, dominate, fly too close to the sun",
      es: "Querer, ascender, dominar",
      it: "Volere, salire, dominare",
      tr: "İstemek, tırmanmak, egemen olmak",
      de: "Wollen, aufsteigen, beherrschen, sich die Flügel verbrennen",
      ja: "求める、昇る、支配する、身を焦がす",
    },
  },
  {
    slug: "conflict",
    emoji: "🔥",
    bg: "linear-gradient(135deg, #fff7ed 0%, #fdba74 100%)",
    border: "#fb923c",
    labels: {
      fr: "La guerre & les mots",
      en: "War & words",
      es: "La guerra & las palabras",
      it: "La guerra & le parole",
      tr: "Savaş & kelimeler",
      de: "Krieg & Worte",
      ja: "争いと言葉",
    },
    desc: {
      fr: "S'affronter, blesser, résister, se réconcilier",
      en: "Clash, wound, resist, reconcile",
      es: "Enfrentarse, herir, resistir",
      it: "Scontrarsi, ferire, resistere",
      tr: "Çatışmak, incitmek, direnmek",
      de: "Zusammenstoßen, verletzen, widerstehen, versöhnen",
      ja: "衝突する、傷つける、抵抗する、和解する",
    },
  },
  {
    slug: "travel",
    emoji: "🌍",
    bg: "linear-gradient(135deg, #ecfeff 0%, #a5f3fc 100%)",
    border: "#67e8f9",
    labels: {
      fr: "Les chemins du monde",
      en: "Roads of the world",
      es: "Los caminos del mundo",
      it: "I cammini del mondo",
      tr: "Dünyanın yolları",
      de: "Die Wege der Welt",
      ja: "世界の道",
    },
    desc: {
      fr: "Partir, errer, s'exiler, revenir",
      en: "Leave, wander, exile yourself, return",
      es: "Partir, vagar, exiliarse, volver",
      it: "Partire, vagare, esiliarsi, tornare",
      tr: "Gitmek, dolaşmak, sürgüne gitmek, dönmek",
      de: "Aufbrechen, umherirren, ins Exil gehen, zurückkehren",
      ja: "旅立つ、さまよう、流浪する、帰る",
    },
  },
  {
    slug: "money",
    emoji: "💰",
    bg: "linear-gradient(135deg, #fdf5dc 0%, #f7e9b8 100%)",
    border: "#e8d57a",
    labels: {
      fr: "L'argent & la réussite",
      en: "Money & success",
      es: "El dinero & el éxito",
      it: "I soldi & il successo",
      tr: "Para & başarı",
      de: "Geld & Erfolg",
      ja: "お金と成功",
    },
    desc: {
      fr: "Gagner, perdre, mériter, gaspiller",
      en: "Earn, lose, deserve, waste",
      es: "Ganar, perder, merecer",
      it: "Guadagnare, perdere, meritare",
      tr: "Kazanmak, kaybetmek, hak etmek",
      de: "Verdienen, verlieren, verdienen, verschwenden",
      ja: "稼ぐ、失う、値する、無駄にする",
    },
  },
  {
    slug: "knowledge",
    emoji: "📖",
    bg: "linear-gradient(135deg, #eff6ff 0%, #bfdbfe 100%)",
    border: "#93c5fd",
    labels: {
      fr: "Le savoir & la vérité",
      en: "Knowledge & truth",
      es: "El saber & la verdad",
      it: "Il sapere & la verità",
      tr: "Bilgi & gerçek",
      de: "Wissen & Wahrheit",
      ja: "知恵と真実",
    },
    desc: {
      fr: "Apprendre, comprendre, se tromper, retenir la leçon",
      en: "Learn, understand, be wrong, remember the lesson",
      es: "Aprender, comprender, equivocarse, recordar la lección",
      it: "Imparare, capire, sbagliare, ricordare la lezione",
      tr: "Öğrenmek, anlamak, yanılmak, dersi hatırlamak",
      de: "Lernen, verstehen, sich irren, die Lehre behalten",
      ja: "学ぶ、理解する、間違える、教訓を胸に刻む",
    },
  },
  {
    slug: "justice",
    emoji: "⚖️",
    bg: "linear-gradient(135deg, #f1f5f9 0%, #cbd5e1 100%)",
    border: "#94a3b8",
    labels: {
      fr: "La justice & le jugement",
      en: "Justice & judgment",
      es: "La justicia & el juicio",
      it: "La giustizia & il giudizio",
      tr: "Adalet & yargı",
      de: "Gerechtigkeit & Urteil",
      ja: "正義と裁き",
    },
    desc: {
      fr: "Juger, punir, réparer, rendre des comptes",
      en: "Judge, punish, make amends, answer for it",
      es: "Juzgar, castigar, reparar, rendir cuentas",
      it: "Giudicare, punire, riparare, renderne conto",
      tr: "Yargılamak, cezalandırmak, telafi etmek, hesap vermek",
      de: "Richten, bestrafen, wiedergutmachen, Rechenschaft ablegen",
      ja: "裁く、罰する、償う、責任を取る",
    },
  },
  {
    slug: "change",
    emoji: "🦋",
    bg: "linear-gradient(135deg, #f0fdfa 0%, #99f6e4 100%)",
    border: "#5eead4",
    labels: {
      fr: "Le changement & la métamorphose",
      en: "Change & transformation",
      es: "El cambio & la metamorfosis",
      it: "Il cambiamento & la metamorfosi",
      tr: "Değişim & dönüşüm",
      de: "Wandel & Verwandlung",
      ja: "変化と変容",
    },
    desc: {
      fr: "Se transformer, s'adapter, tourner la page",
      en: "Transform, adapt, turn the page",
      es: "Transformarse, adaptarse, pasar página",
      it: "Trasformarsi, adattarsi, voltare pagina",
      tr: "Dönüşmek, uyum sağlamak, sayfayı çevirmek",
      de: "Sich wandeln, sich anpassen, ein neues Kapitel aufschlagen",
      ja: "変わる、適応する、新しいページをめくる",
    },
  },
  {
    slug: "food",
    emoji: "🍽️",
    bg: "linear-gradient(135deg, #fef6e4 0%, #f3d9a4 100%)",
    border: "#e0b978",
    labels: {
      fr: "Le pain & la table",
      en: "Bread & the table",
      es: "El pan & la mesa",
      it: "Il pane & la tavola",
      tr: "Ekmek & sofra",
      de: "Brot & Tisch",
      ja: "パンと食卓",
    },
    desc: {
      fr: "Manger, partager, cuisiner, se nourrir",
      en: "Eat, share, cook, nourish yourself",
      es: "Comer, compartir, cocinar, alimentarse",
      it: "Mangiare, condividere, cucinare, nutrirsi",
      tr: "Yemek, paylaşmak, pişirmek, beslenmek",
      de: "Essen, teilen, kochen, sich nähren",
      ja: "食べる、分かち合う、料理する、育む",
    },
  },
];

// Native-speaker proofreading welcome for the 4 domains above (knowledge,
// justice, change, food), especially tr/ja — same convention as voyageLabels.ts.
// They already exist as plain entries in domainDefs.ts (used by the Concepts
// page's full 20-domain browse grid + /search?domain=) — these are their
// editorial/poetic counterparts, curated for the Voyage picker specifically,
// same pattern as the other 16. Emoji kept aligned with domainDefs.ts
// (knowledge 📖, food 🍽️) so the same domain doesn't wear two different
// icons depending on which page a user arrives from.

export const EDITORIAL_DOMAIN_MAP: Record<string, EditorialDomain> = Object.fromEntries(
  EDITORIAL_DOMAINS.map((d) => [d.slug, d])
);

// Second level: purely presentational grouping for the Voyage composer's
// accordion (Lot "carte pays" — QA session 21/07). The filter value sent to
// the API is always a leaf EditorialDomain slug, exactly as before — grouping
// only changes how the 20 pills are chunked visually, nothing in the backend
// or the /random /search contract changes.
export type DomainGroup = {
  slug: string;
  emoji: string;
  labels: Record<UILang, string>;
  children: string[];
};

export const DOMAIN_GROUPS: DomainGroup[] = [
  {
    slug: "wisdom-knowledge",
    emoji: "🦉",
    labels: {
      fr: "Sagesse & savoir", en: "Wisdom & knowledge",
      es: "Sabiduría & saber", it: "Saggezza & sapere",
      tr: "Bilgelik & bilgi", de: "Weisheit & Wissen", ja: "知恵と知識",
    },
    children: ["wisdom", "knowledge"],
  },
  {
    slug: "time-change",
    emoji: "⏳",
    labels: {
      fr: "Temps & mutation", en: "Time & change",
      es: "Tiempo & cambio", it: "Tempo & cambiamento",
      tr: "Zaman & değişim", de: "Zeit & Wandel", ja: "時間と変化",
    },
    children: ["time", "change"],
  },
  {
    slug: "morality-justice",
    emoji: "⚖️",
    labels: {
      fr: "Morale & justice", en: "Morality & justice",
      es: "Moral & justicia", it: "Morale & giustizia",
      tr: "Ahlak & adalet", de: "Moral & Gerechtigkeit", ja: "道徳と正義",
    },
    children: ["morality", "justice"],
  },
  {
    slug: "speech-conflict",
    emoji: "🗣️",
    labels: {
      fr: "Mots & conflits", en: "Words & conflict",
      es: "Palabras & conflicto", it: "Parole & conflitto",
      tr: "Sözler & çatışma", de: "Worte & Konflikt", ja: "言葉と争い",
    },
    children: ["speech", "humor", "conflict"],
  },
  {
    slug: "pleasure-love",
    emoji: "❤️",
    labels: {
      fr: "Amour & plaisirs", en: "Love & pleasure", es: "Amor & placeres",
      it: "Amore & piaceri", tr: "Aşk & zevkler", de: "Liebe & Genuss", ja: "愛と喜び",
    },
    children: ["relations", "pleasure", "food"],
  },
  {
    slug: "effort-ambition",
    emoji: "👑",
    labels: {
      fr: "Effort & ambition", en: "Effort & ambition", es: "Esfuerzo & ambición",
      it: "Sforzo & ambizione", tr: "Çaba & hırs", de: "Mühe & Ehrgeiz", ja: "努力と野心",
    },
    children: ["work", "ambition"],
  },
  {
    slug: "money-luck",
    emoji: "💰",
    labels: {
      fr: "Argent & hasard", en: "Money & luck", es: "Dinero & suerte",
      it: "Soldi & fortuna", tr: "Para & şans", de: "Geld & Glück", ja: "お金と運",
    },
    children: ["money", "luck"],
  },
  {
    slug: "body-nature",
    emoji: "🌿",
    labels: {
      fr: "Corps & nature", en: "Body & nature", es: "Cuerpo & naturaleza",
      it: "Corpo & natura", tr: "Beden & doğa", de: "Körper & Natur", ja: "体と自然",
    },
    children: ["body", "nature"],
  },
  {
    slug: "emotions",
    emoji: "💛",
    labels: {
      fr: "Émotions", en: "Emotions", es: "Emociones",
      it: "Emozioni", tr: "Duygular", de: "Gefühle", ja: "感情",
    },
    children: ["emotions"],
  },
  {
    slug: "travel",
    emoji: "🌍",
    labels: {
      fr: "Voyage", en: "Travel", es: "Viaje",
      it: "Viaggio", tr: "Seyahat", de: "Reise", ja: "旅",
    },
    children: ["travel"],
  },
];
