export const TAG_ICONS: Record<string, string> = {
  argent: '💰', money: '💰', richesse: '💰', wealth: '💰', finances: '💰',
  pauvreté: '💰', poverty: '💰', prix: '💰', price: '💰', dépense: '💰',
  animal: '🐾', animals: '🐾', animaux: '🐾',
  chien: '🐕', dog: '🐕', chat: '🐱', cat: '🐱', cheval: '🐴', horse: '🐴',
  oiseau: '🐦', bird: '🐦', poisson: '🐟', fish: '🐟', vache: '🐄', cow: '🐄',
  cochon: '🐷', pig: '🐷', serpent: '🐍', snake: '🐍', loup: '🐺', wolf: '🐺',
  ours: '🐻', bear: '🐻', lapin: '🐰', rabbit: '🐰', renard: '🦊', fox: '🦊',
  singe: '🐒', monkey: '🐒', mouton: '🐑', sheep: '🐑', kangourou: '🦘', kangaroo: '🦘',
  feu: '🔥', fire: '🔥', flamme: '🔥', flame: '🔥',
  eau: '💧', water: '💧', pluie: '🌧️', rain: '🌧️',
  mer: '🌊', sea: '🌊', ocean: '🌊', rivière: '🌊', river: '🌊',
  peur: '😱', fear: '😱', fright: '😱', crainte: '😱',
  chance: '🍀', luck: '🍀', malchance: '🍀',
  pied: '🦶', foot: '🦶', feet: '🦶', main: '✋', hand: '✋', hands: '✋',
  tête: '🧠', head: '🧠', oeil: '👁️', yeux: '👁️', eye: '👁️', eyes: '👁️',
  bouche: '👄', mouth: '👄', nez: '👃', nose: '👃',
  bras: '💪', arm: '💪', corps: '🫀', body: '🫀',
  temps: '⏰', time: '⏰', heure: '⏰', hour: '⏰',
  travail: '💼', work: '💼', job: '💼', boulot: '💼',
  nourriture: '🍽️', food: '🍽️', cake: '🎂', gâteau: '🎂',
  pain: '🍞', bread: '🍞', vin: '🍷', wine: '🍷',
  bière: '🍺', beer: '🍺', café: '☕', coffee: '☕',
  amour: '❤️', love: '❤️', coeur: '❤️', heart: '❤️',
  joie: '😄', joy: '😄', happiness: '😄', bonheur: '😄',
  tristesse: '😢', sadness: '😢', sad: '😢',
  colère: '😠', anger: '😠', honte: '😳', shame: '😳',
  mensonge: '🤥', lie: '🤥', tromperie: '🤥', deception: '🤥',
  intelligence: '🧠', clever: '🧠', smart: '🧠',
  mort: '💀', death: '💀', dead: '💀',
  maison: '🏠', home: '🏠', house: '🏠',
  famille: '👨‍👩‍👧', family: '👨‍👩‍👧',
  ami: '🤝', amitié: '🤝', friend: '🤝', friendship: '🤝', mate: '🤝',
  voyage: '✈️', travel: '✈️', partir: '🚶', leaving: '🚶',
  soleil: '☀️', sun: '☀️', neige: '❄️', snow: '❄️', froid: '❄️', cold: '❄️',
  vent: '💨', wind: '💨',
  fête: '🎉', party: '🎉', fun: '🎉',
  sommeil: '😴', sleep: '😴', tired: '😴', fatigue: '😴',
  jeu: '🎮', game: '🎮', sport: '⚽',
  nature: '🌿', arbre: '🌳', tree: '🌳', fleur: '🌸', flower: '🌸',
  communication: '💬', discussion: '💬', parole: '💬', speech: '💬',
  relations: '👥', relation: '👥', people: '👥',
  émotions: '🎭', emotion: '🎭', sentiment: '🎭', feeling: '🎭',
  caractère: '😎', personality: '😎', character: '😎',
  effort: '💪', courage: '🦁', bravoure: '🦁', bravery: '🦁',
  succès: '🏆', success: '🏆', victoire: '🏆', victory: '🏆',
  échec: '❌', failure: '❌', défaite: '❌', defeat: '❌',
  météo: '🌦️', weather: '🌦️',
  santé: '💊', health: '💊', maladie: '💊', illness: '💊',
  humor: '😂', humour: '😂', rire: '😂', laugh: '😂',
  surprise: '😮', étonnement: '😮', astonishment: '😮',
  decision: '🤔', choix: '🤔', choice: '🤔',
  action: '⚡', activité: '⚡', activity: '⚡',
  responsibility: '🎯', responsabilité: '🎯',
  conflit: '⚔️', conflict: '⚔️', dispute: '⚔️',
  ironie: '🙃', irony: '🙃', sarcasme: '🙃', sarcasm: '🙃',
  secret: '🤫', mystère: '🤫', mystery: '🤫',
  maladresse: '🤦', clumsiness: '🤦', gaffe: '🤦',
  // Linguistic type tags
  proverb: '📜', proverbe: '📜', proverbio: '📜',
  adage: '💡', adagio: '💡',
  saying: '🗣️', dicton: '🗣️', dicho: '🗣️', detto: '🗣️',
  maxim: '✍️', maxime: '✍️', máxima: '✍️', massima: '✍️',
  locution: '🔤', locución: '🔤', locuzione: '🔤',
  cliche: '🎭', cliché: '🎭', klişe: '🎭',
  // Slugs anglais canoniques (post-normalisation V3A)
  emotions: '🎭', relationships: '👥', lying: '🤥',
  colors: '🎨', energy: '✨', laziness: '😴',
  difficulty: '😤', honesty: '🫡', caution: '⚠️',
  freedom: '🕊️', optimism: '🌟', wisdom: '🦉',
  generosity: '🎁', betrayal: '🗡️', disappointment: '😞',
  slang: '💬', politics: '🏛️', speed: '💨',
  mistake: '😬', escape: '🏃', distrust: '🤨',
  mockery: '😏', criticism: '🗣️', acceptance: '🤗',
  consequences: '⚖️', exaggeration: '📢', resourcefulness: '🧩',
  ambition: '🚀', culture: '🌍', silence: '🤫',
  movement: '🏃', patience: '🕐',
  // Espagnol
  dinero: '💰', trabajo: '💼', animales: '🐾',
  fuego: '🔥', agua: '💧', miedo: '😱', suerte: '🍀',
  amor: '❤️', amistad: '🤝', alegría: '😄', tristeza: '😢',
  comida: '🍽️', sueño: '😴', viajes: '✈️',
  esfuerzo: '💪', conflicto: '⚔️',
  // High-usage tags — S56
  fate: '🎲', destiny: '⭐', tradition: '🏺', trust: '🫱',
  pride: '👑', hope: '🌱', advice: '💡', humility: '🙏',
  loyalty: '💙', youth: '🌸', opportunity: '🚪', resilience: '🔄',
  resignation: '🤷', marriage: '💒', truth: '✅', experience: '📖',
  homesickness: '🏡', foolishness: '🤪', respect: '🫡', perseverance: '🏃',
  hospitality: '🍽️', appearance: '🪞', change: '🦋', age: '⏳',
  support: '🤲', determination: '🎯', nostalgia: '🕰️',
  'old-age': '👴', risk: '⚠️', inevitability: '♟️', faith: '🙏',
  despair: '😔', metaphor: '💭', motivation: '🔥', arrogance: '😤',
  behavior: '🧠', misfortune: '☁️', justice: '⚖️', learning: '📚',
  power: '👑', regret: '😔', honor: '🎖️', lies: '🤥', danger: '⚠️',
  hardship: '⛰️', skill: '✨', unity: '🤝',
  'village-life': '🏘️', phrasebook: '📚',
  british: '🇬🇧', australian: '🦘',
};

export function tagIcon(tag: string): string {
  return TAG_ICONS[tag.toLowerCase()] || TAG_ICONS[tag] || '';
}

// Curated list for the emoji keyboard: one canonical English slug per distinct emoji
export const EMOJI_KEYBOARD: Array<{ emoji: string; slug: string }> = [
  { emoji: '❤️', slug: 'love' },
  { emoji: '😄', slug: 'joy' },
  { emoji: '😢', slug: 'sadness' },
  { emoji: '😠', slug: 'anger' },
  { emoji: '😱', slug: 'fear' },
  { emoji: '😳', slug: 'shame' },
  { emoji: '😮', slug: 'surprise' },
  { emoji: '😴', slug: 'sleep' },
  { emoji: '🤥', slug: 'lying' },
  { emoji: '😂', slug: 'humor' },
  { emoji: '🙃', slug: 'irony' },
  { emoji: '😎', slug: 'character' },
  { emoji: '🤔', slug: 'decision' },
  { emoji: '😤', slug: 'difficulty' },
  { emoji: '😞', slug: 'disappointment' },
  { emoji: '😔', slug: 'despair' },
  { emoji: '😬', slug: 'mistake' },
  { emoji: '😏', slug: 'mockery' },
  { emoji: '🤦', slug: 'clumsiness' },
  { emoji: '🤷', slug: 'resignation' },
  { emoji: '🤗', slug: 'acceptance' },
  { emoji: '🤨', slug: 'distrust' },
  { emoji: '🤪', slug: 'foolishness' },
  { emoji: '💰', slug: 'money' },
  { emoji: '💼', slug: 'work' },
  { emoji: '🏆', slug: 'success' },
  { emoji: '❌', slug: 'failure' },
  { emoji: '🚀', slug: 'ambition' },
  { emoji: '⚡', slug: 'action' },
  { emoji: '🎯', slug: 'responsibility' },
  { emoji: '⚔️', slug: 'conflict' },
  { emoji: '⚖️', slug: 'justice' },
  { emoji: '🎁', slug: 'generosity' },
  { emoji: '🗡️', slug: 'betrayal' },
  { emoji: '🏃', slug: 'escape' },
  { emoji: '🤝', slug: 'friendship' },
  { emoji: '👥', slug: 'relationships' },
  { emoji: '👨‍👩‍👧', slug: 'family' },
  { emoji: '💒', slug: 'marriage' },
  { emoji: '🏠', slug: 'home' },
  { emoji: '✈️', slug: 'travel' },
  { emoji: '🍽️', slug: 'food' },
  { emoji: '🍷', slug: 'wine' },
  { emoji: '🍺', slug: 'beer' },
  { emoji: '☕', slug: 'coffee' },
  { emoji: '🍞', slug: 'bread' },
  { emoji: '🐾', slug: 'animals' },
  { emoji: '🐕', slug: 'dog' },
  { emoji: '🐱', slug: 'cat' },
  { emoji: '🐴', slug: 'horse' },
  { emoji: '🐟', slug: 'fish' },
  { emoji: '🐺', slug: 'wolf' },
  { emoji: '🦊', slug: 'fox' },
  { emoji: '🐻', slug: 'bear' },
  { emoji: '🦁', slug: 'courage' },
  { emoji: '🐒', slug: 'monkey' },
  { emoji: '🐑', slug: 'sheep' },
  { emoji: '🔥', slug: 'fire' },
  { emoji: '💧', slug: 'water' },
  { emoji: '🌊', slug: 'sea' },
  { emoji: '🌧️', slug: 'rain' },
  { emoji: '☀️', slug: 'sun' },
  { emoji: '❄️', slug: 'cold' },
  { emoji: '💨', slug: 'wind' },
  { emoji: '🌿', slug: 'nature' },
  { emoji: '🌳', slug: 'tree' },
  { emoji: '🌸', slug: 'flower' },
  { emoji: '🌍', slug: 'culture' },
  { emoji: '🧠', slug: 'head' },
  { emoji: '💪', slug: 'arm' },
  { emoji: '🦶', slug: 'foot' },
  { emoji: '✋', slug: 'hand' },
  { emoji: '👁️', slug: 'eyes' },
  { emoji: '👄', slug: 'mouth' },
  { emoji: '💀', slug: 'death' },
  { emoji: '💊', slug: 'health' },
  { emoji: '⏰', slug: 'time' },
  { emoji: '🕰️', slug: 'nostalgia' },
  { emoji: '💬', slug: 'speech' },
  { emoji: '🎭', slug: 'emotions' },
  { emoji: '🎉', slug: 'party' },
  { emoji: '🎮', slug: 'game' },
  { emoji: '🍀', slug: 'luck' },
  { emoji: '🎲', slug: 'fate' },
  { emoji: '🦉', slug: 'wisdom' },
  { emoji: '🌟', slug: 'optimism' },
  { emoji: '🌱', slug: 'hope' },
  { emoji: '🕊️', slug: 'freedom' },
  { emoji: '👑', slug: 'pride' },
  { emoji: '💙', slug: 'loyalty' },
  { emoji: '🤫', slug: 'secret' },
  { emoji: '✅', slug: 'truth' },
  { emoji: '⚠️', slug: 'caution' },
  { emoji: '☁️', slug: 'misfortune' },
  { emoji: '⭐', slug: 'destiny' },
  { emoji: '🏺', slug: 'tradition' },
  { emoji: '📖', slug: 'experience' },
  { emoji: '📜', slug: 'proverb' },
  { emoji: '💡', slug: 'adage' },
  { emoji: '🗣️', slug: 'saying' },
];
