export const TAG_ICONS: Record<string, string> = {
  argent: '💰', money: '💰', richesse: '💰', wealth: '💰', finances: '💰',
  pauvreté: '💰', poverty: '💰', prix: '💰', price: '💰', dépense: '💰',
  animal: '🐾', animals: '🐾', animaux: '🐾',
  chien: '🐕', dog: '🐕', chat: '🐱', cat: '🐱', cheval: '🐴', horse: '🐴',
  oiseau: '🐦', bird: '🐦', poisson: '🐟', fish: '🐟', vache: '🐄', cow: '🐄',
  cochon: '🐷', pig: '🐷', serpent: '🐍', snake: '🐍', loup: '🐺', wolf: '🐺',
  ours: '🐻', bear: '🐻', lapin: '🐰', rabbit: '🐰', renard: '🦊', fox: '🦊',
  singe: '🐒', monkey: '🐒', mouton: '🐑', sheep: '🐑', kangourou: '🦘', kangaroo: '🦘',
  feu: '🔥', fire: '🔥', flamme: '🔥', flame: '🔥',
  eau: '💧', water: '💧', pluie: '🌧️', rain: '🌧️',
  mer: '🌊', sea: '🌊', ocean: '🌊', rivière: '🌊', river: '🌊',
  peur: '😱', fear: '😱', fright: '😱', crainte: '😱',
  chance: '🍀', luck: '🍀', malchance: '🍀',
  pied: '🦶', foot: '🦶', feet: '🦶', main: '✋', hand: '✋', hands: '✋',
  tête: '🧠', head: '🧠', oeil: '👁️', yeux: '👁️', eye: '👁️', eyes: '👁️',
  bouche: '👄', mouth: '👄', nez: '👃', nose: '👃',
  bras: '💪', arm: '💪', corps: '🫀', body: '🫀',
  temps: '⏰', time: '⏰', heure: '⏰', hour: '⏰',
  travail: '💼', work: '💼', job: '💼', boulot: '💼',
  nourriture: '🍽️', food: '🍽️', cake: '🎂', gâteau: '🎂',
  pain: '🍞', bread: '🍞', vin: '🍷', wine: '🍷',
  bière: '🍺', beer: '🍺', café: '☕', coffee: '☕',
  amour: '❤️', love: '❤️', coeur: '❤️', heart: '❤️',
  joie: '😄', joy: '😄', happiness: '😄', bonheur: '😄',
  tristesse: '😢', sadness: '😢', sad: '😢',
  colère: '😠', anger: '😠', honte: '😳', shame: '😳',
  mensonge: '🤥', lie: '🤥', tromperie: '🤥', deception: '🤥',
  intelligence: '🧠', clever: '🧠', smart: '🧠',
  mort: '💀', death: '💀', dead: '💀',
  maison: '🏠', home: '🏠', house: '🏠',
  famille: '👨‍👩‍👧', family: '👨‍👩‍👧',
  ami: '🤝', amitié: '🤝', friend: '🤝', friendship: '🤝', mate: '🤝',
  voyage: '✈️', travel: '✈️', partir: '🚶', leaving: '🚶',
  soleil: '☀️', sun: '☀️', neige: '❄️', snow: '❄️', froid: '❄️', cold: '❄️',
  vent: '💨', wind: '💨',
  fête: '🎉', party: '🎉', fun: '🎉',
  sommeil: '😴', sleep: '😴', tired: '😴', fatigue: '😴',
  jeu: '🎮', game: '🎮', sport: '⚽',
  nature: '🌿', arbre: '🌳', tree: '🌳', fleur: '🌸', flower: '🌸',
  communication: '💬', discussion: '💬', parole: '💬', speech: '💬',
  relations: '👥', relation: '👥', people: '👥',
  émotions: '🎭', emotion: '🎭', sentiment: '🎭', feeling: '🎭',
  caractère: '😎', personality: '😎', character: '😎',
  effort: '💪', courage: '🦁', bravoure: '🦁', bravery: '🦁',
  succès: '🏆', success: '🏆', victoire: '🏆', victory: '🏆',
  échec: '❌', failure: '❌', défaite: '❌', defeat: '❌',
  météo: '🌦️', weather: '🌦️',
  santé: '💊', health: '💊', maladie: '💊', illness: '💊',
  humor: '😂', humour: '😂', rire: '😂', laugh: '😂',
  surprise: '😮', étonnement: '😮', astonishment: '😮',
  decision: '🤔', choix: '🤔', choice: '🤔',
  action: '⚡', activité: '⚡', activity: '⚡',
  responsibility: '🎯', responsabilité: '🎯',
  conflit: '⚔️', conflict: '⚔️', dispute: '⚔️',
  ironie: '🙃', irony: '🙃', sarcasme: '🙃', sarcasm: '🙃',
  secret: '🤫', mystère: '🤫', mystery: '🤫',
  maladresse: '🤦', clumsiness: '🤦', gaffe: '🤦',
  // Linguistic type tags
  proverb: '📜', proverbe: '📜', proverbio: '📜',
  adage: '💡', adagio: '💡',
  saying: '🗣️', dicton: '🗣️', dicho: '🗣️', detto: '🗣️',
  maxim: '✍️', maxime: '✍️', máxima: '✍️', massima: '✍️',
  locution: '🔤', locución: '🔤', locuzione: '🔤',
  cliche: '🎭', cliché: '🎭', klişe: '🎭',
  // Slugs anglais canoniques (post-normalisation V3A)
  emotions: '🎭', relationships: '👥', lying: '🤥',
  colors: '🎨', energy: '✨', laziness: '😴',
  difficulty: '😤', honesty: '🫡', caution: '⚠️',
  freedom: '🕊️', optimism: '🌟', wisdom: '🦉',
  generosity: '🎁', betrayal: '🗡️', disappointment: '😞',
  slang: '💬', politics: '🏛️', speed: '💨',
  mistake: '😬', escape: '🏃', distrust: '🤨',
  mockery: '😏', criticism: '🗣️', acceptance: '🤗',
  consequences: '⚖️', exaggeration: '📢', resourcefulness: '🧩',
  ambition: '🚀', culture: '🌍', silence: '🤫',
  movement: '🏃', patience: '🕐',
  // Espagnol
  dinero: '💰', trabajo: '💼', animales: '🐾',
  fuego: '🔥', agua: '💧', miedo: '😱', suerte: '🍀',
  amor: '❤️', amistad: '🤝', alegría: '😄', tristeza: '😢',
  comida: '🍽️', sueño: '😴', viajes: '✈️',
  esfuerzo: '💪', conflicto: '⚔️',
};

export function tagIcon(tag: string): string {
  return TAG_ICONS[tag.toLowerCase()] || TAG_ICONS[tag] || '';
}
