"""add_content_translations

Revision ID: 8e23ae44264c
Revises: e49e73ce50fc
Create Date: 2026-05-20 18:48:31.794422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e23ae44264c'
down_revision: Union[str, Sequence[str], None] = 'e49e73ce50fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_translations',
    sa.Column('expression_id', sa.String(length=120), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('literal', sa.Text(), nullable=True),
    sa.Column('idiomatic', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expression_id', 'target_lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_translations')
    # ### end Alembic commands ###
