"""initial schema

Revision ID: ad54ec3bfd7f
Revises: 
Create Date: 2026-05-19 17:54:29.611309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad54ec3bfd7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('expressions',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('register', sa.String(length=20), nullable=True),
    sa.Column('illustration', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_names',
    sa.Column('tag_id', sa.String(length=60), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'locale')
    )
    op.create_table('expression_content',
    sa.Column('expression_id', sa.String(length=120), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expression_id', 'locale')
    )
    op.create_table('expression_tags',
    sa.Column('expression_id', sa.String(length=120), nullable=False),
    sa.Column('tag_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expression_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expression_tags')
    op.drop_table('expression_content')
    op.drop_table('tag_names')
    op.drop_table('expressions')
    op.drop_table('tags')
    op.drop_table('concepts')
    # ### end Alembic commands ###
