"""add type column to expressions

Revision ID: ff8d8b9f2d35
Revises: ad54ec3bfd7f
Create Date: 2026-05-20 01:16:33.945625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8d8b9f2d35'
down_revision: Union[str, Sequence[str], None] = 'ad54ec3bfd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expressions', sa.Column('type', sa.String(length=20), server_default='expression', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expressions', 'type')
    # ### end Alembic commands ###
