import json
from pathlib import Path

DATA_PATH = Path(__file__).parent.parent / "data" / "expressions.json"

def e(id, expression, meaning, origin, example, register, tags, region):
    return {
        "id": id, "expression": expression, "meaning": meaning,
        "origin": origin, "example": example, "register": register,
        "tags": tags, "region": region, "illustration": None, "language": "en"
    }

NEW = [
    # ── US ──────────────────────────────────────────────────────────────
    e("the-whole-nine-yards","The whole nine yards","Everything, the full amount","Possibly WWII — the length of a fighter plane's ammunition belt","We're doing the whole nine yards for the party — catering, decorations, live band.","informal",["completeness","effort","all"],"us"),
    e("shoot-the-breeze","Shoot the breeze","To chat casually about nothing important","American slang, early 1900s","We spent the whole afternoon on the porch shooting the breeze.","informal",["conversation","relaxation","friendship"],"us"),
    e("hit-the-road","Hit the road","To leave or begin a journey","American English, 19th century","It's getting dark — we should hit the road.","informal",["travel","departure","leaving"],"us"),
    e("bite-the-dust","Bite the dust","To fail, die, or be defeated","American Western imagery, popularized by cowboy films","Three businesses on this block bit the dust during the pandemic.","informal",["failure","defeat","death"],"us"),
    e("get-cold-feet","Get cold feet","To suddenly become nervous or hesitant before doing something","American English, early 20th century","He got cold feet and backed out of the deal at the last minute.","informal",["fear","hesitation","nerves"],"us"),
    e("by-the-skin-of-your-teeth","By the skin of your teeth","Just barely making it","From the Bible, Book of Job; widely used in American English","We caught the last flight by the skin of our teeth.","standard",["luck","close-call","survival"],"us"),
    e("get-the-ball-rolling","Get the ball rolling","To start something, to initiate action","American English, sports imagery","Let's get the ball rolling on this project — we're behind schedule.","standard",["action","beginning","initiative"],"us"),
    e("blow-off-steam","Blow off steam","To release frustration or stress","From steam engines; widely used in the US","He goes to the gym every day to blow off steam after work.","informal",["stress","emotions","relief"],"us"),
    e("think-outside-the-box","Think outside the box","To think creatively beyond conventional solutions","American corporate slang, 1970s–80s","We need to think outside the box to solve this problem.","standard",["creativity","innovation","thinking"],"us"),
    e("drop-the-ball","Drop the ball","To fail to fulfill a responsibility","From American football","I dropped the ball on the deadline — completely forgot about it.","informal",["failure","responsibility","mistake"],"us"),
    e("on-the-same-page","On the same page","In agreement, sharing the same understanding","American business slang","Before we start, let's make sure we're all on the same page.","standard",["agreement","communication","understanding"],"us"),
    e("give-someone-a-heads-up","Give someone a heads-up","To warn or inform someone in advance","American military slang","She gave me a heads-up about the meeting change.","informal",["warning","information","communication"],"us"),
    e("touch-base","Touch base","To briefly check in with someone","American baseball metaphor","I'll touch base with you on Monday to see how things are going.","standard",["communication","check-in","contact"],"us"),
    e("put-on-the-back-burner","Put on the back burner","To postpone or deprioritize something","From cooking; American expression","We put the expansion plans on the back burner until next year.","standard",["priority","delay","planning"],"us"),
    e("take-a-rain-check","Take a rain check","To decline now but accept an offer later","Baseball: rain-cancelled games gave spectators rain checks to return","I can't make dinner tonight, but I'll take a rain check.","informal",["postpone","decline","polite"],"us"),
    e("by-the-book","By the book","Following all the rules exactly","American English","The new manager insists on doing everything by the book.","standard",["rules","procedure","compliance"],"us"),
    e("break-the-ice","Break the ice","To relieve tension or start a conversation","17th century English; widely used in American English","He told a joke to break the ice at the awkward dinner party.","standard",["conversation","social","beginning"],"us"),
    e("bring-home-the-bacon","Bring home the bacon","To earn money to support the family","Popularized in early 20th century American English","Her new job really brings home the bacon.","informal",["money","work","family"],"us"),
    e("face-the-music","Face the music","To accept the consequences of your actions","American origin, possibly military or theater","After the scandal, the CEO had to face the music.","standard",["consequences","accountability","responsibility"],"us"),
    e("call-it-a-day","Call it a day","To decide to stop working","American English","We've made great progress — let's call it a day.","informal",["work","stopping","rest"],"us"),
    e("catch-someone-red-handed","Catch someone red-handed","To catch someone in the act of doing something wrong","Old English law; widely used in American English","The thief was caught red-handed by the security camera.","standard",["crime","caught","guilt"],"us"),
    e("cold-turkey","Cold turkey","Stopping an addictive behavior abruptly and completely","American slang, early 20th century","He quit smoking cold turkey and never looked back.","informal",["addiction","stopping","willpower"],"us"),
    e("cut-to-the-chase","Cut to the chase","To get to the point without wasting time","American filmmaking — cutting to the action scene","I don't have much time, so let me cut to the chase.","informal",["communication","directness","efficiency"],"us"),
    e("dead-in-the-water","Dead in the water","Unable to function or make progress","Nautical expression; widely used in the US","Without funding, the project is dead in the water.","standard",["failure","stuck","hopeless"],"us"),
    e("dont-beat-a-dead-horse","Don't beat a dead horse","Stop wasting effort on something that won't change","American expression","We've debated this enough — let's not beat a dead horse.","informal",["futility","argument","persistence"],"us"),
    e("down-to-earth","Down to earth","Practical, humble, and not pretentious","American English","Despite her success, she remains remarkably down to earth.","standard",["personality","humility","practicality"],"us"),
    e("get-the-green-light","Get the green light","To receive approval or permission to proceed","From traffic signals; American English","We finally got the green light to start construction.","standard",["approval","permission","progress"],"us"),
    e("give-the-benefit-of-the-doubt","Give the benefit of the doubt","To trust someone's good intentions despite uncertainty","Legal term; widely used in American English","I'll give him the benefit of the doubt this time.","standard",["trust","fairness","judgment"],"us"),
    e("have-a-ball","Have a ball","To have a great time","American slang","The kids had a ball at the birthday party.","informal",["fun","enjoyment","celebration"],"us"),
    e("have-the-upper-hand","Have the upper hand","To have an advantage over someone","American English","The home team had the upper hand for most of the game.","standard",["advantage","power","control"],"us"),
    e("hit-a-home-run","Hit a home run","To succeed greatly or achieve something impressive","From baseball; quintessentially American","Her presentation hit a home run with the investors.","informal",["success","achievement","sports"],"us"),
    e("hook-line-and-sinker","Hook, line, and sinker","Completely, entirely believing something","From fishing; American English","He fell for her story hook, line, and sinker.","informal",["deception","belief","naivety"],"us"),
    e("in-a-pickle","In a pickle","In a difficult or awkward situation","From Dutch; widely used in American English","I'm in a real pickle — I double-booked my calendar.","informal",["trouble","difficulty","problems"],"us"),
    e("in-the-long-run","In the long run","Over a long period of time; eventually","American English","Investing in quality always pays off in the long run.","standard",["time","perspective","future"],"us"),
    e("in-the-same-boat","In the same boat","In the same difficult situation as others","Nautical origin; widely used in American English","We're all in the same boat when it comes to budget cuts.","standard",["equality","shared-experience","solidarity"],"us"),
    e("keep-your-nose-to-the-grindstone","Keep your nose to the grindstone","To work hard and persistently","American expression, from sharpening tools","If you keep your nose to the grindstone, you'll get that promotion.","standard",["work","persistence","dedication"],"us"),
    e("kick-the-habit","Kick the habit","To stop a bad habit","American English","He finally kicked the habit after years of trying.","informal",["habit","addiction","change"],"us"),
    e("knock-it-out-of-the-park","Knock it out of the park","To do something exceptionally well","From baseball; American expression","She knocked it out of the park with her debut performance.","informal",["success","achievement","sports"],"us"),
    e("leave-no-stone-unturned","Leave no stone unturned","To try every possible option","From Greek mythology; widely used in American English","The detective left no stone unturned in his investigation.","standard",["thoroughness","effort","investigation"],"us"),
    e("like-a-fish-out-of-water","Like a fish out of water","Uncomfortable in an unfamiliar situation","From Chaucer; widely used in American English","In the corporate world, he felt like a fish out of water.","standard",["discomfort","unfamiliar","adaptation"],"us"),
    e("make-ends-meet","Make ends meet","To earn just enough money to cover expenses","American English","With two jobs, she barely makes ends meet.","standard",["money","poverty","survival"],"us"),
    e("on-the-ball","On the ball","Alert, attentive, and competent","American English","The new assistant is really on the ball.","informal",["competence","attention","alertness"],"us"),
    e("out-of-the-blue","Out of the blue","Unexpectedly, without warning","American English","Out of the blue, she called me after five years of silence.","standard",["surprise","unexpected","shock"],"us"),
    e("pass-the-buck","Pass the buck","To shift responsibility to someone else","American origin, from poker: the 'buck' marked the dealer","The manager always passes the buck when things go wrong.","informal",["responsibility","blame","avoidance"],"us"),
    e("pay-through-the-nose","Pay through the nose","To pay an excessively high price","American English, origin debated","You'll pay through the nose for tickets bought at the last minute.","informal",["money","expensive","price"],"us"),
    e("play-it-by-ear","Play it by ear","To improvise and decide as you go","From music; widely used in American English","We don't have a set plan — let's play it by ear.","informal",["improvise","flexibility","planning"],"us"),
    e("pull-strings","Pull strings","To use personal connections to get something done","American English","She pulled strings to get her son into the school.","informal",["influence","connections","power"],"us"),
    e("put-your-best-foot-forward","Put your best foot forward","To make the best possible impression","American English","It's your first day on the job — put your best foot forward.","standard",["impression","effort","attitude"],"us"),
    e("read-between-the-lines","Read between the lines","To understand the hidden meaning","American English","Reading between the lines, it's clear he wasn't happy about it.","standard",["understanding","hidden-meaning","communication"],"us"),
    e("roll-with-the-punches","Roll with the punches","To adapt to difficulties as they come","From boxing; American expression","Life is unpredictable — you've got to roll with the punches.","informal",["adaptation","resilience","flexibility"],"us"),
    e("saved-by-the-bell","Saved by the bell","Rescued from a bad situation at the last moment","From boxing; American expression","He was saved by the bell when his phone rang during the interrogation.","informal",["luck","rescue","timing"],"us"),
    e("shoot-for-the-stars","Shoot for the stars","To have very ambitious goals","American expression","Dream big and shoot for the stars.","standard",["ambition","dreams","goals"],"us"),
    e("slam-dunk","Slam dunk","A certain success or a sure thing","From basketball; quintessentially American","Winning this account would be a slam dunk for the team.","informal",["success","certainty","sports"],"us"),
    e("start-from-scratch","Start from scratch","To begin again from the very beginning","American expression","The redesign failed, so we're starting from scratch.","standard",["beginning","restart","effort"],"us"),
    e("step-up-to-the-plate","Step up to the plate","To take responsibility and rise to a challenge","From baseball; American expression","When the crisis hit, she stepped up to the plate.","standard",["responsibility","challenge","action"],"us"),
    e("take-the-plunge","Take the plunge","To commit to a risky or uncertain decision","American English","After months of hesitation, they took the plunge and bought the house.","standard",["decision","risk","commitment"],"us"),
    e("throw-in-the-towel","Throw in the towel","To give up, to admit defeat","From boxing; American expression","After three failed attempts, he threw in the towel.","informal",["defeat","giving-up","surrender"],"us"),
    e("throw-someone-under-the-bus","Throw someone under the bus","To sacrifice someone else to avoid blame","American slang, modern origin","When things went wrong, he threw his assistant under the bus.","informal",["betrayal","blame","sacrifice"],"us"),
    e("tie-up-loose-ends","Tie up loose ends","To complete unfinished details","American English","Before the merger closes, there are a few loose ends to tie up.","standard",["completion","details","work"],"us"),
    e("up-for-grabs","Up for grabs","Available to anyone, not yet decided","American English","With the champion injured, the title is up for grabs.","informal",["opportunity","competition","availability"],"us"),
    e("walking-on-eggshells","Walking on eggshells","Being very careful not to upset someone","American English","I feel like I'm walking on eggshells around him lately.","informal",["caution","tension","sensitivity"],"us"),
    e("when-pigs-fly","When pigs fly","Never; referring to something impossible","American English","He'll clean his room when pigs fly.","informal",["impossibility","sarcasm","humor"],"us"),
    e("wipe-the-slate-clean","Wipe the slate clean","To forget past mistakes and start fresh","American English","After their argument, they agreed to wipe the slate clean.","standard",["forgiveness","fresh-start","past"],"us"),
    e("a-dime-a-dozen","A dime a dozen","Very common and not special","American expression; a dime = 10 cents","Good excuses are a dime a dozen — results are what matter.","informal",["common","value","abundance"],"us"),
    e("a-penny-for-your-thoughts","A penny for your thoughts","Asking what someone is thinking about","American English","You've been staring out the window — a penny for your thoughts?","informal",["curiosity","thinking","conversation"],"us"),
    e("a-shot-in-the-dark","A shot in the dark","A wild guess with little chance of success","American English","Calling that number was a shot in the dark, but it paid off.","informal",["guess","uncertainty","risk"],"us"),
    e("add-insult-to-injury","Add insult to injury","To make a bad situation even worse","From Aesop's fables; widely used in American English","He not only fired her — to add insult to injury, he did it by text.","standard",["worsening","offense","unfair"],"us"),
    e("back-in-the-saddle","Back in the saddle","Returning to a previous role after a break","American cowboy culture","After her recovery, she's back in the saddle as CEO.","informal",["return","work","recovery"],"us"),
    e("bang-for-your-buck","Bang for your buck","Good value for money spent","American slang","This hotel offers incredible bang for your buck.","informal",["value","money","efficiency"],"us"),
    e("beat-someone-to-the-punch","Beat someone to the punch","To do something before someone else can","From boxing; American expression","Our competitor beat us to the punch with the new product launch.","informal",["competition","speed","advantage"],"us"),
    e("blow-the-whistle","Blow the whistle","To expose wrongdoing or illegal activity","American English","She blew the whistle on the financial fraud.","standard",["exposure","honesty","justice"],"us"),
    e("break-new-ground","Break new ground","To do something innovative and pioneering","American English","Their research is breaking new ground in cancer treatment.","standard",["innovation","pioneering","progress"],"us"),
    e("bring-to-the-table","Bring to the table","To contribute skills or resources to a discussion","American business slang","What exactly does this new partner bring to the table?","standard",["contribution","skills","business"],"us"),
    e("by-a-long-shot","By a long shot","By a great amount — often used in negatives","American English, from shooting","This isn't over by a long shot.","informal",["distance","certainty","competition"],"us"),
    e("call-the-shots","Call the shots","To be in charge, to make the decisions","American English","She's the one calling the shots around here.","standard",["authority","leadership","control"],"us"),
    e("cant-see-the-forest-for-the-trees","Can't see the forest for the trees","Too focused on details to see the big picture","American English","He's so caught up in the numbers he can't see the forest for the trees.","standard",["perspective","details","big-picture"],"us"),
    e("chew-the-fat","Chew the fat","To chat in a leisurely, informal way","American expression","The neighbors sat on the porch, chewing the fat all afternoon.","informal",["conversation","leisure","friendship"],"us"),
    e("chip-in","Chip in","To contribute money or effort with others","American English","Everyone chipped in to buy the boss a farewell gift.","informal",["contribution","sharing","generosity"],"us"),
    e("cream-of-the-crop","Cream of the crop","The best of a group","American English","These graduates are the cream of the crop.","standard",["excellence","best","quality"],"us"),
    e("dead-ringer","Dead ringer","Someone who looks exactly like someone else","American English","He's a dead ringer for the president.","informal",["resemblance","looks","similarity"],"us"),
    e("dont-hold-your-breath","Don't hold your breath","Don't expect something to happen soon","American English","Don't hold your breath waiting for an apology from him.","informal",["expectation","waiting","sarcasm"],"us"),
    e("down-in-the-dumps","Down in the dumps","Feeling sad and depressed","American English","She's been down in the dumps since losing her job.","informal",["sadness","depression","mood"],"us"),
    e("drop-a-bombshell","Drop a bombshell","To reveal shocking or unexpected news","American expression","She dropped a bombshell when she announced her resignation.","informal",["news","shock","revelation"],"us"),
    e("easy-as-pie","Easy as pie","Very easy","American expression","Don't worry about it — the recipe is easy as pie.","informal",["ease","simplicity"],"us"),
    e("eat-crow","Eat crow","To humiliatingly admit you were wrong","American expression","After his confident prediction failed, he had to eat crow.","informal",["humiliation","wrong","pride"],"us"),
    e("fall-flat","Fall flat","To fail to produce the intended effect","American English","His jokes fell completely flat with the audience.","standard",["failure","humor","disappointment"],"us"),
    e("feel-blue","Feel blue","To feel sad or melancholy","American English","I've been feeling blue since my dog passed away.","informal",["sadness","emotions","mood"],"us"),
    e("fish-or-cut-bait","Fish or cut bait","Make a decision — commit or step aside","American fishing expression","We need an answer by Friday — fish or cut bait.","informal",["decision","commitment","action"],"us"),
    e("fly-off-the-handle","Fly off the handle","To suddenly become very angry","American expression; axe-heads could fly off their handles","He flies off the handle at the slightest provocation.","informal",["anger","temper","emotions"],"us"),
    e("from-the-get-go","From the get-go","From the very beginning","American slang","I knew from the get-go that this was going to be a problem.","informal",["beginning","start","origin"],"us"),
    e("get-a-grip","Get a grip","To calm down and take control of yourself","American English","Stop panicking and get a grip.","informal",["control","calm","emotions"],"us"),
    e("get-a-move-on","Get a move on","To hurry up","American English","We're going to be late — get a move on!","informal",["hurry","speed","impatience"],"us"),
    e("get-the-hang-of-it","Get the hang of it","To learn how to do something through practice","American English","Skiing is hard at first, but you'll get the hang of it.","informal",["learning","practice","skill"],"us"),
    e("give-it-a-shot","Give it a shot","To try something","American English","I've never cooked Thai food before, but I'll give it a shot.","informal",["attempt","trying","courage"],"us"),
    e("go-bananas","Go bananas","To go crazy or become wildly excited","American slang","The crowd went bananas when the band took the stage.","informal",["excitement","crazy","emotion"],"us"),
    e("go-out-on-a-limb","Go out on a limb","To take a risk or expose yourself to criticism","American expression; from climbing trees","I'll go out on a limb and say this plan won't work.","informal",["risk","opinion","vulnerability"],"us"),
    e("have-bigger-fish-to-fry","Have bigger fish to fry","To have more important things to deal with","American expression","Don't bother me with that now — I've got bigger fish to fry.","informal",["priorities","importance","busy"],"us"),
    e("have-butterflies","Have butterflies in your stomach","To feel nervous or anxious","American English","Every time before I speak in public, I get butterflies in my stomach.","standard",["nerves","anxiety","performance"],"us"),
    e("have-egg-on-your-face","Have egg on your face","To be embarrassed by a public mistake","American English","After his prediction was spectacularly wrong, he had egg on his face.","informal",["embarrassment","mistake","pride"],"us"),
    e("heads-up","Heads up","A warning or advance notice","American military slang","Just a heads-up: the client is in a bad mood today.","informal",["warning","information","communication"],"us"),
    e("hear-through-the-grapevine","Hear it through the grapevine","To hear news as informal rumor or gossip","American expression; also a famous Motown song","I heard through the grapevine that they're getting divorced.","informal",["gossip","rumor","news"],"us"),
    e("hit-the-spot","Hit the spot","To be exactly what was needed or wanted","American English","That coffee really hit the spot on a cold morning.","informal",["satisfaction","perfect","pleasure"],"us"),
    e("hold-your-horses","Hold your horses","Wait — slow down and be patient","American Western expression","Hold your horses — let me finish explaining before you decide.","informal",["patience","waiting","calm"],"us"),
    e("in-the-bag","In the bag","Certain to succeed","American English","We've already won — the deal is in the bag.","informal",["certainty","success","confidence"],"us"),
    e("in-the-doghouse","In the doghouse","In trouble with someone, out of favor","American English","He forgot their anniversary and is definitely in the doghouse.","informal",["trouble","relationships","mistake"],"us"),
    e("it-aint-over-till-the-fat-lady-sings","It ain't over till the fat lady sings","Don't assume something is finished before it truly ends","American sports saying; attributed to opera performances","Don't celebrate yet — it ain't over till the fat lady sings.","informal",["patience","sports","outcome"],"us"),
    e("jump-ship","Jump ship","To abandon an organization or cause","American English, nautical origin","Three key employees jumped ship before the layoffs.","informal",["leaving","abandonment","escape"],"us"),
    e("jump-to-conclusions","Jump to conclusions","To make hasty judgments without enough information","American English","Don't jump to conclusions — hear the whole story first.","standard",["judgment","haste","assumptions"],"us"),
    e("keep-a-low-profile","Keep a low profile","To avoid drawing attention to yourself","American English","After the scandal, she kept a low profile for months.","standard",["discretion","attention","hiding"],"us"),
    e("keep-someone-posted","Keep someone posted","To regularly update someone about a situation","American English","Keep me posted on how the interview goes.","standard",["communication","updates","information"],"us"),
    e("know-the-ropes","Know the ropes","To understand how something works","Nautical origin; widely used in American English","Ask Sarah — she knows the ropes around here.","standard",["knowledge","experience","expertise"],"us"),
    e("look-like-a-million-bucks","Look like a million bucks","To look very attractive or impressive","American English","You look like a million bucks in that suit.","informal",["appearance","compliment","attractiveness"],"us"),
    e("lose-your-marbles","Lose your marbles","To go crazy or become irrational","American slang","He completely lost his marbles when they told him the price.","informal",["crazy","sanity","anger"],"us"),
    e("make-a-mountain-out-of-a-molehill","Make a mountain out of a molehill","To exaggerate a minor problem","American English","It's just a small scratch — don't make a mountain out of a molehill.","standard",["exaggeration","perspective","problems"],"us"),
    e("money-talks","Money talks","Wealth gives power and influence","American saying","In politics, money talks more than principles.","standard",["money","power","influence"],"us"),
    e("no-strings-attached","No strings attached","With no conditions or obligations","American English","The loan comes with no strings attached.","standard",["freedom","conditions","contracts"],"us"),
    e("not-batting-an-eye","Not batting an eye","Showing no reaction or emotion","American English","She announced the merger without batting an eye.","standard",["calm","reaction","indifference"],"us"),
    e("off-the-bat","Right off the bat","Immediately, without delay","From baseball; American expression","I knew right off the bat that something was wrong.","informal",["immediate","instinct","beginning"],"us"),
    e("off-the-charts","Off the charts","Exceptionally high or beyond all expectations","American English","The response to the product launch was off the charts.","informal",["exceptional","extreme","success"],"us"),
    e("on-a-roll","On a roll","Experiencing a period of continued success","American English","She's on a roll — three wins in a row.","informal",["success","momentum","luck"],"us"),
    e("on-borrowed-time","On borrowed time","Living or existing beyond the expected end","American English","With the contract expiring, the program is on borrowed time.","standard",["time","expiry","uncertainty"],"us"),
    e("on-cloud-nine","On cloud nine","Extremely happy","American expression","He's been on cloud nine since getting engaged.","informal",["happiness","joy","excitement"],"us"),
    e("on-the-fritz","On the fritz","Not working properly","American slang","My laptop is on the fritz again.","informal",["malfunction","broken","technology"],"us"),
    e("on-the-house","On the house","Free of charge, paid for by the establishment","American English","The dessert is on the house — to celebrate your anniversary.","informal",["free","generosity","hospitality"],"us"),
    e("open-a-can-of-worms","Open a can of worms","To create a complicated new set of problems","American expression","Bringing up the old contract would open a can of worms.","informal",["problems","complications","consequences"],"us"),
    e("out-of-left-field","Out of left field","Completely unexpected","From baseball; American expression","Her resignation came completely out of left field.","informal",["unexpected","surprise","unusual"],"us"),
    e("over-a-barrel","Over a barrel","In a powerless position, forced to accept terms","American expression","With no other suppliers, they had us over a barrel.","informal",["helpless","power","negotiation"],"us"),
    e("pain-in-the-neck","Pain in the neck","Someone or something very annoying","American euphemism","That client is a real pain in the neck.","informal",["annoying","difficult","frustration"],"us"),
    e("play-hardball","Play hardball","To act aggressively to achieve a goal","From baseball; American expression","The lawyers are playing hardball in the negotiations.","standard",["aggression","competition","negotiation"],"us"),
    e("pull-the-plug","Pull the plug","To end or cancel something","American expression, from life support","They pulled the plug on the project due to budget issues.","standard",["ending","canceling","decision"],"us"),
    e("put-your-foot-in-your-mouth","Put your foot in your mouth","To say something embarrassing or tactless","American English","He put his foot in his mouth asking her when the baby was due.","informal",["embarrassment","mistake","speech"],"us"),
    e("put-your-money-where-your-mouth-is","Put your money where your mouth is","To back up your words with real action or money","American expression","If you believe in the company, put your money where your mouth is and invest.","standard",["action","commitment","integrity"],"us"),
    e("raise-the-bar","Raise the bar","To set a higher standard of expectation","American English","That performance really raised the bar for the entire team.","standard",["standards","excellence","improvement"],"us"),
    e("rock-the-boat","Rock the boat","To cause trouble by disrupting the status quo","American English","He never rocks the boat — always goes along with the group.","informal",["disruption","conformity","trouble"],"us"),
    e("rule-of-thumb","Rule of thumb","A practical general principle or guideline","American English (also British)","As a rule of thumb, drink eight glasses of water a day.","standard",["principle","estimate","guideline"],"us"),
    e("scratch-the-surface","Scratch the surface","To deal with only the most superficial part of something","American English","This report barely scratches the surface of the problem.","standard",["superficial","depth","beginning"],"us"),
    e("shape-up-or-ship-out","Shape up or ship out","Improve your behavior or leave","American military expression","The manager gave him an ultimatum: shape up or ship out.","informal",["ultimatum","improvement","dismissal"],"us"),
    e("show-someone-the-ropes","Show someone the ropes","To teach someone how things work","Nautical origin; widely used in the US","Her mentor showed her the ropes in the first few weeks.","standard",["teaching","guidance","experience"],"us"),
    e("sink-or-swim","Sink or swim","Either succeed by your own efforts or fail","American expression","Starting a business is sink or swim.","standard",["survival","effort","independence"],"us"),
    e("sitting-duck","A sitting duck","An easy target with no protection","American English","Without legal support, the startup is a sitting duck.","standard",["vulnerable","target","risk"],"us"),
    e("sleep-on-it","Sleep on it","To delay a decision until the next day","American English","Don't make any big decisions tonight — sleep on it.","standard",["decision","time","thinking"],"us"),
    e("slip-through-the-cracks","Slip through the cracks","To be missed or overlooked by a system","American English","Some students slip through the cracks in the education system.","standard",["oversight","system","missed"],"us"),
    e("something-smells-fishy","Something smells fishy","Something seems suspicious","American expression","Something smells fishy about that deal.","informal",["suspicion","dishonesty","doubt"],"us"),
    e("stab-someone-in-the-back","Stab someone in the back","To betray someone's trust","American English","He stabbed his best friend in the back by going to the boss.","informal",["betrayal","trust","friendship"],"us"),
    e("strike-while-the-iron-is-hot","Strike while the iron is hot","Take advantage of an opportunity at the right moment","From blacksmithing; widely used in American English","She got a job offer and struck while the iron was hot.","standard",["opportunity","timing","action"],"us"),
    e("sweep-under-the-rug","Sweep under the rug","To hide or ignore a problem","American expression","The scandal was quietly swept under the rug.","standard",["hiding","denial","dishonesty"],"us"),
    e("take-a-back-seat","Take a back seat","To take a less important or active role","American expression","Since the merger, innovation has taken a back seat.","standard",["priority","role","importance"],"us"),
    e("take-a-stand","Take a stand","To firmly express or defend a position","American English","It's time to take a stand against discrimination.","standard",["conviction","courage","action"],"us"),
    e("take-it-easy","Take it easy","To relax; to not overwork yourself","American English","You've been working non-stop — take it easy this weekend.","informal",["relaxation","rest","stress"],"us"),
    e("take-someone-under-your-wing","Take someone under your wing","To guide and protect someone less experienced","American English","The senior developer took the intern under his wing.","standard",["mentorship","guidance","care"],"us"),
    e("take-the-cake","Take the cake","To be the most extreme or remarkable example of something","American English","Of all her excuses, this one really takes the cake.","informal",["extreme","remarkable","humor"],"us"),
    e("talk-turkey","Talk turkey","To speak seriously and directly about business","American expression","Let's talk turkey — what's your best and final offer?","informal",["negotiation","directness","business"],"us"),
    e("that-ship-has-sailed","That ship has sailed","That opportunity has already passed","American English","If you wanted to apply for that role, that ship has sailed.","informal",["missed-opportunity","time","regret"],"us"),
    e("the-jury-is-still-out","The jury is still out","The matter has not yet been decided","American legal expression","The jury is still out on whether remote work increases productivity.","standard",["uncertainty","decision","opinion"],"us"),
    e("the-whole-enchilada","The whole enchilada","The complete thing, everything","American slang, from Mexican cuisine","When we renovate, we're doing the whole enchilada.","informal",["completeness","everything","totality"],"us"),
    e("tie-the-knot","Tie the knot","To get married","American English","After five years together, they finally tied the knot.","informal",["marriage","love","commitment"],"us"),
    e("turn-a-blind-eye","Turn a blind eye","To pretend not to notice something wrong","From Admiral Nelson; widely used in American English","The manager turned a blind eye to the policy violations.","standard",["ignorance","avoidance","dishonesty"],"us"),
    e("under-the-table","Under the table","Done secretly and usually illegally","American English","They paid the workers under the table to avoid taxes.","informal",["illegal","secret","money"],"us"),
    e("up-in-arms","Up in arms","Very angry and ready to protest","American English","The community is up in arms about the new highway plan.","standard",["anger","protest","opposition"],"us"),
    e("a-blessing-in-disguise","A blessing in disguise","Something that seems bad but turns out to be good","American English","Getting fired turned out to be a blessing in disguise.","standard",["luck","perspective","change"],"us"),
    e("all-bark-and-no-bite","All bark and no bite","Someone who threatens but never acts on it","American English","Don't worry about him — he's all bark and no bite.","informal",["threats","personality","bluff"],"us"),
    e("at-the-end-of-the-day","At the end of the day","When everything is considered; ultimately","American English","At the end of the day, it's the results that matter.","standard",["conclusion","ultimately","perspective"],"us"),
    e("back-to-square-one","Back to square one","Starting over from the very beginning","American English, from boardgames","The proposal was rejected — we're back to square one.","informal",["restart","failure","beginning"],"us"),
    e("ballpark-figure","Ballpark figure","A rough estimate","From baseball; American expression","Give me a ballpark figure for the renovation costs.","standard",["estimate","approximation","business"],"us"),
    e("bent-out-of-shape","Bent out of shape","Very upset or offended about something","American slang","He got all bent out of shape over a minor comment.","informal",["anger","sensitivity","overreaction"],"us"),
    e("between-a-rock-and-a-hard-place","Between a rock and a hard place","In a situation where all choices are difficult","American expression","I'm between a rock and a hard place — I can't afford it but I can't stay either.","standard",["dilemma","difficult-choice","problems"],"us"),
    e("burn-the-midnight-oil","Burn the midnight oil","To work very late into the night","From oil lamps; widely used in American English","She burned the midnight oil to finish the report on time.","standard",["work","dedication","late-night"],"us"),
    e("every-trick-in-the-book","Every trick in the book","Using all possible methods","American English","She tried every trick in the book to land the deal.","informal",["effort","methods","determination"],"us"),
    e("fall-off-the-wagon","Fall off the wagon","To return to a bad habit after a period of abstinence","American English","He was sober for a year but fell off the wagon at the holidays.","informal",["addiction","relapse","habits"],"us"),
    e("get-your-act-together","Get your act together","To become organized and responsible","American English","You need to get your act together if you want to keep this job.","informal",["organization","responsibility","improvement"],"us"),
    e("go-the-extra-mile","Go the extra mile","To put in more effort than required","American expression","She always goes the extra mile for her clients.","standard",["effort","dedication","service"],"us"),
    e("hit-the-jackpot","Hit the jackpot","To achieve sudden, great success or win something big","American English, gambling origin","They hit the jackpot with that real estate investment.","informal",["luck","success","win"],"us"),
    e("if-it-aint-broke","If it ain't broke, don't fix it","Don't change something that works fine","American saying","I know you want to redesign the app, but if it ain't broke, don't fix it.","informal",["change","pragmatism","caution"],"us"),
    e("in-the-ballpark","In the ballpark","Approximately correct, within an acceptable range","From baseball; American expression","Your estimate is in the ballpark — let me check the numbers.","standard",["estimate","approximation","accuracy"],"us"),
    e("keep-it-under-wraps","Keep it under wraps","To keep something secret","American English","The new product launch needs to be kept under wraps until next month.","standard",["secret","confidentiality","information"],"us"),
    e("keep-the-ball-rolling","Keep the ball rolling","To maintain momentum and progress","American expression","Great start — now let's keep the ball rolling.","standard",["momentum","progress","action"],"us"),
    e("make-or-break","Make or break","A critical factor determining success or failure","American English","This presentation is make or break for the company.","standard",["critical","decision","success"],"us"),
    e("off-the-top-of-my-head","Off the top of my head","Without careful thought, from immediate memory","American English","Off the top of my head, I'd say we need about fifty thousand dollars.","informal",["memory","estimate","immediate"],"us"),
    e("pick-up-the-slack","Pick up the slack","To do work that someone else is not doing","American English","With two team members sick, the rest of us had to pick up the slack.","standard",["work","responsibility","teamwork"],"us"),
    e("run-circles-around","Run circles around someone","To be much faster or more skilled than someone","American expression","She can run circles around any other programmer on the team.","informal",["skill","superiority","comparison"],"us"),
    e("see-eye-to-eye","See eye to eye","To agree with someone completely","American English","They never see eye to eye on budget decisions.","standard",["agreement","disagreement","communication"],"us"),
    e("set-the-record-straight","Set the record straight","To correct a misunderstanding or false rumor","American English","I need to set the record straight: that was not my idea.","standard",["truth","correction","clarification"],"us"),
    e("shoot-yourself-in-the-foot","Shoot yourself in the foot","To accidentally harm your own interests","American expression","He shot himself in the foot by arguing with the interviewer.","informal",["mistake","self-harm","error"],"us"),
    e("speak-of-the-devil","Speak of the devil","Said when someone appears just after being discussed","American English (British origin)","Speak of the devil — we were just talking about you!","informal",["coincidence","surprise","conversation"],"us"),
    e("straight-from-the-horses-mouth","Straight from the horse's mouth","Directly from the original and most reliable source","American expression, from horse racing","I heard it straight from the horse's mouth — the merger is happening.","standard",["information","source","reliability"],"us"),
    e("take-the-bull-by-the-horns","Take the bull by the horns","To face a difficult situation directly and boldly","American expression, from rodeo culture","Instead of avoiding the issue, she took the bull by the horns.","standard",["courage","action","directness"],"us"),
    e("under-someones-nose","Under someone's nose","Right in front of someone without them noticing","American English","The theft happened right under the security guard's nose.","informal",["obvious","unnoticed","deception"],"us"),
    e("wrap-your-head-around","Wrap your head around something","To fully understand something complex","American English","It took me a while to wrap my head around quantum physics.","informal",["understanding","complexity","thinking"],"us"),
    e("you-scratch-my-back","You scratch my back, I'll scratch yours","I'll help you if you help me","American expression","In politics, it's always you scratch my back, I'll scratch yours.","informal",["reciprocity","favors","relationships"],"us"),
    e("zip-your-lips","Zip your lips","To be quiet; stop talking","American slang","Zip your lips — the baby is sleeping.","informal",["silence","quiet","instruction"],"us"),
    e("double-edged-sword","A double-edged sword","Something with both advantages and disadvantages","American English (also widely used)","Social media is a double-edged sword for businesses.","standard",["consequences","pros-and-cons","duality"],"us"),
    e("for-the-birds","For the birds","Not worth considering; pointless","American slang","This plan is for the birds — it will never work.","informal",["worthless","dismissal","criticism"],"us"),
    e("have-a-field-day","Have a field day","To enjoy great freedom or success in doing something","American English","The press had a field day with the politician's gaffe.","informal",["enjoyment","freedom","opportunity"],"us"),
    e("let-sleeping-dogs-lie","Let sleeping dogs lie","Don't disturb a situation that is causing no problems","American English (also British)","Don't bring up old arguments — let sleeping dogs lie.","standard",["peace","avoidance","wisdom"],"us"),
    e("night-owl","Night owl","A person who prefers staying up late","American English","She's a night owl — she does her best work after midnight.","informal",["sleep","habits","personality"],"us"),
    e("put-your-foot-down","Put your foot down","To firmly insist on something","American English","She finally put her foot down and demanded a salary raise.","informal",["determination","authority","insistence"],"us"),
    e("rain-on-someones-parade","Rain on someone's parade","To spoil someone's plans or happiness","American English","I hate to rain on your parade, but the venue is already booked.","informal",["disappointment","spoil","negativity"],"us"),
    e("running-on-empty","Running on empty","Operating with almost no energy or resources left","American English; also a famous Eagles song","I've been running on empty for weeks — I need a vacation.","informal",["exhaustion","energy","resources"],"us"),
    e("run-the-show","Run the show","To be in charge of an entire operation","American English","Since the director retired, she's been running the show.","standard",["authority","leadership","control"],"us"),
    e("sell-like-hotcakes","Sell like hotcakes","To sell very quickly and in large quantities","American expression, from griddle cakes at fairs","Their new sneakers are selling like hotcakes.","informal",["sales","popularity","success"],"us"),
    e("set-in-stone","Set in stone","Fixed and unable to be changed","American English","The schedule isn't set in stone — we can be flexible.","standard",["fixed","rigid","change"],"us"),
    e("step-on-someones-toes","Step on someone's toes","To offend someone by encroaching on their territory","American English","Be careful not to step on the marketing team's toes.","standard",["offense","boundaries","workplace"],"us"),
    e("the-real-mccoy","The real McCoy","The genuine article; the real thing","American expression, origin debated","This isn't a copy — it's the real McCoy.","informal",["authentic","genuine","quality"],"us"),
    e("think-on-your-feet","Think on your feet","To think quickly and react to unexpected situations","American English","In customer service, you need to be able to think on your feet.","standard",["quick-thinking","adaptability","intelligence"],"us"),
    e("toot-your-own-horn","Toot your own horn","To boast about your own achievements","American English","Don't be afraid to toot your own horn in a job interview.","informal",["confidence","boasting","self-promotion"],"us"),
    e("turn-the-tables","Turn the tables","To reverse a situation completely","American English","She turned the tables on her critics by winning the championship.","standard",["reversal","advantage","change"],"us"),
    e("walk-the-walk","Walk the walk","To actually do what you claim you can do","American expression","He talks the talk, but can he walk the walk?","standard",["credibility","actions","integrity"],"us"),
    e("what-goes-around-comes-around","What goes around comes around","Your actions will eventually have consequences for you","American saying","He treated everyone badly and now has no friends. What goes around comes around.","standard",["karma","consequences","justice"],"us"),
    e("wet-behind-the-ears","Wet behind the ears","Young and inexperienced","American English","The new interns are wet behind the ears but eager to learn.","informal",["inexperience","youth","learning"],"us"),
    e("window-of-opportunity","Window of opportunity","A limited time during which action can be taken","American English","We have a small window of opportunity before the competition gets there.","standard",["opportunity","time","action"],"us"),
    e("wolf-in-sheeps-clothing","A wolf in sheep's clothing","Someone who appears harmless but is actually dangerous","American English, biblical origin","That charming investor is a wolf in sheep's clothing.","standard",["deception","danger","appearance"],"us"),
    e("word-of-mouth","Word of mouth","Information passed informally from person to person","American English","The restaurant built its reputation entirely through word of mouth.","standard",["communication","marketing","information"],"us"),
    e("work-your-fingers-to-the-bone","Work your fingers to the bone","To work extremely hard","American expression","She worked her fingers to the bone to put her kids through college.","informal",["hardwork","effort","dedication"],"us"),
    e("you-reap-what-you-sow","You reap what you sow","Your actions have consequences that come back to you","American English, biblical origin","He treated people terribly and now has nothing. You reap what you sow.","standard",["consequences","karma","actions"],"us"),
    e("above-and-beyond","Above and beyond","More than what is required or expected","American English","He always goes above and beyond in his role.","standard",["effort","dedication","performance"],"us"),
    e("pie-in-the-sky","Pie in the sky","An unrealistic or overly idealistic hope","American expression, from labor movement song","His plan to retire at 30 is just pie in the sky.","informal",["dreams","unrealistic","hope"],"us"),
    e("play-devils-advocate","Play devil's advocate","To argue the opposite side to explore an issue","American English","Let me play devil's advocate — what if the plan fails?","standard",["argument","debate","perspective"],"us"),
    e("push-the-envelope","Push the envelope","To go beyond conventional limits","American aviation term","This new technology really pushes the envelope.","standard",["innovation","limits","progress"],"us"),
    e("reinvent-the-wheel","Reinvent the wheel","To waste time creating something that already exists","American expression","Don't reinvent the wheel — use the existing template.","standard",["efficiency","waste","innovation"],"us"),
    e("right-up-your-alley","Right up your alley","Perfectly suited to your skills or interests","American expression","This project is right up your alley — it's all about data analysis.","informal",["suitability","skills","interests"],"us"),
    e("rub-someone-the-wrong-way","Rub someone the wrong way","To irritate or annoy someone","American English","His dismissive attitude really rubs me the wrong way.","informal",["irritation","personality","social"],"us"),
    e("run-out-of-steam","Run out of steam","To lose energy, motivation, or momentum","American expression","The project started strong but ran out of steam by Q3.","informal",["energy","motivation","exhaustion"],"us"),
    e("pass-with-flying-colors","Pass with flying colors","To succeed very well or excel at something","American English, nautical origin","She passed the bar exam with flying colors.","standard",["success","excellence","achievement"],"us"),
    e("that-s-the-way-the-cookie-crumbles","That's the way the cookie crumbles","That's just how life is — accept it","American expression","I didn't get the job. That's the way the cookie crumbles.","informal",["acceptance","fate","life"],"us"),
    e("up-the-ante","Up the ante","To increase the stakes or level of commitment","American English, from poker","Management upped the ante by threatening to close the plant.","standard",["stakes","pressure","escalation"],"us"),
    e("water-under-the-bridge","Water under the bridge","Past events no longer worth worrying about","American English (also British)","We had our differences, but that's all water under the bridge now.","standard",["past","forgiveness","moving-on"],"us"),
    e("wear-your-heart-on-your-sleeve","Wear your heart on your sleeve","To openly display your emotions","From Shakespeare; widely used in American English","She wears her heart on her sleeve — you always know how she feels.","standard",["emotions","honesty","personality"],"us"),
    e("zero-in-on","Zero in on","To focus closely on a specific target","American English, from rifle sighting","The investigation is zeroing in on the key suspect.","standard",["focus","targeting","investigation"],"us"),
    e("on-the-mend","On the mend","Recovering from illness or a setback","American English (also British)","She was very sick last week, but she's on the mend now.","standard",["recovery","health","improvement"],"us"),
    e("open-and-shut","Open and shut","Simple and obvious, requiring no debate","American English, legal term","It's an open and shut case — the evidence is overwhelming.","standard",["clarity","simplicity","obvious"],"us"),
    e("put-on-ice","Put on ice","To postpone or delay indefinitely","American expression","The expansion plans have been put on ice until conditions improve.","standard",["postpone","delay","planning"],"us"),
    e("riding-high","Riding high","Experiencing great success and confidence","American English","The company is riding high after its record quarterly earnings.","informal",["success","confidence","prosperity"],"us"),
    e("spin-your-wheels","Spin your wheels","To put in effort without making any progress","American expression","We've been spinning our wheels on this issue for months.","informal",["effort","futility","progress"],"us"),
    e("string-someone-along","String someone along","To keep someone in an uncertain or hopeful state","American English","He strung her along for months without any real commitment.","informal",["deception","relationship","hope"],"us"),
    e("toot-your-horn","Toot your horn","To brag or promote yourself","American English","In a competitive market, you have to toot your own horn.","informal",["confidence","self-promotion","boasting"],"us"),
    e("turn-over-a-new-leaf","Turn over a new leaf","To change your behavior for the better","American English","After his health scare, he turned over a new leaf.","standard",["change","improvement","fresh-start"],"us"),
    e("under-the-weather","Under the weather","Feeling slightly ill","American English (also British)","I'm feeling a bit under the weather today.","standard",["sick","health","feeling"],"us"),
    e("straight-from-the-shoulder","Straight from the shoulder","Speaking honestly and directly","American English, from boxing","He told them straight from the shoulder that the project was doomed.","standard",["honesty","directness","communication"],"us"),
    e("bite-the-hand-that-feeds","Bite the hand that feeds you","To act against someone who helps or supports you","American English (also British)","Criticizing your biggest sponsor is biting the hand that feeds you.","standard",["betrayal","ingratitude","support"],"us"),
    e("cut-corners","Cut corners","To do something poorly to save time or money","American English","They cut corners on safety to finish the project on time.","informal",["shortcuts","quality","cost"],"us"),
    e("step-up-to-the-mark","Step up to the mark","To perform as well as expected","American English","It's a big challenge, but I know you'll step up to the mark.","standard",["performance","expectations","challenge"],"us"),
    e("back-to-basics","Back to basics","Return to fundamental principles","American English","When things go wrong, it's best to go back to basics.","standard",["principles","simplicity","fundamentals"],"us"),
    e("come-clean","Come clean","To tell the truth about something you've been hiding","American English","He finally came clean about what really happened.","standard",["honesty","confession","truth"],"us"),
    e("get-to-the-bottom-of","Get to the bottom of","To find the real cause of a problem","American English","The investigator was determined to get to the bottom of the scandal.","standard",["investigation","truth","cause"],"us"),
    e("in-over-your-head","In over your head","Involved in something beyond your abilities","American English","He took on too many projects and is in over his head.","standard",["difficulty","overwhelmed","ability"],"us"),
    e("look-before-you-leap","Look before you leap","Think carefully before taking action","American English (also British proverb)","Don't rush into the investment — look before you leap.","standard",["caution","decision","wisdom"],"us"),
    e("miss-by-a-mile","Miss by a mile","To be very far from the correct answer or target","American expression","His estimate missed by a mile — it was three times the actual cost.","informal",["error","distance","wrong"],"us"),
    e("on-the-wagon","On the wagon","Abstaining from alcohol","American expression","He's been on the wagon for six months now.","standard",["sobriety","alcohol","habits"],"us"),
    e("pick-up-steam","Pick up steam","To gradually gain speed, momentum, or strength","American English","The campaign slowly picked up steam across social media.","standard",["momentum","progress","growth"],"us"),
    e("shoot-from-the-hip","Shoot from the hip","To react quickly and directly without much thought","American Western expression","She shoots from the hip in meetings — brutal but honest.","informal",["directness","impulsive","honesty"],"us"),
    e("smooth-sailing","Smooth sailing","Easy progress without obstacles","American expression","After the initial setup, it was smooth sailing.","informal",["ease","progress","success"],"us"),
    e("take-it-or-leave-it","Take it or leave it","Accept what's offered or refuse — no negotiation","American expression","The price is five hundred dollars — take it or leave it.","standard",["negotiation","decision","offer"],"us"),
    e("the-buck-stops-here","The buck stops here","I take full responsibility — no passing blame","American expression; on President Truman's desk","As team leader, the buck stops here.","standard",["responsibility","leadership","accountability"],"us"),
    e("there-s-no-such-thing-as-a-free-lunch","There's no such thing as a free lunch","Nothing is ever truly free — everything has a cost","American economic saying","Read the fine print before accepting — there's no such thing as a free lunch.","standard",["economics","cost","wisdom"],"us"),
    e("throw-a-curveball","Throw a curveball","To present an unexpected challenge","From baseball; American expression","The new regulation really threw us a curveball.","informal",["unexpected","challenge","surprise"],"us"),
    e("too-big-for-your-boots","Too big for your boots","Arrogant and overconfident about your own importance","American English (also British)","Since getting promoted, he's become too big for his boots.","informal",["arrogance","pride","attitude"],"us"),
    e("up-and-running","Up and running","Functioning and operational","American English","The new system will be up and running by Monday.","standard",["operational","working","technology"],"us"),
    e("work-the-graveyard-shift","Work the graveyard shift","To work during the night, typically midnight to morning","American English","He works the graveyard shift at the hospital every weekend.","informal",["work","night","schedule"],"us"),

    # ── UK ──────────────────────────────────────────────────────────────
    e("bobs-your-uncle","Bob's your uncle","And there it is — it's as simple as that","British expression possibly from 1880s political nepotism","Just add the flour, stir for two minutes, and Bob's your uncle — perfect gravy!","informal",["British","simplicity","completion"],"uk"),
    e("chuffed-to-bits","Chuffed to bits","Very pleased or proud","British slang","She was absolutely chuffed to bits when she got the promotion.","informal",["happiness","pride","pleasure","British"],"uk"),
    e("go-pear-shaped","Go pear-shaped","To go wrong or fail","British slang","The plan went completely pear-shaped when the supplier dropped out.","informal",["failure","problems","British"],"uk"),
    e("not-my-cup-of-tea","Not my cup of tea","Not something I enjoy or prefer","British expression","Horror films are really not my cup of tea.","informal",["preference","dislike","British"],"uk"),
    e("lose-the-plot","Lose the plot","To become irrational, confused, or out of control","British slang","He completely lost the plot when they told him the news.","informal",["confusion","crazy","British"],"uk"),
    e("take-the-mickey","Take the mickey","To mock or tease someone","British slang","Are you taking the mickey? That price is absolutely outrageous!","informal",["teasing","humor","British"],"uk"),
    e("spanner-in-the-works","A spanner in the works","Something that disrupts or sabotages a plan","British expression","The last-minute cancellation was a real spanner in the works.","standard",["disruption","problems","planning","British"],"uk"),
    e("storm-in-a-teacup","A storm in a teacup","A lot of fuss about something minor","British expression","The whole argument was just a storm in a teacup.","informal",["overreaction","minor","fuss","British"],"uk"),
    e("the-penny-has-dropped","The penny has dropped","The person has finally understood something","British expression, from slot machines","I could see the penny drop when she finally got the joke.","informal",["understanding","realization","British"],"uk"),
    e("tickled-pink","Tickled pink","Very pleased or amused","British expression","She was absolutely tickled pink by the surprise party.","informal",["happiness","pleasure","British"],"uk"),
    e("all-mouth-and-no-trousers","All mouth and no trousers","All talk and no action","British expression","He promised so much, but he's all mouth and no trousers.","informal",["boasting","empty-promises","British"],"uk"),
    e("gobsmacked","Gobsmacked","Utterly astonished","British slang","I was absolutely gobsmacked when I heard the news.","informal",["surprise","shock","British"],"uk"),
    e("done-and-dusted","Done and dusted","Completely finished","British expression","Once we sign the contract, it's done and dusted.","informal",["completion","finality","British"],"uk"),
    e("its-not-cricket","It's not cricket","It's not fair or sportsmanlike","British expression, from cricket","Spreading rumors about a colleague — it's just not cricket.","standard",["fairness","ethics","British","sport"],"uk"),
    e("over-the-moon","Over the moon","Extremely happy","British expression","She was over the moon when she found out she was pregnant.","informal",["happiness","joy","excitement","British"],"uk"),
    e("by-hook-or-by-crook","By hook or by crook","By any means necessary","British expression, medieval origin","We'll get this project finished by hook or by crook.","informal",["determination","methods","commitment","British"],"uk"),
    e("horses-for-courses","Horses for courses","Different approaches suit different people or situations","British expression from horse racing","Some people need strict deadlines, others need freedom — horses for courses.","standard",["suitability","individual","approach","British"],"uk"),
    e("mind-your-ps-and-qs","Mind your Ps and Qs","Be careful about your behavior and manners","British expression","Mind your Ps and Qs at the formal dinner tonight.","standard",["manners","behavior","propriety","British"],"uk"),
    e("a-dab-hand","A dab hand","An expert at something","British expression","She's a dab hand at fixing old furniture.","informal",["skill","expertise","British"],"uk"),
    e("on-the-blink","On the blink","Not working properly","British expression","The heating is on the blink again.","informal",["malfunction","broken","British"],"uk"),
    e("pigs-might-fly","Pigs might fly","Something that will never happen","British expression","He'll apologize when pigs might fly.","informal",["impossibility","sarcasm","British"],"uk"),
    e("up-the-creek","Up the creek without a paddle","In serious trouble with no means of escape","British expression","Without insurance, you'd really be up the creek without a paddle.","informal",["trouble","helpless","British"],"uk"),
    e("touch-wood","Touch wood","Said while knocking on wood to avoid bad luck","British expression (American equivalent: 'knock on wood')","I haven't had a cold all winter — touch wood!","informal",["superstition","luck","British"],"uk"),
    e("mums-the-word","Mum's the word","Keep it secret, don't say anything","British expression","Don't tell anyone about the surprise party — mum's the word.","informal",["secrecy","silence","British"],"uk"),
    e("sick-as-a-parrot","Sick as a parrot","Very disappointed","British expression, particularly in football commentary","He was sick as a parrot when his team lost the cup final.","informal",["disappointment","British","sports"],"uk"),
    e("pull-a-fast-one","Pull a fast one","To trick or deceive someone","British expression","He pulled a fast one by claiming the expenses twice.","informal",["deception","tricks","British"],"uk"),
    e("take-the-biscuit","Take the biscuit","To be the most surprising or audacious example","British expression","Asking for a pay rise after one week? That really takes the biscuit.","informal",["extreme","audacity","British"],"uk"),
    e("gutted","Gutted","Very disappointed","British slang","I was absolutely gutted when my team was eliminated.","informal",["disappointment","British","sports"],"uk"),
    e("on-a-sticky-wicket","On a sticky wicket","In a difficult or tricky situation","British expression from cricket","The company is on a sticky wicket with that contract clause.","standard",["difficulty","British","cricket"],"uk"),
    e("knackered","Knackered","Extremely tired or exhausted","British slang","I'm completely knackered after that long flight.","informal",["tiredness","exhaustion","British"],"uk"),
    e("through-thick-and-thin","Through thick and thin","In both good and bad times, through everything","British expression","They've been close friends through thick and thin.","standard",["loyalty","friendship","commitment"],"uk"),
    e("once-bitten-twice-shy","Once bitten, twice shy","Having been hurt once, you are more cautious in future","British proverb","After that failed investment, she's once bitten, twice shy about startups.","standard",["caution","experience","learning"],"uk"),
    e("have-a-butchers","Have a butcher's","Have a look (Cockney rhyming slang: butcher's hook = look)","British Cockney rhyming slang","Let me have a butcher's at that document.","informal",["Cockney","British","look"],"uk"),
    e("on-your-bike","On your bike","Go away; clear off","British informal","If you don't like it, on your bike!","informal",["dismissal","British","rude"],"uk"),
    e("swings-and-roundabouts","Swings and roundabouts","What you gain in one way you lose in another","British expression","Working from home saves on commuting, but it's swings and roundabouts with heating bills.","standard",["balance","tradeoffs","British"],"uk"),
    e("make-a-pigs-ear","Make a pig's ear of something","To do something badly or bungle it","British expression","He made a complete pig's ear of the presentation.","informal",["failure","mistake","British"],"uk"),
    e("give-someone-a-bell","Give someone a bell","To call someone on the telephone","British slang","Give me a bell when you arrive and I'll come out.","informal",["telephone","British","communication"],"uk"),
    e("have-a-lie-in","Have a lie-in","To stay in bed later than usual in the morning","British expression","I love having a lie-in on Sunday mornings.","informal",["sleep","relaxation","British"],"uk"),
    e("bits-and-bobs","Bits and bobs","Various small, miscellaneous things","British expression","I just need to pick up a few bits and bobs from the shops.","informal",["miscellaneous","British","things"],"uk"),
    e("faff-about","Faff about","To spend time in a disorganized, ineffective way","British expression","Stop faffing about and get the job done.","informal",["disorganization","wasting-time","British"],"uk"),
    e("the-bees-knees","The bee's knees","The very best","British expression (also used in US)","This ice cream is absolutely the bee's knees.","informal",["excellence","best","quality","British"],"uk"),
    e("belt-and-braces","Belt and braces","Taking double precautions to be safe","British expression","We installed both a smoke alarm and a sprinkler — belt and braces approach.","standard",["caution","safety","British"],"uk"),
    e("in-two-shakes","In two shakes of a lamb's tail","Very quickly","British expression","I'll be with you in two shakes of a lamb's tail.","informal",["speed","British","quick"],"uk"),
    e("let-the-side-down","Let the side down","To disappoint or fail your group or team","British expression","Don't let the side down — we're all counting on you.","standard",["disappointment","team","British"],"uk"),
    e("have-a-chinwag","Have a chinwag","Have a chat, a long conversation","British slang","Let's have a chinwag over coffee sometime.","informal",["conversation","British","social"],"uk"),
    e("on-the-cards","On the cards","Likely to happen","British expression","A merger has been on the cards for months now.","standard",["probability","prediction","British"],"uk"),
    e("full-of-beans","Full of beans","Very lively, energetic, and enthusiastic","British expression","The kids are absolutely full of beans this morning.","informal",["energy","lively","British"],"uk"),
    e("over-egg-the-pudding","Over-egg the pudding","To exaggerate something unnecessarily","British expression","He's over-egging the pudding with those statistics.","informal",["exaggeration","British","excess"],"uk"),
    e("brass-tacks","Get down to brass tacks","To get to the essential facts or matters","British expression (also used in American English)","Let's get down to brass tacks — what are the actual costs?","standard",["directness","essentials","business"],"uk"),
    e("keep-mum","Keep mum","To remain silent about something","British expression","Keep mum about the party plans until Saturday.","informal",["secrecy","silence","British"],"uk"),
    e("in-the-nick-of-time","In the nick of time","Just in time, before something bad happens","British expression","The paramedics arrived in the nick of time.","standard",["timing","rescue","urgent"],"uk"),
    e("live-and-let-live","Live and let live","Don't interfere with how others choose to live","British expression","She doesn't judge anyone — live and let live is her motto.","standard",["tolerance","freedom","attitude"],"uk"),
    e("a-fortnight","A fortnight","A period of two weeks","British English","We're going on holiday for a fortnight.","standard",["time","British","two-weeks"],"uk"),
    e("cheeky-monkey","Cheeky monkey","A playful way to describe a mischievous person","British expression","You cheeky monkey! You ate all my chips!","informal",["playful","mischief","children","British"],"uk"),
    e("wonky","Wonky","Not working properly; not straight","British informal","The table leg is a bit wonky.","informal",["broken","imperfect","British"],"uk"),
    e("fancy","Fancy","To want or desire something; to find someone attractive","British informal","Do you fancy a cup of tea?","informal",["desire","want","British"],"uk"),
    e("bits-n-pieces","Bits and pieces","Various small miscellaneous items","British expression","There are some bits and pieces left over from the project.","informal",["miscellaneous","British","various"],"uk"),
    e("in-a-jiffy","In a jiffy","Very quickly, in a very short time","British informal","I'll be with you in a jiffy.","informal",["speed","quick","British"],"uk"),
    e("under-the-cosh","Under the cosh","Under intense pressure or difficulty","British expression","The team has been under the cosh since the manager left.","informal",["pressure","difficulty","British"],"uk"),
    e("couldn-t-organise-a-piss-up","Couldn't organise a piss-up in a brewery","Completely incompetent at organising anything","British vulgar expression","That committee couldn't organise a piss-up in a brewery.","vulgar",["incompetence","British","humor"],"uk"),
    e("the-dogs-dinner","A dog's dinner","A mess; something done very badly","British expression","He made a dog's dinner of the whole arrangement.","informal",["mess","British","failure"],"uk"),
    e("it-ll-all-come-out-in-the-wash","It'll all come out in the wash","Everything will sort itself out eventually","British expression","Don't worry about it now — it'll all come out in the wash.","informal",["patience","reassurance","British"],"uk"),
    e("pip-pip","Pip-pip","Goodbye (old-fashioned)","British old-fashioned expression","Right, I'm off — pip-pip!","informal",["goodbye","British","old-fashioned"],"uk"),

    # ── AU ──────────────────────────────────────────────────────────────
    e("shes-apples","She's apples","Everything is fine, no worries","Australian expression, rhyming slang: apples and spice = nice","Don't stress about it — she's apples.","informal",["Australian","fine","reassurance"],"au"),
    e("fair-dinkum","Fair dinkum","True, genuine, or authentic","Australian expression, possibly from English dialect","Is that fair dinkum? He actually won the whole thing?","informal",["Australian","genuine","truth"],"au"),
    e("no-worries","No worries","No problem; it's all fine","Australian expression","Thanks for your help!" "No worries, mate.","informal",["Australian","reassurance","friendliness"],"au"),
    e("good-on-ya","Good on ya","Well done; good for you","Australian expression","You got the job? Good on ya, mate!","informal",["Australian","praise","approval"],"au"),
    e("arvo","Arvo","Afternoon","Australian slang","See you this arvo around three o'clock.","informal",["Australian","time","slang"],"au"),
    e("brekkie","Brekkie","Breakfast","Australian slang","Let's grab some brekkie before we head out.","informal",["Australian","food","morning"],"au"),
    e("how-ya-going","How ya going?","How are you?","Australian greeting","Hey mate, how ya going?","informal",["Australian","greeting","social"],"au"),
    e("chuck-a-sickie","Chuck a sickie","To call in sick when you're not actually ill","Australian expression","The weather is perfect today — I might chuck a sickie.","informal",["Australian","work","deception"],"au"),
    e("tall-poppy-syndrome","Tall poppy syndrome","The tendency to criticize those who have achieved success","Australian cultural concept","She was afraid of tall poppy syndrome if she talked publicly about her success.","standard",["Australian","culture","success"],"au"),
    e("shell-be-right","She'll be right","Everything will be fine, don't worry","Australian expression","I'm worried the project will fail." "Don't stress — she'll be right!","informal",["Australian","optimism","reassurance"],"au"),
    e("hard-yakka","Hard yakka","Hard work","Australian slang, from Yagara word 'yaga' meaning work","Building that fence in the heat was hard yakka.","informal",["Australian","work","effort"],"au"),
    e("true-blue","True blue","Genuinely Australian; loyal and trustworthy","Australian expression","He's a true blue Aussie — born and bred in the outback.","informal",["Australian","loyalty","genuine"],"au"),
    e("bushed","Bushed","Exhausted; or lost in the bush","Australian expression","I'm absolutely bushed after that twelve-hour hike.","informal",["Australian","tired","exhaustion"],"au"),
    e("reckon","Reckon","Think or believe","Australian slang","I reckon we should leave early to avoid the traffic.","informal",["Australian","opinion","belief"],"au"),
    e("crook","Crook","Sick, unwell, or dishonest","Australian slang","I'm feeling a bit crook today — might stay home.","informal",["Australian","sick","health"],"au"),
    e("give-it-a-burl","Give it a burl","Give it a try","Australian expression","I've never tried surfing before, but I'll give it a burl.","informal",["Australian","attempt","courage"],"au"),
    e("stoked","Stoked","Very excited or pleased","Australian slang","I'm absolutely stoked about the trip to Bali.","informal",["Australian","excitement","happiness"],"au"),
    e("heaps","Heaps","A lot; very much","Australian informal","There were heaps of people at the festival.","informal",["Australian","quantity","amount"],"au"),
    e("dag","Dag","A socially awkward person; used affectionately","Australian slang","Oh, you're such a dag — in a good way!","informal",["Australian","personality","humor"],"au"),
    e("bogan","Bogan","An uncultured or unsophisticated person","Australian slang","He showed up to the formal dinner in thongs — what a bogan.","informal",["Australian","class","culture"],"au"),
    e("ripper","Ripper","Excellent; great","Australian slang","That was an absolute ripper of a game!","informal",["Australian","excellence","approval"],"au"),
    e("servo","Servo","A service station, petrol station","Australian slang","I'll stop at the servo to fill up the tank.","informal",["Australian","petrol","driving"],"au"),
    e("smoko","Smoko","A short break from work, originally for a cigarette","Australian expression","We'll take a smoko at ten o'clock.","informal",["Australian","break","work"],"au"),
    e("barbie","Barbie","Barbecue","Australian slang","We're having a barbie on Saturday — bring some salads.","informal",["Australian","food","social"],"au"),
    e("thongs","Thongs","Flip-flop sandals","Australian slang (not underwear!)","Don't forget your thongs for the beach.","informal",["Australian","footwear","beach"],"au"),
    e("yeah-nah","Yeah nah","No; polite disagreement","Australian expression","Do you want to come out tonight?" "Yeah nah, I'm a bit tired.","informal",["Australian","refusal","politeness"],"au"),
    e("nah-yeah","Nah yeah","Yes; agreement (despite starting with no)","Australian expression","Was it a good film?" "Nah yeah, it was actually great!","informal",["Australian","agreement","informal"],"au"),
    e("spit-the-dummy","Spit the dummy","To have a tantrum; to overreact with anger","Australian expression","The toddler spat the dummy when we left the playground.","informal",["Australian","anger","tantrum"],"au"),
    e("couldnt-be-stuffed","Couldn't be stuffed","Can't be bothered","Australian expression","I was meant to clean the house but I couldn't be stuffed.","informal",["Australian","laziness","motivation"],"au"),
    e("going-off","Going off","Very exciting; really happening","Australian slang","That party was absolutely going off!","informal",["Australian","excitement","party"],"au"),
    e("flat-out-like-a-lizard-drinking","Flat out like a lizard drinking","Extremely busy","Australian expression","I've been flat out like a lizard drinking all week.","informal",["Australian","busy","work"],"au"),
    e("buckleys-chance","Buckley's chance","Little to no chance at all","Australian expression, from William Buckley","You've got Buckley's chance of getting a refund from them.","informal",["Australian","chance","hope"],"au"),
    e("down-the-gurgler","Down the gurgler","Lost, wasted, or ruined","Australian expression","All that hard work went down the gurgler when the company folded.","informal",["Australian","loss","failure"],"au"),
    e("rough-as-guts","Rough as guts","Very rough, uncouth, or of poor quality","Australian expression","That rental car was rough as guts — I couldn't believe it.","informal",["Australian","quality","rough"],"au"),
    e("drongo","Drongo","A foolish or stupid person","Australian slang","Don't be a drongo — read the instructions first.","informal",["Australian","foolish","insult"],"au"),
    e("galah","Galah","A foolish or stupid person; from the native bird","Australian slang","Stop being such a galah and think before you act.","informal",["Australian","foolish","bird"],"au"),
    e("stone-the-crows","Stone the crows","Expression of surprise or disbelief","Australian expression","Stone the crows, you actually pulled it off!","informal",["Australian","surprise","exclamation"],"au"),
    e("strewth","Strewth","An exclamation of surprise or dismay","Australian expression","Strewth, that's an enormous spider!","informal",["Australian","surprise","exclamation"],"au"),
    e("beyond-the-black-stump","Beyond the black stump","In the middle of nowhere; very remote","Australian expression","He lives beyond the black stump — three hours from the nearest town.","informal",["Australian","remote","distance"],"au"),
    e("back-of-bourke","Back of Bourke","Very remote; in the middle of nowhere","Australian expression, from the remote town of Bourke","The farm is way back of Bourke — I'm not driving out there.","informal",["Australian","remote","distance"],"au"),
    e("woop-woop","Woop Woop","A very remote or insignificant place","Australian slang","I'm not driving all the way out to woop woop for a meeting.","informal",["Australian","remote","humor"],"au"),
    e("piece-of-piss","Piece of piss","Very easy","Australian vulgar slang","That exam was a total piece of piss.","vulgar",["Australian","easy","vulgar"],"au"),
    e("full-as-a-boot","Full as a boot","Very drunk or completely full from eating","Australian expression","I'm full as a boot — I cannot eat another bite.","informal",["Australian","drunk","food"],"au"),
    e("have-a-squiz","Have a squiz","Have a look","Australian slang","Have a squiz at this photo — does it look familiar?","informal",["Australian","look","curiosity"],"au"),
    e("off-like-a-bucket-of-prawns","Off like a bucket of prawns in the sun","Leaving very quickly; also: something going bad fast","Australian expression","As soon as the speech ended, he was off like a bucket of prawns in the sun.","informal",["Australian","speed","leaving"],"au"),
    e("few-roos-loose","A few roos loose in the top paddock","Not quite sane; a bit crazy","Australian expression","I think there might be a few roos loose in the top paddock there.","informal",["Australian","crazy","humor"],"au"),
    e("mad-as-a-cut-snake","As mad as a cut snake","Very angry or completely crazy","Australian expression","When he found out, he was as mad as a cut snake.","informal",["Australian","angry","crazy"],"au"),
    e("shoot-through","Shoot through","To leave suddenly without saying goodbye","Australian expression","He shot through without telling anyone where he was going.","informal",["Australian","leaving","departure"],"au"),
    e("have-a-blue","Have a blue","Have an argument or fight","Australian expression","The neighbors had a big blue last night — we heard everything.","informal",["Australian","argument","conflict"],"au"),
    e("make-a-quid","Make a quid","To earn money","Australian expression","He'll do just about anything to make a quid.","informal",["Australian","money","work"],"au"),
    e("your-shout","Your shout","It's your turn to buy drinks","Australian expression","I got the last round, so it's your shout.","informal",["Australian","drinks","social"],"au"),
    e("the-never-never","The never never","The remote Australian outback","Australian expression","They sold everything and disappeared into the never never.","standard",["Australian","remote","outback"],"au"),
    e("beaut","Beaut","Great; wonderful","Australian slang","That's a beaut idea — let's do it!","informal",["Australian","approval","excellent"],"au"),
    e("bonzer","Bonzer","Excellent (old-fashioned)","Australian slang, now somewhat dated","That was a bonzer meal — the best I've had in years.","informal",["Australian","excellence","old-fashioned"],"au"),
    e("go-walkabout","Go walkabout","To go on a long journey; or to disappear unexpectedly","Australian expression, from Aboriginal tradition of long journeys","The boss has gone walkabout — no one's seen him since Monday.","informal",["Australian","journey","disappear"],"au"),
    e("crikey","Crikey","Expression of surprise or astonishment","Australian expression, associated with Steve Irwin","Crikey, that's an enormous crocodile!","informal",["Australian","surprise","exclamation"],"au"),
    e("tinny","Tinny","A can of beer; or a small aluminium boat","Australian slang","Grab me a tinny from the esky, would ya?","informal",["Australian","beer","drink"],"au"),
    e("esky","Esky","A portable cooler for drinks and food","Australian brand name used generically","Put the drinks in the esky before we head to the beach.","informal",["Australian","cooler","beach"],"au"),
    e("bottle-o","Bottle-o","A liquor store","Australian slang","I'll swing by the bottle-o on the way home.","informal",["Australian","alcohol","shopping"],"au"),
    e("hoon","Hoon","Someone who drives recklessly","Australian slang","Those hoons are going way too fast through the suburb.","informal",["Australian","driving","reckless"],"au"),
    e("bludge","Bludge","To freeload; to avoid doing any work","Australian slang","Stop bludging off your parents and find a job.","informal",["Australian","laziness","freeloading"],"au"),
    e("chuck-a-uey","Chuck a U-ey","To make a U-turn while driving","Australian slang","We missed the turn — chuck a U-ey at the lights.","informal",["Australian","driving","direction"],"au"),
    e("sticky-beak","Stickybeak","A nosy person who pries into others' business","Australian slang","Don't be a stickybeak — it's none of your business.","informal",["Australian","nosy","curiosity"],"au"),
    e("grouse","Grouse","Excellent; great (Melbourne slang)","Australian slang, especially in Victoria","That's a grouse idea — let's go with it!","informal",["Australian","excellent","approval"],"au"),
    e("up-a-gum-tree","Up a gum tree","In trouble with no obvious solution","Australian expression","Without a lawyer, you're really up a gum tree.","informal",["Australian","trouble","help"],"au"),
    e("cracker","Cracker","Something excellent or particularly enjoyable","Australian slang","That was a cracker of a match — best of the season.","informal",["Australian","excellent","approval"],"au"),
    e("the-full-quid","Not the full quid","Not very intelligent; not quite all there","Australian expression, 'quid' = pound/dollar","He means well but he's not quite the full quid.","informal",["Australian","intelligence","money"],"au"),
    e("do-your-block","Do your block","To lose your temper completely","Australian expression","He did his block when he saw the damage to the car.","informal",["Australian","anger","temper"],"au"),
    e("cop-it-sweet","Cop it sweet","To accept something without complaining","Australian expression","He copped it sweet when they cut his overtime.","informal",["Australian","acceptance","stoicism"],"au"),
    e("bush-telegraph","Bush telegraph","The informal spread of news or gossip","Australian expression, from pre-telephone rural communication","The bush telegraph had everyone knowing about it by morning.","informal",["Australian","gossip","rural"],"au"),
    e("oldies","The oldies","One's parents","Australian slang","I'm going to visit the oldies this weekend.","informal",["Australian","family","parents"],"au"),
    e("chockers","Chockers","Completely full; packed","Australian slang","The beach was absolutely chockers on New Year's Day.","informal",["Australian","full","crowded"],"au"),
    e("blind-freddy","Blind Freddy could see that","It should be obvious to absolutely everyone","Australian expression","Blind Freddy could see that was a terrible investment.","informal",["Australian","obvious","clarity"],"au"),
    e("ta","Ta","Thank you","Australian informal","Ta for the help — really appreciate it!","informal",["Australian","gratitude","informal"],"au"),
    e("liquid-lunch","Liquid lunch","A lunch consisting mainly of alcoholic drinks","Australian expression (also British)","The whole team had a liquid lunch to celebrate the contract win.","informal",["Australian","alcohol","humor"],"au"),
    e("up-the-duff","Up the duff","Pregnant","Australian informal","She's three months up the duff — very exciting news!","informal",["Australian","pregnancy","informal"],"au"),
    e("rooted","Rooted","Exhausted; broken; ruined","Australian vulgar slang","My car is completely rooted — it won't even start.","vulgar",["Australian","broken","exhausted"],"au"),
    e("maccas","Maccas","McDonald's","Australian slang","Let's grab some Maccas on the way home from the footy.","informal",["Australian","food","fast-food"],"au"),
    e("no-hoper","No-hoper","A person or thing with no chance of success","Australian slang","That project was a no-hoper from day one.","informal",["Australian","failure","hopeless"],"au"),
    e("as-dry-as-a-dead-dingos-donger","As dry as a dead dingo's donger","Extremely dry","Australian vulgar expression","After the hike, I was as dry as a dead dingo's donger.","vulgar",["Australian","dry","thirst"],"au"),
    e("she-ll-be-apples","She'll be apples","Everything will work out fine","Australian rhyming slang variant","Stop worrying about the presentation — she'll be apples.","informal",["Australian","reassurance","optimism"],"au"),
]

def main():
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)

    existing_ids = {e["id"] for e in data}
    added = 0
    skipped = 0

    for expr in NEW:
        if expr["id"] in existing_ids:
            skipped += 1
        else:
            data.append(expr)
            existing_ids.add(expr["id"])
            added += 1

    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    from collections import Counter
    regions = Counter(e.get("region") for e in data)
    langs   = Counter(e.get("language") for e in data)
    print(f"Added: {added} | Skipped (duplicates): {skipped}")
    print(f"Total expressions: {len(data)}")
    print(f"By region: {dict(sorted(regions.items()))}")
    print(f"By language: {dict(langs)}")

if __name__ == "__main__":
    main()
