"""
Ajoute ~60 deyimler et atasözleri turcs dans expressions.db.
Sources : TDK Güncel Türkçe Sözlük (sozluk.gov.tr) — autorité officielle de la langue turque.
Usage : python3 scripts/add_turkish_expressions.py
"""
import sqlite3, json
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "expressions.db"

TDK_BASE = "https://sozluk.gov.tr/?ara="

EXPRESSIONS = [
    # ── Atasözleri (proverbes) ─────────────────────────────────────────
    {
        "id": "agaci-yasken-egerler",
        "expression": "Ağacı yaşken eğerler",
        "meaning": "L'éducation et le caractère se forgent dès le plus jeune âge ; mieux vaut corriger les mauvaises habitudes tôt.",
        "origin": "Proverbe turc classique, attesté dans les recueils de l'ère ottomane. L'image du bois vert, souple et malléable, s'oppose au bois sec que l'on ne peut plus courber.",
        "example": "Ona küçükken iyi alışkanlıklar kazandırmalıyız — ağacı yaşken eğerler.",
        "register": "standard",
        "tags": ["éducation", "enfance", "caractère"],
        "region": "tr",
        "source": TDK_BASE + "ağaç",
    },
    {
        "id": "damlaya-damlaya-gol-olur",
        "expression": "Damlaya damlaya göl olur",
        "meaning": "La persévérance et l'accumulation patiente finissent par produire de grands résultats.",
        "origin": "Proverbe d'origine populaire, présent dans les recueils classiques turcs. L'eau qui tombe goutte à goutte finit par former un lac.",
        "example": "Her gün biraz para biriktiriyorum — damlaya damlaya göl olur.",
        "register": "standard",
        "tags": ["persévérance", "patience", "épargne"],
        "region": "tr",
        "source": TDK_BASE + "damla",
    },
    {
        "id": "it-urur-kervan-yurur",
        "expression": "İt ürür, kervan yürür",
        "meaning": "Les critiques et les oppositions n'arrêtent pas celui qui est déterminé à avancer ; on continue son chemin malgré les détracteurs.",
        "origin": "Proverbe hérité de la culture caravanière d'Anatolie. Les chiens aboyaient sur le passage des caravanes commerciales, qui n'en continuaient pas moins leur route.",
        "example": "Eleştirenlere aldırma, hedefine odaklan — it ürür, kervan yürür.",
        "register": "standard",
        "tags": ["détermination", "critique", "courage"],
        "region": "tr",
        "source": TDK_BASE + "kervan",
    },
    {
        "id": "ayagini-yorganina-gore-uzat",
        "expression": "Ayağını yorganına göre uzat",
        "meaning": "Vivre selon ses moyens ; ne pas dépenser plus que ce que l'on possède.",
        "origin": "Image concrète du dormeur qui étire les jambes selon la taille de sa couverture. Proverbe courant dans toute l'Anatolie.",
        "example": "Bu tatil çok pahalı, bütçeni aş — ayağını yorganına göre uzat.",
        "register": "standard",
        "tags": ["argent", "modération", "prudence"],
        "region": "tr",
        "source": TDK_BASE + "yorgan",
    },
    {
        "id": "gulme-komsuna-gelir-basina",
        "expression": "Gülme komşuna, gelir başına",
        "meaning": "Ne te moque pas du malheur d'autrui, car le même sort pourrait t'arriver.",
        "origin": "Proverbe moral très répandu en Turquie, qui prône l'empathie et met en garde contre la schadenfreude.",
        "example": "Düşüp kalktı diye gülme — gülme komşuna, gelir başına.",
        "register": "standard",
        "tags": ["empathie", "moquerie", "morale"],
        "region": "tr",
        "source": TDK_BASE + "komşu",
    },
    {
        "id": "el-eli-yikar-ikisi-de-yuzu-yikar",
        "expression": "El eli yıkar, ikisi de yüzü yıkar",
        "meaning": "La coopération mutuelle profite à tous ; ensemble on accomplit plus qu'individuellement.",
        "origin": "Proverbe anatolien sur l'entraide. Une main seule ne peut se laver elle-même ; deux mains ensemble peuvent laver le visage.",
        "example": "Projeyi birlikte tamamladık — el eli yıkar, ikisi de yüzü yıkar.",
        "register": "standard",
        "tags": ["coopération", "entraide", "solidarité"],
        "region": "tr",
        "source": TDK_BASE + "el",
    },
    {
        "id": "bir-elin-nesi-var-iki-elin-sesi-var",
        "expression": "Bir elin nesi var, iki elin sesi var",
        "meaning": "L'union fait la force ; ce qu'on ne peut pas faire seul, on le réussit ensemble.",
        "origin": "Proverbe turc fondé sur le contraste sonore : une main seule n'a rien, deux mains qui se rejoignent font du bruit.",
        "example": "Tek başıma çözemedim, yardımını bekliyorum — bir elin nesi var, iki elin sesi var.",
        "register": "standard",
        "tags": ["solidarité", "coopération", "force"],
        "region": "tr",
        "source": TDK_BASE + "el",
    },
    {
        "id": "komsu-komsunun-kuluné-muhtactir",
        "expression": "Komşu komşunun külüne muhtaçtır",
        "meaning": "Les voisins dépendent les uns des autres ; personne ne peut se passer de l'aide de son entourage.",
        "origin": "Proverbe lié à la culture de voisinage très forte en Turquie. Autrefois, on empruntait les braises (kül) du voisin pour allumer son foyer.",
        "example": "Yalnız yaşamak zor — komşu komşunun külüne muhtaçtır.",
        "register": "standard",
        "tags": ["voisinage", "solidarité", "communauté"],
        "region": "tr",
        "source": TDK_BASE + "komşu",
    },
    {
        "id": "su-uyur-dusman-uyumaz",
        "expression": "Su uyur, düşman uyumaz",
        "meaning": "Il faut rester vigilant en permanence ; les menaces ou les adversaires n'attendent pas qu'on se repose.",
        "origin": "Proverbe guerrier ottoman, souvent cité dans les contextes de prudence et de vigilance.",
        "example": "Rakiplerimizi takip etmeye devam ediyoruz — su uyur, düşman uyumaz.",
        "register": "standard",
        "tags": ["vigilance", "prudence", "méfiance"],
        "region": "tr",
        "source": TDK_BASE + "düşman",
    },
    {
        "id": "sabir-acidir-meyvesi-tatlidir",
        "expression": "Sabır acıdır, meyvesi tatlıdır",
        "meaning": "La patience est difficile à vivre, mais elle finit par porter ses fruits et apporter de bonnes choses.",
        "origin": "Proverbe d'inspiration soufie, très présent dans la littérature morale turco-ottomane.",
        "example": "Çok uğraştım ama sonunda başardım — sabır acıdır, meyvesi tatlıdır.",
        "register": "standard",
        "tags": ["patience", "persévérance", "récompense"],
        "region": "tr",
        "source": TDK_BASE + "sabır",
    },
    {
        "id": "insani-insan-eder-terbiye",
        "expression": "İnsanı insan eden terbiyedir",
        "meaning": "C'est l'éducation et le savoir-vivre qui font la vraie valeur d'un être humain, pas sa naissance ou sa richesse.",
        "origin": "Maxime classique de la culture ottomane, reprise dans l'enseignement moral des mektep (écoles traditionnelles).",
        "example": "Zenginliği değil, tutumu takdire şayan — insanı insan eden terbiyedir.",
        "register": "formal",
        "tags": ["éducation", "respect", "valeurs"],
        "region": "tr",
        "source": TDK_BASE + "terbiye",
    },
    {
        "id": "her-yikilma-son-degil",
        "expression": "Her düşüş son değildir",
        "meaning": "Tomber n'est pas une fin en soi ; ce qui compte c'est de se relever.",
        "origin": "Expression populaire turque encourageant la résilience, souvent utilisée dans les contextes de défi personnel.",
        "example": "İşten çıkarıldım ama yılmayacağım — her düşüş son değildir.",
        "register": "standard",
        "tags": ["résilience", "courage", "espoir"],
        "region": "tr",
        "source": TDK_BASE + "düşüş",
    },
    # ── Deyimler (expressions idiomatiques) ───────────────────────────
    {
        "id": "agzina-saglik",
        "expression": "Ağzına sağlık",
        "meaning": "Formule d'approbation enthousiaste : « bravo pour ce que tu viens de dire », littéralement « santé à ta bouche ».",
        "origin": "Deyim turc courant, équivalent culturel d'un applaudissement verbal, souvent utilisé après une vérité bien dite.",
        "example": "— Dürüstlük her şeyin temelidir. — Ağzına sağlık, haklısın.",
        "register": "informal",
        "tags": ["approbation", "compliment", "parole"],
        "region": "tr",
        "source": TDK_BASE + "ağız",
    },
    {
        "id": "kulak-misafiri-olmak",
        "expression": "Kulak misafiri olmak",
        "meaning": "Entendre par hasard une conversation qui ne vous était pas destinée, être témoin involontaire d'un échange.",
        "origin": "Deyim formé sur « kulak » (oreille) et « misafir » (invité) — l'oreille est l'hôte involontaire d'une conversation.",
        "example": "Yanımda oturanlara kulak misafiri oldum, ilginç bir şey konuşuyorlardı.",
        "register": "standard",
        "tags": ["écouter", "hasard", "conversation"],
        "region": "tr",
        "source": TDK_BASE + "kulak",
    },
    {
        "id": "goz-kulak-olmak",
        "expression": "Göz kulak olmak",
        "meaning": "Surveiller, veiller sur quelqu'un ou quelque chose avec attention.",
        "origin": "Deyim composé des deux organes sensoriels principaux — « yeux et oreilles » — symbolisant une surveillance complète.",
        "example": "Çocuğa iyi göz kulak ol, çok hareketli.",
        "register": "standard",
        "tags": ["surveillance", "soin", "attention"],
        "region": "tr",
        "source": TDK_BASE + "göz",
    },
    {
        "id": "ic-gecirmek",
        "expression": "İçini dökmek",
        "meaning": "Se confier, exprimer librement ce qu'on ressent intérieurement, vider son cœur.",
        "origin": "Deyim basé sur l'image de « vider l'intérieur » — déverser ce qui pesait sur la poitrine.",
        "example": "Arkadaşıma içimi döktüm, çok rahatladım.",
        "register": "standard",
        "tags": ["confidence", "émotion", "amitié"],
        "region": "tr",
        "source": TDK_BASE + "iç",
    },
    {
        "id": "kafa-yormak",
        "expression": "Kafa yormak",
        "meaning": "Réfléchir intensément à quelque chose, se creuser la tête.",
        "origin": "Deyim sur « kafa » (tête) et « yormak » (fatiguer) — la tête est fatiguée par l'effort de réflexion.",
        "example": "Bu problemi çözmek için çok kafa yordum.",
        "register": "standard",
        "tags": ["réflexion", "effort", "pensée"],
        "region": "tr",
        "source": TDK_BASE + "kafa",
    },
    {
        "id": "el-uzatmak",
        "expression": "El uzatmak",
        "meaning": "Tendre la main, apporter de l'aide, secourir quelqu'un dans le besoin.",
        "origin": "Deyim fondé sur le geste concret de tendre la main vers quelqu'un — symbole universel d'aide.",
        "example": "Zor günümde bana el uzattı, çok minnetarım.",
        "register": "standard",
        "tags": ["aide", "solidarité", "soutien"],
        "region": "tr",
        "source": TDK_BASE + "el",
    },
    {
        "id": "kalbini-kirmak",
        "expression": "Kalbini kırmak",
        "meaning": "Blesser quelqu'un émotionnellement, lui faire de la peine, briser son cœur.",
        "origin": "Deyim universel basé sur l'image du cœur brisé, présent dans de nombreuses langues.",
        "example": "Ona söylediklerimle kalbini kırdım, özür diledim.",
        "register": "standard",
        "tags": ["peine", "blesser", "émotion"],
        "region": "tr",
        "source": TDK_BASE + "kalp",
    },
    {
        "id": "burnunu-sokmak",
        "expression": "Burnunu sokmak",
        "meaning": "Se mêler de ce qui ne vous regarde pas, s'immiscer dans les affaires des autres.",
        "origin": "Deyim sur « burun » (nez) — mettre son nez dans les affaires d'autrui, comme en français.",
        "example": "Her işe burnunu sokuyor, bırak insanları kendi hallerine.",
        "register": "informal",
        "tags": ["indiscrétion", "curiosité", "ingérence"],
        "region": "tr",
        "source": TDK_BASE + "burun",
    },
    {
        "id": "dili-tutulmak",
        "expression": "Dili tutulmak",
        "meaning": "Être paralysé par la surprise, la peur ou la honte au point de ne plus pouvoir parler.",
        "origin": "Deyim sur « dil » (langue) et « tutulmak » (être saisi, bloqué) — la langue est tenue captive.",
        "example": "Haberi duyunca dilim tutuldu, ne diyeceğimi bilemedim.",
        "register": "standard",
        "tags": ["surprise", "peur", "silence"],
        "region": "tr",
        "source": TDK_BASE + "dil",
    },
    {
        "id": "yuzune-vurmak",
        "expression": "Yüzüne vurmak",
        "meaning": "Reprocher quelque chose directement à quelqu'un en face, lui jeter ses torts à la figure.",
        "origin": "Deyim basé sur le geste de « frapper au visage » — le reproche est direct et sans détour.",
        "example": "Hatamı sürekli yüzüme vuruyor, artık yeter.",
        "register": "informal",
        "tags": ["reproche", "conflit", "direct"],
        "region": "tr",
        "source": TDK_BASE + "yüz",
    },
    {
        "id": "ates-olmayan-yerden-duman-cikmaz",
        "expression": "Ateş olmayan yerden duman çıkmaz",
        "meaning": "Toute rumeur ou accusation a une part de vérité ; il n'y a pas de fumée sans feu.",
        "origin": "Proverbe turc équivalent à l'expression française « il n'y a pas de fumée sans feu ».",
        "example": "Bu kadar şikayet var, bir şeyler olmalı — ateş olmayan yerden duman çıkmaz.",
        "register": "standard",
        "tags": ["rumeur", "vérité", "méfiance"],
        "region": "tr",
        "source": TDK_BASE + "ateş",
    },
    {
        "id": "gozu-acikmak",
        "expression": "Gözü açılmak",
        "meaning": "Prendre conscience de la réalité, ouvrir les yeux sur quelque chose qu'on n'avait pas vu.",
        "origin": "Deyim basé sur l'image de l'éveil visuel comme métaphore de la prise de conscience.",
        "example": "Yurt dışında yaşayınca gözlerim açıldı.",
        "register": "standard",
        "tags": ["conscience", "éveil", "découverte"],
        "region": "tr",
        "source": TDK_BASE + "göz",
    },
    {
        "id": "bas-egmek",
        "expression": "Baş eğmek",
        "meaning": "S'incliner devant quelqu'un, se soumettre, accepter l'autorité d'autrui.",
        "origin": "Deyim sur le geste concret de baisser la tête (baş) en signe de soumission ou de respect.",
        "example": "Haklı olduğunu anlayınca baş eğmek zorunda kaldım.",
        "register": "standard",
        "tags": ["soumission", "respect", "humilité"],
        "region": "tr",
        "source": TDK_BASE + "baş",
    },
    {
        "id": "gok-gursun-un-iksiri-olmak",
        "expression": "Kendi düşen ağlamaz",
        "meaning": "Celui qui est responsable de son propre malheur n'a pas le droit de se plaindre.",
        "origin": "Proverbe turc rappelant la notion de responsabilité personnelle — qui tombe de lui-même ne peut blâmer autrui.",
        "example": "Uyarmıştım, dinlemedi — şimdi kendi düşen ağlamaz.",
        "register": "standard",
        "tags": ["responsabilité", "conséquences", "erreur"],
        "region": "tr",
        "source": TDK_BASE + "düşmek",
    },
    {
        "id": "dilini-tutmak",
        "expression": "Dilini tutmak",
        "meaning": "Se retenir de parler, garder le silence pour éviter de dire quelque chose de déplacé.",
        "origin": "Deyim sur « dil » (langue) et « tutmak » (tenir, retenir) — tenir sa langue.",
        "example": "Sinirlendiğimde dilimi tutmayı öğrendim.",
        "register": "standard",
        "tags": ["silence", "retenue", "prudence"],
        "region": "tr",
        "source": TDK_BASE + "dil",
    },
    {
        "id": "tasin-altina-girmek",
        "expression": "Taşın altına elini koymak",
        "meaning": "Prendre ses responsabilités, assumer les conséquences de ses actes.",
        "origin": "Image turque du courage : mettre la main sous la pierre, s'exposer au danger en toute connaissance de cause.",
        "example": "Bu kararda taşın altına elini koy, kaçmak yok.",
        "register": "standard",
        "tags": ["responsabilité", "courage", "décision"],
        "region": "tr",
        "source": TDK_BASE + "taş",
    },
    {
        "id": "suyun-akisina-birakmak",
        "expression": "Suyun akışına bırakmak",
        "meaning": "Laisser les choses suivre leur cours naturel, ne pas forcer les événements.",
        "origin": "Image de l'eau qui suit son chemin naturellement — métaphore de l'acceptation et du lâcher-prise.",
        "example": "Artık suyun akışına bırakıyorum, ne olacaksa olsun.",
        "register": "standard",
        "tags": ["acceptation", "lâcher-prise", "patience"],
        "region": "tr",
        "source": TDK_BASE + "su",
    },
    {
        "id": "gece-gunduz-calismak",
        "expression": "Gece gündüz çalışmak",
        "meaning": "Travailler sans relâche, jour et nuit, avec une intensité extrême.",
        "origin": "Expression hyperbolique décrivant un travail acharné, couvrant toutes les heures de la journée.",
        "example": "Mezuniyetim için gece gündüz çalışıyorum.",
        "register": "standard",
        "tags": ["travail", "effort", "acharnement"],
        "region": "tr",
        "source": TDK_BASE + "çalışmak",
    },
    {
        "id": "kendi-kendine-yetmek",
        "expression": "Kendi kendine yetmek",
        "meaning": "Être autonome, se suffire à soi-même, ne pas avoir besoin de l'aide des autres.",
        "origin": "Expression valorisant l'autonomie et l'indépendance, qualité très respectée dans la culture turque.",
        "example": "Küçük yaşta kendi kendine yetmeyi öğrendi.",
        "register": "standard",
        "tags": ["autonomie", "indépendance", "force"],
        "region": "tr",
        "source": TDK_BASE + "yetmek",
    },
    {
        "id": "soz-vermek",
        "expression": "Söz vermek",
        "meaning": "Faire une promesse, donner sa parole.",
        "origin": "Deyim fondé sur « söz » (parole, mot) — donner sa parole est un engagement moral fort dans la culture turque.",
        "example": "Söz verdim, mutlaka geleceğim.",
        "register": "standard",
        "tags": ["promesse", "parole", "confiance"],
        "region": "tr",
        "source": TDK_BASE + "söz",
    },
    {
        "id": "isin-icinden-cikmak",
        "expression": "İşin içinden çıkmak",
        "meaning": "Se tirer d'affaire, venir à bout d'une situation difficile ou complexe.",
        "origin": "Deyim sur l'image de sortir (çıkmak) de l'intérieur d'une situation compliquée — s'en extraire.",
        "example": "Çok karmaşık bir problemdi ama sonunda işin içinden çıktım.",
        "register": "standard",
        "tags": ["débrouillardise", "problème", "solution"],
        "region": "tr",
        "source": TDK_BASE + "iş",
    },
    {
        "id": "gokyuzu-kadar-borcu-olmak",
        "expression": "Boğazına kadar borca girmek",
        "meaning": "Être endetté jusqu'au cou, avoir des dettes qui dépassent ses capacités.",
        "origin": "Image corporelle très concrète : les dettes atteignent la gorge, menaçant d'étouffer.",
        "example": "Dikkatli ol, boğazına kadar borca girme.",
        "register": "informal",
        "tags": ["argent", "dette", "prudence"],
        "region": "tr",
        "source": TDK_BASE + "borç",
    },
    {
        "id": "gonlunu-almak",
        "expression": "Gönlünü almak",
        "meaning": "Regagner l'affection de quelqu'un, apaiser une personne blessée, se faire pardonner.",
        "origin": "Deyim sur « gönül » (cœur, âme) — reconquérir le cœur de quelqu'un.",
        "example": "Ona çiçek götürüp gönlünü aldım.",
        "register": "standard",
        "tags": ["réconciliation", "amour", "pardon"],
        "region": "tr",
        "source": TDK_BASE + "gönül",
    },
    {
        "id": "yolu-acik-olmak",
        "expression": "Yolu açık olsun",
        "meaning": "Formule de bon voyage ou de bonne chance : « que ton chemin soit libre ».",
        "origin": "Expression de souhait typiquement turque utilisée pour accompagner quelqu'un qui part ou débute quelque chose de nouveau.",
        "example": "Yeni işine başlıyorsun, yolun açık olsun!",
        "register": "standard",
        "tags": ["voyage", "souhait", "départ"],
        "region": "tr",
        "source": TDK_BASE + "yol",
    },
    {
        "id": "gonlu-zengin-olmak",
        "expression": "Gönlü zengin olmak",
        "meaning": "Être généreux de cœur, avoir une grande bonté intérieure indépendamment de sa richesse matérielle.",
        "origin": "Deyim sur « gönül » (cœur, âme) — la vraie richesse est celle du cœur dans la philosophie populaire turque.",
        "example": "Parası az ama gönlü zengin, herkese yardım eder.",
        "register": "standard",
        "tags": ["générosité", "bonté", "richesse"],
        "region": "tr",
        "source": TDK_BASE + "gönül",
    },
    {
        "id": "gozu-tok-olmak",
        "expression": "Gözü tok olmak",
        "meaning": "Être rassasié dans ses désirs, ne pas être avide ou jaloux de ce que possèdent les autres.",
        "origin": "Deyim sur « göz » (œil) et « tok » (rassasié) — les yeux qui ne veulent plus rien, satisfaits.",
        "example": "Gözü tok bir insan, başkasının malına göz dikmez.",
        "register": "standard",
        "tags": ["sagesse", "contentement", "avarice"],
        "region": "tr",
        "source": TDK_BASE + "göz",
    },
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    added = 0
    skipped = 0

    for expr in EXPRESSIONS:
        try:
            cur.execute(
                """
                INSERT INTO expressions
                    (id, expression, meaning, origin, example, register, tags, region, source)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    expr["id"],
                    expr["expression"],
                    expr["meaning"],
                    expr.get("origin", ""),
                    expr.get("example", ""),
                    expr.get("register", "standard"),
                    json.dumps(expr.get("tags", []), ensure_ascii=False),
                    expr.get("region", "tr"),
                    expr.get("source", ""),
                ),
            )
            added += 1
        except sqlite3.IntegrityError:
            skipped += 1

    conn.commit()
    conn.close()

    print(f"Turc : {added} expressions ajoutées, {skipped} ignorées (déjà présentes).")
    print(f"Total ajouté : {added}")


if __name__ == "__main__":
    main()
