"""
Ajoute ~60 espressioni idiomatiche et proverbi italiens dans expressions.db.
Sources : Treccani Vocabolario (treccani.it) — référence officielle italienne, liée à l'Accademia della Crusca.
Usage : python3 scripts/add_italian_expressions.py
"""
import sqlite3, json
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "expressions.db"

TRECCANI_BASE = "https://www.treccani.it/vocabolario/"

EXPRESSIONS = [
    # ── Proverbi ───────────────────────────────────────────────────────
    {
        "id": "chi-dorme-non-piglia-pesci",
        "expression": "Chi dorme non piglia pesci",
        "meaning": "Celui qui est paresseux ou inactif ne récolte rien ; il faut être diligent pour saisir les opportunités.",
        "origin": "Proverbe d'origine médiévale lié à la pêche en Méditerranée. Attesté dans les recueils de Giovanni Torriano (1666).",
        "example": "Alzati, è già tardi — chi dorme non piglia pesci.",
        "register": "standard",
        "tags": ["travail", "paresse", "opportunité"],
        "region": "it",
        "source": TRECCANI_BASE + "pesce/",
    },
    {
        "id": "chi-va-piano-va-sano-e-va-lontano",
        "expression": "Chi va piano va sano e va lontano",
        "meaning": "Procéder avec méthode et sans précipitation conduit plus loin et plus sainement que la hâte.",
        "origin": "Proverbe latin adapté en italien, présent chez Pétrarque et dans les Adagia d'Érasme. Exprime la sagesse de la lenteur réfléchie.",
        "example": "Non fretta — chi va piano va sano e va lontano.",
        "register": "standard",
        "tags": ["patience", "méthode", "sagesse"],
        "region": "it",
        "source": TRECCANI_BASE + "piano/",
    },
    {
        "id": "tra-il-dire-e-il-fare-ce-di-mezzo-il-mare",
        "expression": "Tra il dire e il fare c'è di mezzo il mare",
        "meaning": "Il y a une grande distance entre les paroles et les actes ; promettre est facile, tenir ses promesses est difficile.",
        "origin": "Proverbe toscan largement diffusé à travers la péninsule. La mer (il mare) symbolise l'obstacle immense entre l'intention et la réalisation.",
        "example": "Dice che cambierà, ma tra il dire e il fare c'è di mezzo il mare.",
        "register": "standard",
        "tags": ["promesse", "action", "réalité"],
        "region": "it",
        "source": TRECCANI_BASE + "dire/",
    },
    {
        "id": "il-lupo-perde-il-pelo-ma-non-il-vizio",
        "expression": "Il lupo perde il pelo ma non il vizio",
        "meaning": "On peut changer d'apparence, mais rarement de nature profonde ; les mauvaises habitudes restent.",
        "origin": "Proverbe d'origine latine (« lupus pilum mutat, non mentem ») repris dans la tradition littéraire italienne depuis Machiavel.",
        "example": "Ha promesso di smettere di fumare mille volte — il lupo perde il pelo ma non il vizio.",
        "register": "standard",
        "tags": ["caractère", "habitude", "changement"],
        "region": "it",
        "source": TRECCANI_BASE + "lupo/",
    },
    {
        "id": "non-tutte-le-ciambelle-riescono-col-buco",
        "expression": "Non tutte le ciambelle riescono col buco",
        "meaning": "Tout ne se passe pas toujours comme prévu ; il faut accepter que certaines choses ne soient pas parfaites.",
        "origin": "Proverbe populaire lié à la tradition culinaire italienne. La ciambella (beignet) est censée avoir un trou ; si elle n'en a pas, c'est un défaut acceptable.",
        "example": "Il progetto non è andato benissimo, ma non tutte le ciambelle riescono col buco.",
        "register": "informal",
        "tags": ["imperfection", "acceptation", "réalisme"],
        "region": "it",
        "source": TRECCANI_BASE + "ciambella/",
    },
    {
        "id": "ogni-promessa-e-debito",
        "expression": "Ogni promessa è debito",
        "meaning": "Toute promesse engage celui qui la fait ; une promesse est une dette morale qu'il faut honorer.",
        "origin": "Maxime d'origine juridique et morale, présente dans le droit romain et dans la littérature populaire italienne depuis le Moyen Âge.",
        "example": "Ti avevo promesso di venire — ogni promessa è debito.",
        "register": "standard",
        "tags": ["promesse", "engagement", "honneur"],
        "region": "it",
        "source": TRECCANI_BASE + "promessa/",
    },
    {
        "id": "chi-semina-vento-raccoglie-tempesta",
        "expression": "Chi semina vento raccoglie tempesta",
        "meaning": "Celui qui provoque ou agit de manière irresponsable récoltera des conséquences bien plus graves.",
        "origin": "Proverbe d'origine biblique (Osée 8:7), passé dans la tradition populaire italienne. La tempête est la conséquence amplifiée du vent semé.",
        "example": "Ha litigato con tutti — chi semina vento raccoglie tempesta.",
        "register": "standard",
        "tags": ["conséquences", "responsabilité", "prudence"],
        "region": "it",
        "source": TRECCANI_BASE + "vento/",
    },
    {
        "id": "a-caval-donato-non-si-guarda-in-bocca",
        "expression": "A caval donato non si guarda in bocca",
        "meaning": "On ne critique pas un cadeau, même imparfait ; il faut accepter gracieusement ce qu'on reçoit.",
        "origin": "Proverbe d'origine latine (« equi donati dentes non inspiciuntur »), attesté en italien dès le XIVe siècle chez Boccace.",
        "example": "Non ti piace il regalo? A caval donato non si guarda in bocca.",
        "register": "standard",
        "tags": ["gratitude", "cadeau", "générosité"],
        "region": "it",
        "source": TRECCANI_BASE + "cavallo/",
    },
    {
        "id": "il-mattino-ha-loro-in-bocca",
        "expression": "Il mattino ha l'oro in bocca",
        "meaning": "Les premières heures de la journée sont les plus précieuses et les plus productives.",
        "origin": "Proverbe toscan popularisé par Leonardo da Vinci et repris dans la tradition littéraire italienne.",
        "example": "Mi alzo alle sei ogni giorno — il mattino ha l'oro in bocca.",
        "register": "standard",
        "tags": ["matin", "productivité", "temps"],
        "region": "it",
        "source": TRECCANI_BASE + "mattino/",
    },
    {
        "id": "paese-che-vai-usanza-che-trovi",
        "expression": "Paese che vai, usanza che trovi",
        "meaning": "Chaque lieu a ses propres coutumes ; il faut s'adapter aux habitudes locales quand on voyage.",
        "origin": "Proverbe d'origine latine (« quot regiones, tot mores »), largement répandu en Italie dès le XVe siècle.",
        "example": "Non sorprenderti delle differenze — paese che vai, usanza che trovi.",
        "register": "standard",
        "tags": ["voyage", "culture", "adaptation"],
        "region": "it",
        "source": TRECCANI_BASE + "paese/",
    },
    {
        "id": "meglio-tardi-che-mai",
        "expression": "Meglio tardi che mai",
        "meaning": "Il vaut mieux faire quelque chose tardivement que de ne pas le faire du tout.",
        "origin": "Adaptation italienne du proverbe latin « potius sero quam numquam », attestée dans toute la péninsule depuis le XVe siècle.",
        "example": "Hai finalmente imparato a nuotare a quarant'anni — meglio tardi che mai!",
        "register": "standard",
        "tags": ["temps", "action", "retard"],
        "region": "it",
        "source": TRECCANI_BASE + "tardi/",
    },
    {
        "id": "non-e-tutto-oro-quello-che-luccica",
        "expression": "Non è tutto oro quello che luccica",
        "meaning": "Les apparences peuvent être trompeuses ; ce qui brille n'est pas forcément de valeur.",
        "origin": "Proverbe issu du Marchand de Venise de Shakespeare (1596) et parallèlement présent dans la tradition populaire italienne. Attesté chez Boccace sous une forme voisine.",
        "example": "Quel progetto sembrava perfetto, ma non è tutto oro quello che luccica.",
        "register": "standard",
        "tags": ["apparences", "tromperie", "sagesse"],
        "region": "it",
        "source": TRECCANI_BASE + "oro/",
    },
    # ── Espressioni idiomatiche ─────────────────────────────────────────
    {
        "id": "in-bocca-al-lupo",
        "expression": "In bocca al lupo",
        "meaning": "Formule de souhait de bonne chance, littéralement « dans la gueule du loup ». La réponse attendue est « Crepi! » (qu'il crève !).",
        "origin": "Expression d'origine incertaine, peut-être théâtrale ou cynégétique. La logique est inversée : souhaiter le pire pour conjurer le sort.",
        "example": "— Domani ho l'esame. — In bocca al lupo! — Crepi!",
        "register": "informal",
        "tags": ["bonne chance", "souhait", "théâtre"],
        "region": "it",
        "source": TRECCANI_BASE + "lupo/",
    },
    {
        "id": "avere-le-mani-in-pasta",
        "expression": "Avere le mani in pasta",
        "meaning": "Être impliqué dans quelque chose, avoir des connexions ou de l'influence dans une affaire.",
        "origin": "Expression basée sur l'image concrète du boulanger qui pétrit la pâte — avoir les mains dans la pâte, c'est être au cœur de l'action.",
        "example": "In questo affare ha le mani in pasta fino al gomito.",
        "register": "standard",
        "tags": ["influence", "implication", "connexions"],
        "region": "it",
        "source": TRECCANI_BASE + "pasta/",
    },
    {
        "id": "fare-orecchi-da-mercante",
        "expression": "Fare orecchi da mercante",
        "meaning": "Faire semblant de ne pas entendre, ignorer délibérément ce qu'on ne veut pas écouter.",
        "origin": "Expression née dans les milieux marchands — le marchand habile faisait la sourde oreille aux protestations des clients ou aux mauvaises nouvelles.",
        "example": "Gli ho chiesto scusa tre volte e lui continua a fare orecchi da mercante.",
        "register": "standard",
        "tags": ["indifférence", "ignorer", "hypocrisie"],
        "region": "it",
        "source": TRECCANI_BASE + "orecchio/",
    },
    {
        "id": "avere-il-pallino",
        "expression": "Avere il pallino di qualcosa",
        "meaning": "Avoir une passion obsessionnelle pour quelque chose, ne penser qu'à ça.",
        "origin": "Le pallino est la petite boule blanche du jeu de pétanque (bocce) — point focal vers lequel tout converge. Métaphore de l'idée fixe.",
        "example": "Ha il pallino della fotografia, passa ore a scattare foto.",
        "register": "informal",
        "tags": ["passion", "obsession", "hobby"],
        "region": "it",
        "source": TRECCANI_BASE + "pallino/",
    },
    {
        "id": "prendere-la-palla-al-balzo",
        "expression": "Prendere la palla al balzo",
        "meaning": "Saisir une opportunité au bon moment, profiter d'une occasion favorable sans tarder.",
        "origin": "Métaphore sportive — attraper la balle au rebond, au moment précis où elle est à portée. Attestée dans la littérature italienne depuis le XVIIe siècle.",
        "example": "Hanno proposto un incontro e ho preso la palla al balzo.",
        "register": "standard",
        "tags": ["opportunité", "réactivité", "chance"],
        "region": "it",
        "source": TRECCANI_BASE + "palla/",
    },
    {
        "id": "girare-al-largo",
        "expression": "Girare al largo",
        "meaning": "Éviter quelqu'un ou quelque chose, garder ses distances par précaution ou par crainte.",
        "origin": "Expression nautique — passer au large d'un écueil, d'une côte dangereuse. Transposée à la vie sociale pour évoquer l'évitement.",
        "example": "Da quando abbiamo litigato, mi gira al largo.",
        "register": "standard",
        "tags": ["évitement", "distance", "prudence"],
        "region": "it",
        "source": TRECCANI_BASE + "largo/",
    },
    {
        "id": "avere-la-luna-storta",
        "expression": "Avere la luna storta",
        "meaning": "Être de mauvaise humeur, de mauvais poil, sans raison apparente.",
        "origin": "Expression fondée sur la croyance populaire que la lune influence l'humeur. La lune « de travers » perturbe l'équilibre émotionnel.",
        "example": "Non parlargli adesso, ha la luna storta.",
        "register": "informal",
        "tags": ["humeur", "colère", "émotions"],
        "region": "it",
        "source": TRECCANI_BASE + "luna/",
    },
    {
        "id": "cavarsela",
        "expression": "Cavarsela",
        "meaning": "S'en tirer, se débrouiller malgré les difficultés, sortir d'une situation compliquée.",
        "origin": "De « cavarsi » (se tirer) — s'extraire soi-même d'une situation. Expression très courante dans l'italien de tous les jours.",
        "example": "La situazione era difficile, ma me la sono cavata.",
        "register": "informal",
        "tags": ["débrouillardise", "résilience", "autonomie"],
        "region": "it",
        "source": TRECCANI_BASE + "cavare/",
    },
    {
        "id": "non-stare-ne-in-cielo-ne-in-terra",
        "expression": "Non stare né in cielo né in terra",
        "meaning": "N'avoir aucun sens, être incohérent, ne tenir ni logiquement ni moralement.",
        "origin": "Expression fondée sur la métaphore du flottement entre ciel et terre — ce qui ne peut se fixer nulle part.",
        "example": "La tua proposta non sta né in cielo né in terra.",
        "register": "standard",
        "tags": ["incohérence", "absurde", "critique"],
        "region": "it",
        "source": TRECCANI_BASE + "cielo/",
    },
    {
        "id": "perdere-il-filo",
        "expression": "Perdere il filo",
        "meaning": "Perdre le fil de ses idées, ne plus suivre le raisonnement, oublier ce qu'on voulait dire.",
        "origin": "Métaphore tissulaire — le fil (filo) du discours ou du raisonnement qui se rompt, à l'image du fil d'Ariane.",
        "example": "Scusa, ho perso il filo — dove eravamo rimasti?",
        "register": "standard",
        "tags": ["mémoire", "concentration", "discours"],
        "region": "it",
        "source": TRECCANI_BASE + "filo/",
    },
    {
        "id": "avere-il-bernoccolo",
        "expression": "Avere il bernoccolo per qualcosa",
        "meaning": "Avoir un don naturel pour quelque chose, une aptitude innée.",
        "origin": "Expression basée sur la phrénologie populaire — le bernoccolo est une bosse sur le crâne censée indiquer un talent particulier.",
        "example": "Ha il bernoccolo per la matematica, capisce tutto subito.",
        "register": "informal",
        "tags": ["talent", "don", "aptitude"],
        "region": "it",
        "source": TRECCANI_BASE + "bernoccolo/",
    },
    {
        "id": "mettere-i-puntini-sulle-i",
        "expression": "Mettere i puntini sulle i",
        "meaning": "Être précis et rigoureux dans ses explications, clarifier les choses dans le moindre détail.",
        "origin": "Expression graphique — poser les points sur les i pour que l'écriture soit lisible. Métaphore de la rigueur et de la clarté.",
        "example": "Lascia che metta i puntini sulle i così non ci sono malintesi.",
        "register": "standard",
        "tags": ["précision", "clarté", "rigueur"],
        "region": "it",
        "source": TRECCANI_BASE + "punto/",
    },
    {
        "id": "tirare-acqua-al-proprio-mulino",
        "expression": "Tirare acqua al proprio mulino",
        "meaning": "Agir dans son propre intérêt en profitant de toutes les situations, souvent aux dépens des autres.",
        "origin": "Image rurale du meunier qui détourne l'eau vers son propre moulin — chacun pour soi dans la concurrence des ressources.",
        "example": "Attenzione a lui — tira sempre acqua al suo mulino.",
        "register": "standard",
        "tags": ["intérêt personnel", "opportunisme", "égoïsme"],
        "region": "it",
        "source": TRECCANI_BASE + "mulino/",
    },
    {
        "id": "fare-il-diavolo-a-quattro",
        "expression": "Fare il diavolo a quattro",
        "meaning": "Faire un scandale, s'agiter dans tous les sens, créer un désordre total.",
        "origin": "Expression médiévale liée aux représentations théâtrales des mystères où quatre diables jouaient ensemble une scène chaotique.",
        "example": "Quando ha saputo la notizia, ha fatto il diavolo a quattro.",
        "register": "informal",
        "tags": ["désordre", "colère", "agitation"],
        "region": "it",
        "source": TRECCANI_BASE + "diavolo/",
    },
    {
        "id": "avere-la-testa-tra-le-nuvole",
        "expression": "Avere la testa tra le nuvole",
        "meaning": "Être distrait, rêveur, avoir la tête dans les nuages, ne pas être attentif à la réalité.",
        "origin": "Métaphore aérienne universelle — la tête qui s'élève au-dessus des nuages perd contact avec la réalité terrestre.",
        "example": "Non ascolta mai — ha sempre la testa tra le nuvole.",
        "register": "standard",
        "tags": ["distraction", "rêverie", "inattention"],
        "region": "it",
        "source": TRECCANI_BASE + "nuvola/",
    },
    {
        "id": "fare-il-passo-piu-lungo-della-gamba",
        "expression": "Fare il passo più lungo della gamba",
        "meaning": "Vouloir aller trop vite ou trop loin par rapport à ses capacités, prendre des risques disproportionnés.",
        "origin": "Expression corporelle — un pas trop grand fait perdre l'équilibre. Métaphore de l'excès d'ambition ou de précipitation.",
        "example": "Vuole aprire tre negozi insieme — sta facendo il passo più lungo della gamba.",
        "register": "standard",
        "tags": ["ambition", "précipitation", "excès"],
        "region": "it",
        "source": TRECCANI_BASE + "passo/",
    },
    {
        "id": "capitare-a-fagiolo",
        "expression": "Capitare a fagiolo",
        "meaning": "Tomber à point nommé, arriver au bon moment, être exactement ce dont on avait besoin.",
        "origin": "Expression d'origine incertaine — le fagiolo (haricot) était un aliment populaire et simple, symbole d'opportunité quotidienne bien saisie.",
        "example": "Avevo bisogno di aiuto e sei arrivato proprio a fagiolo!",
        "register": "informal",
        "tags": ["hasard", "timing", "opportunité"],
        "region": "it",
        "source": TRECCANI_BASE + "fagiolo/",
    },
    {
        "id": "avere-il-sangue-blu",
        "expression": "Avere il sangue blu",
        "meaning": "Être de noble naissance, appartenir à l'aristocratie.",
        "origin": "Expression d'origine médiévale espagnole (sangre azul), adoptée en italien. Les veines des nobles, visibles sous une peau claire non hâlée par le travail, semblaient bleuâtres.",
        "example": "Si comporta come se avesse il sangue blu, ma viene da una famiglia normale.",
        "register": "standard",
        "tags": ["noblesse", "aristocratie", "origine"],
        "region": "it",
        "source": TRECCANI_BASE + "sangue/",
    },
    {
        "id": "non-vedere-lora",
        "expression": "Non vedere l'ora",
        "meaning": "Être impatient, attendre quelque chose avec grande hâte et désir.",
        "origin": "Expression basée sur l'attente du temps — « ne pas voir l'heure » signifie que le temps semble s'étirer tellement l'attente est forte.",
        "example": "Non vedo l'ora di rivederti!",
        "register": "standard",
        "tags": ["impatience", "désir", "attente"],
        "region": "it",
        "source": TRECCANI_BASE + "ora/",
    },
    {
        "id": "mettere-le-carte-in-tavola",
        "expression": "Mettere le carte in tavola",
        "meaning": "Dire clairement ce qu'on veut ou ce qu'on sait, être transparent et honnête dans ses intentions.",
        "origin": "Métaphore du jeu de cartes — étaler ses cartes sur la table, sans les cacher, pour montrer son jeu.",
        "example": "È il momento di mettere le carte in tavola e spiegare la situazione.",
        "register": "standard",
        "tags": ["honnêteté", "transparence", "franchise"],
        "region": "it",
        "source": TRECCANI_BASE + "carta/",
    },
    {
        "id": "avere-il-cuore-in-gola",
        "expression": "Avere il cuore in gola",
        "meaning": "Être très anxieux, avoir le cœur qui bat si fort qu'il semble remonter dans la gorge.",
        "origin": "Expression corporelle intense — le cœur qui monte, signe de peur ou d'excitation extrême.",
        "example": "Mentre aspettavo i risultati avevo il cuore in gola.",
        "register": "standard",
        "tags": ["anxiété", "peur", "émotion"],
        "region": "it",
        "source": TRECCANI_BASE + "cuore/",
    },
    {
        "id": "fare-due-chiacchiere",
        "expression": "Fare due chiacchiere",
        "meaning": "Avoir une conversation légère et décontractée, bavarder, échanger quelques mots sans formalité.",
        "origin": "Expression basée sur « chiacchiera » (bavardage) — faire « deux » bavardages, le chiffre minimum pour un échange.",
        "example": "Vieni, facciamo due chiacchiere davanti a un caffè.",
        "register": "informal",
        "tags": ["conversation", "amitié", "détente"],
        "region": "it",
        "source": TRECCANI_BASE + "chiacchiera/",
    },
    {
        "id": "in-un-batter-docchio",
        "expression": "In un batter d'occhio",
        "meaning": "Très rapidement, en un instant, en un clin d'œil.",
        "origin": "Expression basée sur le battement de paupière — le mouvement le plus rapide du corps humain — comme mesure de la vitesse extrême.",
        "example": "Ha finito il lavoro in un batter d'occhio.",
        "register": "standard",
        "tags": ["vitesse", "rapidité", "instant"],
        "region": "it",
        "source": TRECCANI_BASE + "occhio/",
    },
    {
        "id": "avere-la-coda-di-paglia",
        "expression": "Avere la coda di paglia",
        "meaning": "Avoir mauvaise conscience et se sentir visé par des remarques générales qui ne vous étaient pas adressées.",
        "origin": "La coda di paglia (queue de paille) prend feu facilement — métaphore de la culpabilité qui rend susceptible et inflammable.",
        "example": "Ha preso la critica per sé — ha la coda di paglia.",
        "register": "informal",
        "tags": ["culpabilité", "susceptibilité", "conscience"],
        "region": "it",
        "source": TRECCANI_BASE + "paglia/",
    },
    {
        "id": "lasciare-il-segno",
        "expression": "Lasciare il segno",
        "meaning": "Marquer durablement quelque chose ou quelqu'un, laisser une empreinte mémorable.",
        "origin": "Expression concrète — laisser une marque physique transposée au plan symbolique : laisser une trace dans les mémoires ou dans l'histoire.",
        "example": "Questo insegnante ha davvero lasciato il segno nella mia vita.",
        "register": "standard",
        "tags": ["impact", "mémoire", "héritage"],
        "region": "it",
        "source": TRECCANI_BASE + "segno/",
    },
    {
        "id": "prendere-in-giro",
        "expression": "Prendere in giro",
        "meaning": "Se moquer de quelqu'un, le ridiculiser, le faire tourner en dérision.",
        "origin": "Expression dont l'image évoque de « faire tourner en rond » quelqu'un — le perdre, le berner.",
        "example": "Smettila di prendermi in giro davanti a tutti!",
        "register": "informal",
        "tags": ["moquerie", "humour", "dérision"],
        "region": "it",
        "source": TRECCANI_BASE + "giro/",
    },
    {
        "id": "avere-le-mani-bucate",
        "expression": "Avere le mani bucate",
        "meaning": "Être incapable de garder son argent, dépenser sans compter, laisser filer ses revenus.",
        "origin": "Image concrète — les mains trouées (bucate) laissent tout s'échapper, comme un sac percé laisse passer le grain.",
        "example": "Non riesce a risparmiare niente — ha le mani bucate.",
        "register": "informal",
        "tags": ["argent", "dépenses", "dilapidation"],
        "region": "it",
        "source": TRECCANI_BASE + "mano/",
    },
    {
        "id": "dormire-sugli-allori",
        "expression": "Dormire sugli allori",
        "meaning": "Se reposer sur ses lauriers, profiter de ses succès passés sans chercher à progresser.",
        "origin": "Les allori (lauriers) sont le symbole antique du triomphe — dormir dessus, c'est se laisser bercer par la gloire passée au lieu de continuer à agir.",
        "example": "Ha vinto un premio l'anno scorso e ora dorme sugli allori.",
        "register": "standard",
        "tags": ["paresse", "gloire", "complaisance"],
        "region": "it",
        "source": TRECCANI_BASE + "alloro/",
    },
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    added = 0
    skipped = 0

    for expr in EXPRESSIONS:
        try:
            cur.execute(
                """
                INSERT INTO expressions
                    (id, expression, meaning, origin, example, register, tags, region, source)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    expr["id"],
                    expr["expression"],
                    expr["meaning"],
                    expr.get("origin", ""),
                    expr.get("example", ""),
                    expr.get("register", "standard"),
                    json.dumps(expr.get("tags", []), ensure_ascii=False),
                    expr.get("region", "it"),
                    expr.get("source", ""),
                ),
            )
            added += 1
        except sqlite3.IntegrityError:
            skipped += 1

    conn.commit()
    conn.close()

    print(f"Italien : {added} expressions ajoutées, {skipped} ignorées (déjà présentes).")
    print(f"Total ajouté : {added}")


if __name__ == "__main__":
    main()
