"""
Ajoute ~100 expressions espagnoles dans expressions.db.
Usage : python3 scripts/add_spanish_expressions.py
"""
import sqlite3, json
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "expressions.db"

EXPRESSIONS = [
    # ── Refranes (proverbes) ──────────────────────────────────────────
    {
        "id": "a-mal-tiempo-buena-cara",
        "expression": "A mal tiempo, buena cara",
        "meaning": "Frente a las adversidades, hay que mantener una actitud positiva y no dejarse abatir.",
        "origin": "Refrán popular de origen incierto, extendido en toda la cultura hispanohablante desde el siglo XVII.",
        "example": "Perdí el trabajo, pero a mal tiempo, buena cara — ya encontraré algo mejor.",
        "register": "standard",
        "tags": ["actitud", "optimismo", "dificultad"],
    },
    {
        "id": "no-hay-mal-que-por-bien-no-venga",
        "expression": "No hay mal que por bien no venga",
        "meaning": "Toda desgracia trae consigo algo positivo; equivalente a 'no hay mal que por bien no venga'.",
        "origin": "Refrán clásico recogido ya en el Quijote de Cervantes (1605).",
        "example": "Perdí el vuelo, pero así conocí a mi pareja — no hay mal que por bien no venga.",
        "register": "standard",
        "tags": ["optimismo", "suerte", "esperanza"],
    },
    {
        "id": "camaron-que-se-duerme-se-lo-lleva-la-corriente",
        "expression": "Camarón que se duerme, se lo lleva la corriente",
        "meaning": "Quien no está atento y activo pierde sus oportunidades o queda a merced de los demás.",
        "origin": "Refrán popular latinoamericano basado en la imagen del camarón arrastrado por el río si no nada activamente.",
        "example": "Si no actualizas tu CV, otro te quitará el puesto — camarón que se duerme, se lo lleva la corriente.",
        "register": "standard",
        "tags": ["trabajo", "pereza", "oportunidad"],
    },
    {
        "id": "el-que-madruga-dios-le-ayuda",
        "expression": "Al que madruga, Dios le ayuda",
        "meaning": "Levantarse temprano y empezar pronto el trabajo trae buenos resultados.",
        "origin": "Recogido en el Libro de Buen Amor del Arcipreste de Hita (siglo XIV), uno de los refranes más antiguos del español.",
        "example": "Llegué el primero a la fila y conseguí el mejor sitio — al que madruga, Dios le ayuda.",
        "register": "standard",
        "tags": ["trabajo", "tiempo", "esfuerzo"],
    },
    {
        "id": "a-caballo-regalado-no-le-mires-el-diente",
        "expression": "A caballo regalado no le mires el diente",
        "meaning": "No hay que criticar ni poner condiciones a lo que nos dan gratuitamente.",
        "origin": "Los dientes del caballo revelan su edad y salud; examinarlos era forma de tasar su valor. El refrán aparece ya en el siglo XV.",
        "example": "La habitación del hotel era pequeña, pero era gratis — a caballo regalado no le mires el diente.",
        "register": "standard",
        "tags": ["gratitud", "regalo", "generosidad"],
    },
    {
        "id": "mas-vale-tarde-que-nunca",
        "expression": "Más vale tarde que nunca",
        "meaning": "Es preferible hacer algo con retraso que no hacerlo en absoluto.",
        "origin": "Adaptación del latín 'Potius sero quam numquam' (Tito Livio). Común en todas las lenguas romances.",
        "example": "Empecé a aprender guitarra a los 40 años, pero más vale tarde que nunca.",
        "register": "standard",
        "tags": ["tiempo", "motivación", "paciencia"],
    },
    {
        "id": "en-boca-cerrada-no-entran-moscas",
        "expression": "En boca cerrada no entran moscas",
        "meaning": "El silencio evita problemas; es mejor callar que hablar sin pensar.",
        "origin": "Refrán popular recogido desde el siglo XVI. La imagen de la mosca simboliza el problema que entra cuando uno habla de más.",
        "example": "No opines sobre la pelea de tus jefes — en boca cerrada no entran moscas.",
        "register": "standard",
        "tags": ["silencio", "prudencia", "animales"],
    },
    {
        "id": "dime-con-quien-andas",
        "expression": "Dime con quién andas y te diré quién eres",
        "meaning": "Las personas que frecuentamos reflejan y moldean nuestro carácter y reputación.",
        "origin": "Refrán clásico recogido en el Quijote. Equivalente al latín 'Noscitur a sociis'.",
        "example": "Desde que sale con ese grupo, ha cambiado mucho — dime con quién andas y te diré quién eres.",
        "register": "standard",
        "tags": ["amistad", "influencia", "carácter"],
    },
    {
        "id": "ojos-que-no-ven-corazon-que-no-siente",
        "expression": "Ojos que no ven, corazón que no siente",
        "meaning": "Lo que uno desconoce no le afecta emocionalmente; la ignorancia puede ser un alivio.",
        "origin": "Refrán popular cuya primera documentación data del siglo XVI. Equivalente al inglés 'out of sight, out of mind'.",
        "example": "No le cuentes lo que pasó en la fiesta — ojos que no ven, corazón que no siente.",
        "register": "standard",
        "tags": ["ignorancia", "dolor", "secreto"],
    },
    {
        "id": "mas-vale-pajaro-en-mano",
        "expression": "Más vale pájaro en mano que cien volando",
        "meaning": "Es mejor conformarse con lo que se tiene seguro que arriesgarlo por algo mayor e incierto.",
        "origin": "Refrán documentado en español desde el siglo XIII. Tiene equivalentes en latín, árabe y casi todas las lenguas europeas.",
        "example": "Me ofrecen el 80 % ahora o el 100 % en seis meses — más vale pájaro en mano que cien volando.",
        "register": "standard",
        "tags": ["prudencia", "certeza", "animales", "pájaro"],
    },
    {
        "id": "de-tal-palo-tal-astilla",
        "expression": "De tal palo, tal astilla",
        "meaning": "Los hijos suelen parecerse a sus padres en carácter o defectos.",
        "origin": "Refrán clásico documentado desde el siglo XV; la imagen de la madera transmite la idea de que la astilla tiene la naturaleza del tronco.",
        "example": "Igual que su padre, siempre llega tarde — de tal palo, tal astilla.",
        "register": "standard",
        "tags": ["familia", "herencia", "carácter"],
    },
    {
        "id": "el-habito-no-hace-al-monje",
        "expression": "El hábito no hace al monje",
        "meaning": "La apariencia exterior no define la verdadera naturaleza o valía de una persona.",
        "origin": "Adaptación española del latín medieval 'Cucullus non facit monachum'. El hábito es el traje del monje.",
        "example": "Viste muy elegante pero no sabe nada del tema — el hábito no hace al monje.",
        "register": "standard",
        "tags": ["apariencia", "carácter", "engaño"],
    },
    {
        "id": "no-todo-lo-que-brilla-es-oro",
        "expression": "No todo lo que brilla es oro",
        "meaning": "Las apariencias pueden engañar; algo atractivo a primera vista puede no tener valor real.",
        "origin": "Proviene de Shakespeare ('All that glitters is not gold', El mercader de Venecia, 1596), pero el concepto es anterior en la cultura española.",
        "example": "La oferta parece increíble, pero no todo lo que brilla es oro — lee bien la letra pequeña.",
        "register": "standard",
        "tags": ["apariencia", "engaño", "prudencia"],
    },
    {
        "id": "perro-ladrador-poco-mordedor",
        "expression": "Perro ladrador, poco mordedor",
        "meaning": "Quien más amenaza o protesta suele ser el que menos actúa; las bravatas no siempre tienen consecuencias.",
        "origin": "Refrán documentado desde el siglo XV. El perro que ladra constantemente suele no atacar.",
        "example": "Siempre amenaza con quejarse al director, pero nunca lo hace — perro ladrador, poco mordedor.",
        "register": "standard",
        "tags": ["amenaza", "cobardía", "animales", "perro"],
    },
    {
        "id": "el-tiempo-todo-lo-cura",
        "expression": "El tiempo todo lo cura",
        "meaning": "Con el paso del tiempo, las heridas emocionales y los problemas se alivian o desaparecen.",
        "origin": "Sentencia atribuida a Hipócrates en versión médica; adoptada como refrán popular en todas las culturas mediterráneas.",
        "example": "Estás muy triste ahora, pero el tiempo todo lo cura — ya lo verás.",
        "register": "standard",
        "tags": ["tiempo", "dolor", "esperanza", "curación"],
    },
    {
        "id": "nadie-es-profeta-en-su-tierra",
        "expression": "Nadie es profeta en su tierra",
        "meaning": "Las personas no suelen ser reconocidas o valoradas en su propio entorno o lugar de origen.",
        "origin": "Frase de origen bíblico (Lucas 4:24). Ha pasado a ser un refrán universal en todas las culturas.",
        "example": "En su ciudad nadie lo conoce, pero en el extranjero es famosísimo — nadie es profeta en su tierra.",
        "register": "standard",
        "tags": ["reconocimiento", "fama", "valor"],
    },
    {
        "id": "el-que-rie-ultimo-rie-mejor",
        "expression": "El que ríe último, ríe mejor",
        "meaning": "El verdadero éxito o victoria corresponde a quien triunfa al final, no al que se adelanta.",
        "origin": "Traducción del inglés 'He who laughs last, laughs longest'. Adoptado al español en el siglo XX.",
        "example": "Se burlaron de mi proyecto, pero ganó el premio — el que ríe último, ríe mejor.",
        "register": "standard",
        "tags": ["victoria", "paciencia", "alegría"],
    },
    {
        "id": "cada-oveja-con-su-pareja",
        "expression": "Cada oveja con su pareja",
        "meaning": "Cada persona debe emparejarse o asociarse con quien le corresponde o se le parece.",
        "origin": "Refrán popular basado en la imagen del pastor que agrupa las ovejas de dos en dos.",
        "example": "Son completamente diferentes — no durarán. Cada oveja con su pareja.",
        "register": "standard",
        "tags": ["amor", "compatibilidad", "animales"],
    },
    {
        "id": "lo-que-no-mata-engorda",
        "expression": "Lo que no mata, engorda",
        "meaning": "Algo que no resulta fatal puede incluso hacernos más fuertes o resistentes.",
        "origin": "Refrán popular de uso gastronómico extendido, empleado para quitar importancia a algo potencialmente dañino.",
        "example": "La leche está un poco pasada, pero lo que no mata engorda — dale otro sorbo.",
        "register": "informal",
        "tags": ["resistencia", "comida", "optimismo"],
    },
    {
        "id": "caras-vemos-corazones-no-sabemos",
        "expression": "Caras vemos, corazones no sabemos",
        "meaning": "La apariencia exterior no revela la verdadera personalidad o intenciones de las personas.",
        "origin": "Refrán popular castellano documentado desde el siglo XVI. Alerta sobre la imposibilidad de conocer a alguien solo por su rostro.",
        "example": "Parece muy amable, pero caras vemos, corazones no sabemos.",
        "register": "standard",
        "tags": ["apariencia", "engaño", "desconfianza"],
    },
    {
        "id": "mas-sabe-el-diablo-por-viejo",
        "expression": "Más sabe el diablo por viejo que por diablo",
        "meaning": "La experiencia acumulada con los años vale más que cualquier talento o astucia innata.",
        "origin": "Refrán clásico español recogido en el siglo XVII. El diablo es símbolo de astucia; su sabiduría se atribuye a la edad, no solo a su naturaleza.",
        "example": "No le subestimes — más sabe el diablo por viejo que por diablo.",
        "register": "standard",
        "tags": ["experiencia", "sabiduría", "edad"],
    },
    {
        "id": "mal-de-muchos-consuelo-de-tontos",
        "expression": "Mal de muchos, consuelo de tontos",
        "meaning": "No tiene sentido consolarse de un problema propio porque también afecta a otros; el sufrimiento compartido no lo reduce.",
        "origin": "Refrán irónico castellano que critica el hábito de buscar consuelo en la desgracia ajena.",
        "example": "— Al menos no soy el único en haber suspendido. — Eso es mal de muchos, consuelo de tontos.",
        "register": "standard",
        "tags": ["consuelo", "problemas", "ironía"],
    },
    {
        "id": "en-casa-del-herrero-cuchillo-de-palo",
        "expression": "En casa del herrero, cuchillo de palo",
        "meaning": "A menudo los expertos en algo descuidan ese mismo aspecto en su propia vida.",
        "origin": "Refrán documentado desde el siglo XVI. El herrero que forja hierro todo el día no se hace un cuchillo decente para su cocina.",
        "example": "El médico fuma una cajetilla al día — en casa del herrero, cuchillo de palo.",
        "register": "standard",
        "tags": ["ironía", "paradoja", "trabajo"],
    },
    {
        "id": "a-buen-hambre-no-hay-pan-duro",
        "expression": "A buen hambre no hay pan duro",
        "meaning": "Cuando se tiene verdadera necesidad, cualquier cosa resulta suficiente y bien recibida.",
        "origin": "Refrán popular de origen latino ('Optimum condimentum fames'), universalmente extendido.",
        "example": "Después de seis horas de excursión, el bocadillo seco estaba delicioso — a buen hambre no hay pan duro.",
        "register": "standard",
        "tags": ["comida", "necesidad", "gratitud"],
    },
    {
        "id": "visteme-despacio-que-tengo-prisa",
        "expression": "Vísteme despacio, que tengo prisa",
        "meaning": "Cuando hay urgencia, hay que actuar con calma y precisión para no cometer errores que hagan perder más tiempo.",
        "origin": "Frase atribuida a Napoleón Bonaparte. Recogida como refrán en el habla popular española.",
        "example": "No corras al escribir el código — vísteme despacio, que tengo prisa.",
        "register": "standard",
        "tags": ["paciencia", "trabajo", "calma", "tiempo"],
    },
    {
        "id": "no-hay-dos-sin-tres",
        "expression": "No hay dos sin tres",
        "meaning": "Cuando algo ocurre dos veces, es probable que ocurra una tercera vez también.",
        "origin": "Refrán popular basado en la superstición popular sobre los números; el tres simboliza la repetición confirmada.",
        "example": "Ya he ganado dos sorteos este año — no hay dos sin tres.",
        "register": "informal",
        "tags": ["suerte", "repetición", "patrón"],
    },
    {
        "id": "mas-vale-solo-que-mal-acompanado",
        "expression": "Más vale solo que mal acompañado",
        "meaning": "Es preferible la soledad a estar con personas que nos perjudican o hacen daño.",
        "origin": "Refrán documentado desde el siglo XIV. El concepto aparece en escritores clásicos latinos como Cicerón.",
        "example": "Rompí con ese grupo de amigos tóxicos — más vale solo que mal acompañado.",
        "register": "standard",
        "tags": ["amistad", "soledad", "independencia"],
    },
    {
        "id": "a-palabras-necias-oidos-sordos",
        "expression": "A palabras necias, oídos sordos",
        "meaning": "Hay que ignorar los comentarios estúpidos, insultantes o hirientes sin darles importancia.",
        "origin": "Refrán popular recogido desde el siglo XVI. Aconseja la indiferencia como mejor respuesta a la estupidez.",
        "example": "Se puso a insultarme, pero yo seguí andando — a palabras necias, oídos sordos.",
        "register": "standard",
        "tags": ["insultos", "indiferencia", "silencio", "prudencia"],
    },
    {
        "id": "cuando-el-rio-suena-agua-lleva",
        "expression": "Cuando el río suena, agua lleva",
        "meaning": "Donde hay rumores, algo de verdad suele haber; el humo indica que hay fuego.",
        "origin": "Refrán popular recogido en el Refranero español (siglo XVI). Imagen del sonido del río como señal de corriente.",
        "example": "Dicen que van a cerrar la empresa — cuando el río suena, agua lleva.",
        "register": "standard",
        "tags": ["rumores", "verdad", "desconfianza"],
    },
    {
        "id": "no-hay-rosa-sin-espinas",
        "expression": "No hay rosa sin espinas",
        "meaning": "Nada bueno viene sin dificultades o aspectos negativos; todo tiene su precio.",
        "origin": "Refrán universal documentado en latín, árabe y castellano desde la Edad Media.",
        "example": "El trabajo es fantástico, pero el jefe es insoportable — no hay rosa sin espinas.",
        "register": "standard",
        "tags": ["dificultad", "esperanza", "equilibrio"],
    },
    {
        "id": "no-hay-que-vender-la-piel-del-oso",
        "expression": "No hay que vender la piel del oso antes de cazarlo",
        "meaning": "No hay que contar con algo que aún no se tiene; no adelantarse antes de que algo sea seguro.",
        "origin": "Refrán documentado desde Cervantes. La imagen del cazador que vende la piel antes de atrapar al oso ilustra la imprudencia.",
        "example": "No gastes ese dinero — no hay que vender la piel del oso antes de cazarlo.",
        "register": "standard",
        "tags": ["prudencia", "imprudencia", "animales", "certeza"],
    },

    # ── Expresiones con partes del cuerpo ────────────────────────────
    {
        "id": "meter-la-pata",
        "expression": "Meter la pata",
        "meaning": "Cometer un error o decir algo inapropiado que causa un problema o situación embarazosa.",
        "origin": "Imagen del animal que introduce la pata en un agujero o trampa. Usada desde el siglo XIX en el habla coloquial.",
        "example": "Mencioné su exnovio sin saber que habían roto — metí la pata.",
        "register": "informal",
        "tags": ["error", "torpeza", "vergüenza"],
    },
    {
        "id": "costar-un-ojo-de-la-cara",
        "expression": "Costar un ojo de la cara",
        "meaning": "Ser extremadamente caro, tener un precio exorbitante.",
        "origin": "El ojo es el órgano más preciado del cuerpo; su precio hiperbólico expresa el mayor valor imaginable.",
        "example": "Las entradas al concierto cuestan un ojo de la cara — ¡cien euros por persona!",
        "register": "informal",
        "tags": ["dinero", "precio", "caro"],
    },
    {
        "id": "no-tener-pelos-en-la-lengua",
        "expression": "No tener pelos en la lengua",
        "meaning": "Decir las cosas directamente y sin rodeos, sin temor a herir o molestar.",
        "origin": "Imagen de que los pelos en la lengua dificultarían hablar con fluidez; sin ellos, uno habla sin obstáculos ni filtros.",
        "example": "Le dijo a su jefe lo que pensaba sin dudar — no tiene pelos en la lengua.",
        "register": "informal",
        "tags": ["franqueza", "honestidad", "hablar"],
    },
    {
        "id": "hablar-por-los-codos",
        "expression": "Hablar por los codos",
        "meaning": "Hablar muchísimo, sin parar, de forma excesiva.",
        "origin": "Imagen humorística de alguien que habla tanto que parece hacerlo hasta por los codos, no solo por la boca.",
        "example": "Mi vecina habla por los codos — lleva dos horas contándome su día.",
        "register": "informal",
        "tags": ["hablar", "locuacidad", "exageración"],
    },
    {
        "id": "ponerse-como-un-tomate",
        "expression": "Ponerse como un tomate",
        "meaning": "Ruborizarse intensamente por vergüenza, emoción o timidez.",
        "origin": "El tomate maduro es rojo brillante; su color es la referencia popular para describir el enrojecimiento facial.",
        "example": "Cuando lo presentaron en público, se puso como un tomate.",
        "register": "informal",
        "tags": ["vergüenza", "timidez", "emociones"],
    },
    {
        "id": "quedarse-en-blanco",
        "expression": "Quedarse en blanco",
        "meaning": "Tener la mente vacía de repente, sin poder recordar nada o pensar con claridad.",
        "origin": "Imagen de una pizarra o página en blanco — la mente queda sin contenido. Uso generalizado desde el siglo XX.",
        "example": "En el examen oral me quedé en blanco y no pude decir ni una palabra.",
        "register": "informal",
        "tags": ["olvido", "bloqueo", "estrés"],
    },
    {
        "id": "hacer-de-tripas-corazon",
        "expression": "Hacer de tripas corazón",
        "meaning": "Armarse de valor y hacer algo difícil o desagradable a pesar del miedo o la repulsa.",
        "origin": "Las tripas representaban el miedo (el 'nudo en el estómago'); convertirlas en corazón simboliza transformar el miedo en valentía.",
        "example": "Hice de tripas corazón y pedí disculpas aunque no me apetecía nada.",
        "register": "standard",
        "tags": ["valentía", "esfuerzo", "miedo", "superación"],
    },
    {
        "id": "tener-mala-leche",
        "expression": "Tener mala leche",
        "meaning": "Tener mal carácter, ser de mal humor o actuar con mala intención.",
        "origin": "En la cultura popular, la 'mala leche' hace referencia al humor ácido o agrio, como leche en mal estado.",
        "example": "Cuidado con ese jefe — tiene muy mala leche cuando algo no sale bien.",
        "register": "informal",
        "tags": ["malhumor", "carácter", "agresividad"],
    },
    {
        "id": "estar-en-las-nubes",
        "expression": "Estar en las nubes",
        "meaning": "Estar distraído, pensando en otra cosa, sin atender a lo que ocurre alrededor.",
        "origin": "Imagen poética de alguien cuya mente vuela tan alto que pierde contacto con la realidad.",
        "example": "Le pregunté tres veces y no respondió — estaba completamente en las nubes.",
        "register": "informal",
        "tags": ["distracción", "soñar", "atención"],
    },
    {
        "id": "pagar-los-platos-rotos",
        "expression": "Pagar los platos rotos",
        "meaning": "Sufrir las consecuencias de algo que ha hecho otra persona; ser el chivo expiatorio.",
        "origin": "Imagen literal: en una pelea doméstica, alguien rompe platos y otro paga los daños. Uso figurado desde el siglo XIX.",
        "example": "El proyecto fracasó por culpa del director, pero pagó los platos rotos el becario.",
        "register": "informal",
        "tags": ["culpa", "injusticia", "consecuencias"],
    },
    {
        "id": "no-dar-el-brazo-a-torcer",
        "expression": "No dar el brazo a torcer",
        "meaning": "Mantenerse firme en la propia posición o decisión, sin ceder ante presiones.",
        "origin": "Imagen de alguien que no permite que le retuerzan el brazo, ni en sentido literal ni figurado.",
        "example": "Le propusieron tres veces cambiar el diseño y no dio el brazo a torcer.",
        "register": "standard",
        "tags": ["terquedad", "firmeza", "determinación"],
    },
    {
        "id": "tener-los-pies-en-la-tierra",
        "expression": "Tener los pies en la tierra",
        "meaning": "Ser realista y práctico, no dejarse llevar por ilusiones o fantasías.",
        "origin": "Contraste entre los pies (anclados al suelo, a la realidad) y la cabeza que puede flotar en el aire o las nubes.",
        "example": "Es un gran soñador, pero por suerte tiene los pies en la tierra cuando se trata de dinero.",
        "register": "standard",
        "tags": ["realismo", "prudencia", "sensatez"],
    },
    {
        "id": "tener-agallas",
        "expression": "Tener agallas",
        "meaning": "Tener valentía, atrevimiento y determinación para afrontar situaciones difíciles.",
        "origin": "Las agallas son las branquias del pez que le permiten respirar bajo el agua. Por extensión, simbolizan la capacidad de aguantar presión.",
        "example": "Hay que tener agallas para dejar un trabajo estable y montar tu propia empresa.",
        "register": "informal",
        "tags": ["valentía", "atrevimiento", "determinación"],
    },
    {
        "id": "coger-el-toro-por-los-cuernos",
        "expression": "Coger el toro por los cuernos",
        "meaning": "Enfrentarse directamente a un problema o situación difícil sin evitarlo ni posponerlo.",
        "origin": "Imagen taurina: agarrar al toro por los cuernos es el acto más arriesgado y directo del toreo.",
        "example": "En vez de ignorar el conflicto, decidió coger el toro por los cuernos y hablar con las dos partes.",
        "register": "standard",
        "tags": ["valentía", "decisión", "problema", "animales"],
    },
    {
        "id": "poner-el-dedo-en-la-llaga",
        "expression": "Poner el dedo en la llaga",
        "meaning": "Señalar exactamente el punto débil o el problema más doloroso de una situación.",
        "origin": "Referencia bíblica al apóstol Tomás, que quiso meter el dedo en la herida de Cristo para creer en su resurrección.",
        "example": "Cuando mencionó la falta de comunicación, puso el dedo en la llaga — ese era el problema real.",
        "register": "standard",
        "tags": ["problema", "verdad", "honestidad"],
    },
    {
        "id": "no-tener-ni-pies-ni-cabeza",
        "expression": "No tener ni pies ni cabeza",
        "meaning": "Carecer de coherencia o sentido; ser completamente ilógico o absurdo.",
        "origin": "Imagen del ser sin extremidades ni cabeza, por tanto incapaz de moverse o pensar: inútil e incomprensible.",
        "example": "Su plan de negocio no tiene ni pies ni cabeza — es imposible de entender.",
        "register": "informal",
        "tags": ["confusión", "incoherencia", "absurdo"],
    },
    {
        "id": "estar-hasta-las-narices",
        "expression": "Estar hasta las narices",
        "meaning": "Estar completamente harto, agotado o frustrado de algo o alguien.",
        "origin": "La nariz como límite extremo de aguante: cuando el agua llega hasta las narices, ya no se puede respirar — uno está al límite.",
        "example": "Estoy hasta las narices de que siempre llegues tarde — esto tiene que cambiar.",
        "register": "informal",
        "tags": ["hartazgo", "frustración", "límite"],
    },
    {
        "id": "no-pegar-ojo",
        "expression": "No pegar ojo",
        "meaning": "No dormir en absoluto durante una noche.",
        "origin": "'Pegar ojo' significaba cerrar los ojos para dormir; su negación indica la imposibilidad de conciliar el sueño.",
        "example": "Con el ruido de la obra no pegué ojo en toda la noche.",
        "register": "informal",
        "tags": ["sueño", "cansancio", "insomnio"],
    },
    {
        "id": "romperse-la-cabeza",
        "expression": "Romperse la cabeza",
        "meaning": "Pensar intensamente en algo durante mucho tiempo para encontrar una solución.",
        "origin": "Imagen hiperbólica del esfuerzo mental tan intenso que parece capaz de romper la cabeza.",
        "example": "Llevo horas rompiéndome la cabeza con este problema de matemáticas.",
        "register": "informal",
        "tags": ["esfuerzo", "pensamiento", "solución"],
    },
    {
        "id": "tener-buena-mano",
        "expression": "Tener buena mano",
        "meaning": "Tener habilidad natural o destreza especial para algo concreto.",
        "origin": "La mano como instrumento de habilidad manual; tener 'buena mano' sugiere que la mano trabaja bien sola.",
        "example": "Tiene muy buena mano para los pasteles — todo lo que hace queda delicioso.",
        "register": "informal",
        "tags": ["habilidad", "talento", "destreza"],
    },

    # ── Expresiones con animales ──────────────────────────────────────
    {
        "id": "ser-un-lobo-con-piel-de-cordero",
        "expression": "Ser un lobo con piel de cordero",
        "meaning": "Aparentar ser inofensivo o bondadoso cuando en realidad se tiene malas intenciones.",
        "origin": "Imagen bíblica (Mateo 7:15): 'Guardaos de los falsos profetas, que vienen a vosotros con vestidos de ovejas, pero por dentro son lobos rapaces'.",
        "example": "Parecía muy amable en las reuniones, pero era un lobo con piel de cordero — traicionó a todos.",
        "register": "standard",
        "tags": ["engaño", "hipocresía", "animales", "lobo"],
    },
    {
        "id": "a-otro-perro-con-ese-hueso",
        "expression": "A otro perro con ese hueso",
        "meaning": "Expresión de incredulidad ante una excusa o historia que uno no se cree; rechazo de algo que se considera falso.",
        "origin": "El hueso es algo que se le da al perro para entretenerlo; ofrecer ese engaño a 'otro' indica que uno no es tan fácil de engañar.",
        "example": "¿Que el tren llegó tarde? A otro perro con ese hueso — siempre tienes una excusa.",
        "register": "informal",
        "tags": ["incredulidad", "engaño", "animales", "perro"],
    },
    {
        "id": "estar-como-pez-en-el-agua",
        "expression": "Estar como pez en el agua",
        "meaning": "Sentirse completamente cómodo, en su elemento, en una situación determinada.",
        "origin": "El pez en el agua como imagen máxima de comodidad y adaptación al entorno propio.",
        "example": "Desde que empezó a trabajar en diseño, está como pez en el agua.",
        "register": "informal",
        "tags": ["comodidad", "adaptación", "animales", "pez"],
    },
    {
        "id": "dar-gato-por-liebre",
        "expression": "Dar gato por liebre",
        "meaning": "Engañar a alguien vendiéndole o dándole algo de inferior calidad haciéndolo pasar por algo mejor.",
        "origin": "En los mercados medievales se vendía carne de gato haciéndola pasar por liebre, más valiosa y sabrosa.",
        "example": "Le vendieron un coche de segunda mano como si fuera nuevo — le dieron gato por liebre.",
        "register": "informal",
        "tags": ["engaño", "fraude", "animales"],
    },
    {
        "id": "buscar-tres-pies-al-gato",
        "expression": "Buscar tres pies al gato",
        "meaning": "Complicar algo innecesariamente, buscar problemas donde no los hay, o darle vueltas a algo simple.",
        "origin": "El gato tiene cuatro patas; buscar tres es una empresa absurda que solo crea confusión.",
        "example": "El contrato era sencillo y empezó a buscar tres pies al gato — ahora nadie entiende nada.",
        "register": "informal",
        "tags": ["complicar", "problemas", "animales"],
    },
    {
        "id": "matar-dos-pajaros-de-un-tiro",
        "expression": "Matar dos pájaros de un tiro",
        "meaning": "Resolver dos problemas o conseguir dos objetivos con una sola acción.",
        "origin": "Imagen de caza: un solo disparo que derriba dos pájaros a la vez, máxima eficiencia.",
        "example": "Voy al médico y de paso compro en el mercado — mato dos pájaros de un tiro.",
        "register": "informal",
        "tags": ["eficiencia", "solución", "animales", "pájaro"],
    },
    {
        "id": "tener-mariposas-en-el-estomago",
        "expression": "Tener mariposas en el estómago",
        "meaning": "Sentir nerviosismo y emoción, especialmente por algo romántico o por anticipación de algo importante.",
        "origin": "Imagen física de la sensación de 'aleteo' en el estómago provocada por la adrenalina en situaciones de excitación o nerviosismo.",
        "example": "Cada vez que la veo siento mariposas en el estómago.",
        "register": "informal",
        "tags": ["amor", "nervios", "emociones", "animales"],
    },
    {
        "id": "ser-un-raton-de-biblioteca",
        "expression": "Ser un ratón de biblioteca",
        "meaning": "Ser una persona que pasa mucho tiempo leyendo y estudiando, muy aficionada a los libros.",
        "origin": "Imagen del ratón que vive entre libros y los roe; a diferencia del ratón real, el 'ratón de biblioteca' los 'devora' con la lectura.",
        "example": "Desde niño fue un ratón de biblioteca — siempre tenía un libro entre las manos.",
        "register": "informal",
        "tags": ["lectura", "estudios", "animales"],
    },
    {
        "id": "cuando-las-ranas-crien-pelo",
        "expression": "Cuando las ranas críen pelo",
        "meaning": "Nunca; algo que se considera imposible que ocurra.",
        "origin": "Las ranas no tienen pelo; el refrán usa un imposible biológico para expresar la imposibilidad de algo.",
        "example": "¿Que me va a pedir perdón? Sí, cuando las ranas críen pelo.",
        "register": "informal",
        "tags": ["imposible", "nunca", "animales"],
    },
    {
        "id": "ser-la-oveja-negra",
        "expression": "Ser la oveja negra",
        "meaning": "Ser el miembro de un grupo (especialmente una familia) que se aparta de las normas o causa vergüenza.",
        "origin": "En los rebaños, la oveja negra era indeseable porque su lana no tenía valor comercial; simbolizaba lo diferente y problemático.",
        "example": "De los cinco hermanos, él es la oveja negra — siempre metido en líos.",
        "register": "informal",
        "tags": ["familia", "diferente", "animales"],
    },
    {
        "id": "ser-un-gallina",
        "expression": "Ser un gallina",
        "meaning": "Ser cobarde, miedoso, carecer de valentía.",
        "origin": "La gallina es símbolo de cobardía en el imaginario popular por su tendencia a huir al menor susto.",
        "example": "No se atrevió a tirarse en paracaídas — es un gallina.",
        "register": "informal",
        "tags": ["cobardía", "miedo", "animales"],
    },
    {
        "id": "el-gato-escaldado-del-agua-fria-huye",
        "expression": "El gato escaldado, del agua fría huye",
        "meaning": "Quien ha sufrido una mala experiencia se vuelve excesivamente precavido y desconfía incluso donde no hay peligro.",
        "origin": "Imagen del gato que, tras quemarse con agua caliente, huye incluso del agua fría por precaución.",
        "example": "Desde que le estafaron, no compra nada por internet — el gato escaldado, del agua fría huye.",
        "register": "standard",
        "tags": ["miedo", "experiencia", "desconfianza", "animales"],
    },
    {
        "id": "a-perro-flaco-todo-son-pulgas",
        "expression": "A perro flaco, todo son pulgas",
        "meaning": "A quien ya tiene problemas, se le acumulan más desgracias; la mala suerte llama a más mala suerte.",
        "origin": "Imagen del perro débil y desnutrido que, por su estado, atrae más parásitos que uno sano.",
        "example": "Se le averió el coche justo cuando había perdido el trabajo — a perro flaco, todo son pulgas.",
        "register": "standard",
        "tags": ["mala suerte", "problemas", "animales", "perro"],
    },
    {
        "id": "llevarse-el-gato-al-agua",
        "expression": "Llevarse el gato al agua",
        "meaning": "Salir victorioso de una situación difícil o disputada; conseguir lo que se quería a pesar de los obstáculos.",
        "origin": "Origen incierto; quizás relacionado con la dificultad de llevar a un gato (que odia el agua) hasta ella.",
        "example": "Había cuatro candidatos fuertes, pero ella se llevó el gato al agua.",
        "register": "informal",
        "tags": ["victoria", "competición", "animales"],
    },

    # ── Dinero y trabajo ──────────────────────────────────────────────
    {
        "id": "estar-a-dos-velas",
        "expression": "Estar a dos velas",
        "meaning": "Estar sin dinero, en situación de pobreza o apuro económico.",
        "origin": "Las dos velas eran la iluminación mínima de los más pobres; tener solo eso indicaba extrema escasez.",
        "example": "Este mes estamos a dos velas — no llega para el alquiler.",
        "register": "informal",
        "tags": ["dinero", "pobreza", "economía"],
    },
    {
        "id": "arrimar-el-hombro",
        "expression": "Arrimar el hombro",
        "meaning": "Colaborar activamente, poner esfuerzo y trabajo para ayudar en una tarea común.",
        "origin": "Imagen física de apoyar el hombro para empujar algo pesado en equipo; metáfora de la cooperación.",
        "example": "En los momentos difíciles todos arrimaron el hombro y sacaron el proyecto adelante.",
        "register": "standard",
        "tags": ["trabajo", "colaboración", "esfuerzo"],
    },
    {
        "id": "ponerse-las-pilas",
        "expression": "Ponerse las pilas",
        "meaning": "Empezar a esforzarse más, activarse o ponerse al día cuando se ha estado perezoso o despistado.",
        "origin": "Metáfora moderna del aparato que funciona mejor al ponerle pilas nuevas; popularizada en el siglo XX.",
        "example": "Solo quedan dos semanas para el examen — ya es hora de ponerse las pilas.",
        "register": "informal",
        "tags": ["motivación", "esfuerzo", "trabajo", "pereza"],
    },
    {
        "id": "ser-un-hacha",
        "expression": "Ser un hacha",
        "meaning": "Ser muy hábil, competente o brillante en algo.",
        "origin": "El hacha es la herramienta cortante por excelencia; alguien que 'corta' como ella domina su campo.",
        "example": "Para las matemáticas es un hacha — resuelve los problemas en segundos.",
        "register": "informal",
        "tags": ["habilidad", "talento", "elogio"],
    },
    {
        "id": "echar-agua-al-mar",
        "expression": "Echar agua al mar",
        "meaning": "Hacer algo completamente inútil porque aporta algo insignificante a lo que ya es ilimitado o suficiente.",
        "origin": "Imagen de la inutilidad de añadir agua al océano; lo que se aporta es irrelevante en comparación con lo que ya hay.",
        "example": "Criticar esa empresa en un tweet es echar agua al mar — nadie lo va a ver.",
        "register": "informal",
        "tags": ["inutilidad", "esfuerzo", "agua"],
    },
    {
        "id": "salir-el-tiro-por-la-culata",
        "expression": "Salirse el tiro por la culata",
        "meaning": "Que algo resulte al contrario de lo que se esperaba; que un plan cause el efecto opuesto.",
        "origin": "En un arma de fuego defectuosa, el disparo puede salir por la culata (la parte trasera) e hiriendo al tirador.",
        "example": "Intentó negociar un aumento y le ofrecieron un recorte — el tiro le salió por la culata.",
        "register": "informal",
        "tags": ["fracaso", "error", "consecuencias"],
    },
    {
        "id": "el-que-mucho-abarca-poco-aprieta",
        "expression": "El que mucho abarca, poco aprieta",
        "meaning": "Quien intenta hacer demasiadas cosas a la vez acaba haciéndolas todas mal o a medias.",
        "origin": "Refrán documentado desde el siglo XVI. 'Abarcar' es rodear con los brazos; 'apretar' es apretar el abrazo.",
        "example": "Dirige tres proyectos a la vez y ninguno avanza — el que mucho abarca, poco aprieta.",
        "register": "standard",
        "tags": ["trabajo", "ambición", "límite", "concentración"],
    },
    {
        "id": "querer-es-poder",
        "expression": "Querer es poder",
        "meaning": "Con suficiente voluntad y determinación, se puede lograr cualquier objetivo.",
        "origin": "Traducción del inglés 'Where there's a will there's a way'. Popularizado en español en el siglo XIX.",
        "example": "No digas que no puedes correr 10 km — querer es poder, solo hay que entrenarse.",
        "register": "standard",
        "tags": ["determinación", "voluntad", "motivación"],
    },
    {
        "id": "ser-pan-comido",
        "expression": "Ser pan comido",
        "meaning": "Ser algo muy fácil de hacer o conseguir, sin esfuerzo ni dificultad.",
        "origin": "El pan es el alimento más básico y fácil de comer; 'pan comido' simboliza lo que no supone ningún reto.",
        "example": "Para ella, ese examen fue pan comido — solo estudió dos horas.",
        "register": "informal",
        "tags": ["facilidad", "sencillo", "esfuerzo"],
    },
    {
        "id": "estar-hecho-polvo",
        "expression": "Estar hecho polvo",
        "meaning": "Estar extremadamente cansado, agotado o en muy mal estado físico o emocional.",
        "origin": "Imagen de algo desintegrado en polvo; si uno está así, ha llegado a su mínima expresión de energía.",
        "example": "Después del maratón estaba hecho polvo — no podía ni levantarse del sofá.",
        "register": "informal",
        "tags": ["cansancio", "agotamiento", "estado"],
    },

    # ── Verdad, engaño y comunicación ────────────────────────────────
    {
        "id": "hacer-la-vista-gorda",
        "expression": "Hacer la vista gorda",
        "meaning": "Ignorar deliberadamente algo que se sabe o se ve, fingir que no se ha notado.",
        "origin": "La vista 'gorda' o gruesa no puede ver los detalles finos; hacer la vista gorda es ver borroso a propósito.",
        "example": "El inspector hizo la vista gorda ante las irregularidades del local.",
        "register": "informal",
        "tags": ["ignorar", "permisividad", "complicidad"],
    },
    {
        "id": "tirar-de-la-manta",
        "expression": "Tirar de la manta",
        "meaning": "Revelar algo que se mantenía en secreto, especialmente algo comprometedor.",
        "origin": "Imagen de dos personas que duermen juntas y una tira de la manta, dejando al descubierto a la otra.",
        "example": "Un empleado tiró de la manta y reveló el fraude fiscal de la empresa.",
        "register": "informal",
        "tags": ["secreto", "revelación", "honestidad"],
    },
    {
        "id": "meter-baza",
        "expression": "Meter baza",
        "meaning": "Intervenir en una conversación o asunto sin que nadie lo haya pedido.",
        "origin": "'Baza' es en cartas una jugada ganada; 'meter baza' es intervenir en el juego de otros sin ser invitado.",
        "example": "Estábamos hablando los dos y él siempre tiene que meter baza.",
        "register": "informal",
        "tags": ["intervenir", "hablar", "impertinencia"],
    },
    {
        "id": "andarse-con-rodeos",
        "expression": "Andarse con rodeos",
        "meaning": "Dar vueltas alrededor de un tema sin llegar al punto principal; evitar decir algo directamente.",
        "origin": "Imagen del camino que rodea un obstáculo en lugar de ir directo; en la comunicación, evitar el punto central.",
        "example": "Deja de andarte con rodeos y dime qué es lo que realmente quieres.",
        "register": "informal",
        "tags": ["evasión", "hablar", "sinceridad"],
    },
    {
        "id": "quedarse-con-alguien",
        "expression": "Quedarse con alguien",
        "meaning": "Burlarse de alguien con engaño o hacer una broma a su costa.",
        "origin": "Expresión coloquial española; 'quedarse con' tiene el sentido de atrapar o poseer al otro en la burla.",
        "example": "¿De verdad hay una reunión a las seis? No te estarás quedando conmigo, ¿no?",
        "register": "informal",
        "tags": ["burla", "engaño", "humor"],
    },
    {
        "id": "tomar-el-pelo",
        "expression": "Tomar el pelo",
        "meaning": "Burlarse de alguien, engañarle con humor o no tomar en serio lo que dice.",
        "origin": "Imagen de manipular el pelo de alguien, hacer que baile al son propio; metáfora de la manipulación lúdica.",
        "example": "¿Me estás diciendo que ganaste la lotería? Seguro que me estás tomando el pelo.",
        "register": "informal",
        "tags": ["burla", "humor", "engaño"],
    },
    {
        "id": "hacerse-el-sueco",
        "expression": "Hacerse el sueco",
        "meaning": "Fingir no entender o no saber algo para evitar comprometerse o responder.",
        "origin": "Posiblemente de 'sueco' (sordo en lenguaje de germanía, no del país), por alteración fonética.",
        "example": "Le pregunté quién había roto el jarrón y se hizo el sueco.",
        "register": "informal",
        "tags": ["evasión", "ignorar", "disimulo"],
    },
    {
        "id": "dar-en-el-clavo",
        "expression": "Dar en el clavo",
        "meaning": "Acertar exactamente en algo, encontrar la solución o interpretación correcta.",
        "origin": "Imagen del carpintero que clava el clavo de un martillazo certero, sin desviarse.",
        "example": "Cuando dijo que el problema era la falta de comunicación, dio en el clavo.",
        "register": "informal",
        "tags": ["acierto", "solución", "intuición"],
    },
    {
        "id": "irse-por-las-ramas",
        "expression": "Irse por las ramas",
        "meaning": "Desviarse del tema principal hablando de detalles secundarios e irrelevantes.",
        "origin": "Imagen del animal que trepa por el tronco pero se pierde en las ramas pequeñas sin llegar al fruto.",
        "example": "Lleva diez minutos hablando y no ha llegado al punto — se va siempre por las ramas.",
        "register": "informal",
        "tags": ["evasión", "hablar", "concentración"],
    },
    {
        "id": "ir-al-grano",
        "expression": "Ir al grano",
        "meaning": "Hablar de manera directa y concisa, sin preámbulos ni rodeos innecesarios.",
        "origin": "Imagen de ir directamente al grano del trigo, la parte esencial y valiosa, sin perderse en la paja.",
        "example": "No hay tiempo, así que voy al grano: necesitamos más presupuesto.",
        "register": "informal",
        "tags": ["directness", "hablar", "eficiencia"],
    },
    {
        "id": "no-saber-ni-papa",
        "expression": "No saber ni papa",
        "meaning": "No saber absolutamente nada sobre un tema.",
        "origin": "En argot popular, 'papa' era una voz infantil para cualquier cosa pequeña. 'Ni papa' equivalía a 'nada de nada'.",
        "example": "Me preguntaron sobre contabilidad y no sé ni papa — tuve que improvisar.",
        "register": "informal",
        "tags": ["ignorancia", "conocimiento", "torpeza"],
    },
    {
        "id": "estar-en-el-ajo",
        "expression": "Estar en el ajo",
        "meaning": "Estar involucrado en un asunto o enterado de un secreto o plan.",
        "origin": "El ajo como símbolo del elemento fuerte y esencial de un guiso; estar 'en el ajo' es estar en el corazón del asunto.",
        "example": "Solo tres personas estaban en el ajo de la sorpresa para su cumpleaños.",
        "register": "informal",
        "tags": ["secreto", "conocimiento", "complicidad"],
    },

    # ── Situaciones y estados ─────────────────────────────────────────
    {
        "id": "estar-entre-la-espada-y-la-pared",
        "expression": "Estar entre la espada y la pared",
        "meaning": "Encontrarse en una situación sin salida, con dos alternativas igualmente malas.",
        "origin": "Imagen bélica: un guerrero acorralado con una espada apuntándole de frente y una pared detrás, sin escape posible.",
        "example": "Si acepto el trabajo pierdo a mi familia; si lo rechazo pierdo la carrera — estoy entre la espada y la pared.",
        "register": "standard",
        "tags": ["dilema", "dificultad", "sin salida"],
    },
    {
        "id": "saltar-a-la-vista",
        "expression": "Saltar a la vista",
        "meaning": "Ser algo tan evidente u obvio que no necesita explicación.",
        "origin": "Imagen de algo tan llamativo que 'salta' visualmente hacia los ojos del observador.",
        "example": "Que están enamorados salta a la vista — se miran todo el tiempo.",
        "register": "informal",
        "tags": ["evidencia", "obvio", "claridad"],
    },
    {
        "id": "estar-en-la-luna",
        "expression": "Estar en la luna",
        "meaning": "Estar muy distraído, ensimismado o ajeno a lo que ocurre alrededor.",
        "origin": "La luna como lugar remoto e inalcanzable; estar 'en la luna' es estar tan lejos mentalmente que uno no percibe lo que le rodea.",
        "example": "Le hablé tres veces y no contestó — está siempre en la luna.",
        "register": "informal",
        "tags": ["distracción", "soñar", "atención"],
    },
    {
        "id": "quedarse-a-cuadros",
        "expression": "Quedarse a cuadros",
        "meaning": "Quedarse sin palabras por sorpresa o estupefacción ante algo inesperado.",
        "origin": "Posiblemente de la expresión del rostro cuadriculado o bloqueado ante una sorpresa; también relacionado con cuadros o cuadrícula de estupefacción.",
        "example": "Cuando anunció que se casaban, todos nos quedamos a cuadros.",
        "register": "informal",
        "tags": ["sorpresa", "asombro", "reacción"],
    },
    {
        "id": "llueve-sobre-mojado",
        "expression": "Llueve sobre mojado",
        "meaning": "Se añade un problema más a los que ya existen; las desgracias se acumulan.",
        "origin": "Imagen de la lluvia que cae sobre tierra ya empapada; el agua adicional no mejora nada y puede empeorar la situación.",
        "example": "Le rechazaron la solicitud justo cuando había perdido el contrato — llueve sobre mojado.",
        "register": "standard",
        "tags": ["mala suerte", "problemas", "acumulación", "agua"],
    },
    {
        "id": "tirar-la-casa-por-la-ventana",
        "expression": "Tirar la casa por la ventana",
        "meaning": "Gastar dinero de forma espléndida o excesiva para celebrar algo o impresionar.",
        "origin": "Se dice que en la España del siglo XIX se celebraba la lotería tirando los muebles viejos por la ventana para estrenar los nuevos.",
        "example": "Para la boda tiraron la casa por la ventana — tres días de fiesta y 300 invitados.",
        "register": "informal",
        "tags": ["dinero", "generosidad", "celebración", "exceso"],
    },
    {
        "id": "ponerse-las-botas",
        "expression": "Ponerse las botas",
        "meaning": "Sacar gran provecho de algo, especialmente disfrutar de mucha comida o ganar mucho dinero.",
        "origin": "Las botas altas eran símbolo de riqueza y posición social; ponérselas significaba prosperar.",
        "example": "En el bufé libre del hotel nos pusimos las botas — comimos de todo.",
        "register": "informal",
        "tags": ["comida", "provecho", "celebración"],
    },
    {
        "id": "barriga-llena-corazon-contento",
        "expression": "Barriga llena, corazón contento",
        "meaning": "Cuando se ha comido bien y se está saciado, todo parece mejor y el ánimo mejora.",
        "origin": "Refrán popular que refleja la cultura mediterránea donde la comida es central en el bienestar y la convivencia.",
        "example": "Después de la paella familiar, nadie discutía — barriga llena, corazón contento.",
        "register": "informal",
        "tags": ["comida", "alegría", "bienestar"],
    },
    {
        "id": "no-hay-mal-que-dure-cien-anos",
        "expression": "No hay mal que dure cien años",
        "meaning": "Ningún problema o desgracia es eterno; todo pasa con el tiempo.",
        "origin": "Refrán popular documentado desde el siglo XVI. La variante completa es: 'No hay mal que cien años dure, ni cuerpo que lo aguante'.",
        "example": "Estás muy deprimido, pero esto pasará — no hay mal que dure cien años.",
        "register": "standard",
        "tags": ["esperanza", "tiempo", "consuelo"],
    },
    {
        "id": "caerse-la-cara-de-verguenza",
        "expression": "Caérsele la cara de vergüenza",
        "meaning": "Sentir una vergüenza tan intensa que resulta visible e insoportable.",
        "origin": "Imagen hiperbólica: la vergüenza pesa tanto sobre el rostro que parece que va a caerse.",
        "example": "Se le tendría que caer la cara de vergüenza por haber mentido así delante de todos.",
        "register": "informal",
        "tags": ["vergüenza", "honestidad", "moral"],
    },
    {
        "id": "dar-largas",
        "expression": "Dar largas",
        "meaning": "Aplazar o retrasar algo de forma deliberada, dando excusas para no resolverlo.",
        "origin": "'Largas' en el sentido de 'largos plazos'; dar largas es alargar el tiempo de espera sin intención de resolver.",
        "example": "Lleva meses dándome largas con el contrato — creo que no piensa firmarlo.",
        "register": "informal",
        "tags": ["procrastinación", "evasión", "tiempo"],
    },

    # ── Alegría, amor y relaciones ────────────────────────────────────
    {
        "id": "estar-en-el-septimo-cielo",
        "expression": "Estar en el séptimo cielo",
        "meaning": "Sentirse completamente feliz, en un estado de felicidad máxima.",
        "origin": "En la cosmología medieval, el séptimo cielo era el más elevado y donde vivía Dios; alcanzarlo simbolizaba la felicidad perfecta.",
        "example": "Cuando le dijeron que había aprobado con matrícula, estaba en el séptimo cielo.",
        "register": "informal",
        "tags": ["alegría", "felicidad", "emociones"],
    },
    {
        "id": "llevar-la-voz-cantante",
        "expression": "Llevar la voz cantante",
        "meaning": "Ser quien manda, dirige o tiene la autoridad en un grupo o situación.",
        "origin": "El solista o voz principal en un coro o grupo musical lleva la melodía; por extensión, quien lleva la voz cantante dirige al resto.",
        "example": "En ese equipo siempre lleva la voz cantante aunque no sea el jefe oficial.",
        "register": "informal",
        "tags": ["liderazgo", "poder", "autoridad"],
    },
    {
        "id": "ser-tal-para-cual",
        "expression": "Ser tal para cual",
        "meaning": "Ser dos personas muy parecidas en carácter o defectos, especialmente cuando ambos son un poco difíciles.",
        "origin": "Expresión que iguala a dos personas; 'tal' y 'cual' son pronombres indefinidos que se corresponden.",
        "example": "Ella es orgullosa y él es testarudo — son tal para cual.",
        "register": "informal",
        "tags": ["pareja", "carácter", "similitud"],
    },
    {
        "id": "no-hay-quinto-malo",
        "expression": "No hay quinto malo",
        "meaning": "El quinto intento suele salir bien; expresión de optimismo ante una nueva oportunidad.",
        "origin": "Originalmente del ámbito militar (el quinto regimiento) o del tabaco (el quinto cigarrillo del paquete, más sabroso por la humedad). Uso popular generalizado.",
        "example": "Llevo cuatro entrevistas sin éxito, pero no hay quinto malo — mañana me llaman.",
        "register": "informal",
        "tags": ["suerte", "optimismo", "perseverancia"],
    },
    {
        "id": "tener-el-mundo-a-sus-pies",
        "expression": "Tener el mundo a sus pies",
        "meaning": "Gozar de grandes posibilidades, éxito o admiración; tenerlo todo a su favor.",
        "origin": "Imagen de los emperadores y conquistadores ante quienes el mundo se postraba; adaptada para expresar el máximo éxito.",
        "example": "Con solo 25 años y ese talento, tiene el mundo a sus pies.",
        "register": "standard",
        "tags": ["éxito", "fama", "poder"],
    },
    {
        "id": "no-hay-que-dormirse-en-los-laureles",
        "expression": "No hay que dormirse en los laureles",
        "meaning": "No hay que confiarse por los éxitos pasados y dejar de esforzarse.",
        "origin": "Los laureles eran la corona de los vencedores en la Antigüedad griega; dormirse en ellos significaba abandonarse al éxito pasado.",
        "example": "Ganamos el primer trimestre, pero no hay que dormirse en los laureles.",
        "register": "standard",
        "tags": ["esfuerzo", "éxito", "motivación"],
    },
    {
        "id": "donde-fueres-haz-lo-que-vieres",
        "expression": "Donde fueres, haz lo que vieres",
        "meaning": "Hay que adaptarse a las costumbres y normas del lugar donde uno se encuentra.",
        "origin": "Refrán clásico documentado desde el siglo XIV; equivale al inglés 'When in Rome, do as the Romans do'.",
        "example": "En Japón me quité los zapatos al entrar — donde fueres, haz lo que vieres.",
        "register": "standard",
        "tags": ["adaptación", "respeto", "viajes", "costumbres"],
    },
    {
        "id": "a-dios-rogando-y-con-el-mazo-dando",
        "expression": "A Dios rogando y con el mazo dando",
        "meaning": "Hay que pedir ayuda o confiar en la suerte, pero también actuar por uno mismo; la oración no sustituye al esfuerzo.",
        "origin": "Refrán clásico español documentado desde el siglo XIII. El mazo es un mazo de trabajo; el refrán combina fe y acción.",
        "example": "Espero que el proyecto salga bien, pero mientras tanto estoy trabajando — a Dios rogando y con el mazo dando.",
        "register": "standard",
        "tags": ["esfuerzo", "trabajo", "fe"],
    },
    {
        "id": "no-hay-atajo-sin-trabajo",
        "expression": "No hay atajo sin trabajo",
        "meaning": "No existen caminos fáciles hacia el éxito; todo requiere esfuerzo y dedicación.",
        "origin": "Refrán popular de origen incierto que recoge la sabiduría sobre el esfuerzo necesario para lograr cualquier meta.",
        "example": "Quería aprender chino en tres meses — no hay atajo sin trabajo.",
        "register": "standard",
        "tags": ["trabajo", "esfuerzo", "éxito"],
    },
    {
        "id": "la-union-hace-la-fuerza",
        "expression": "La unión hace la fuerza",
        "meaning": "Las personas unidas son más fuertes y consiguen más que trabajando por separado.",
        "origin": "Lema político adoptado en numerosos países; base del pensamiento sindicalista y cooperativo del siglo XIX.",
        "example": "Juntos consiguieron negociar mejores condiciones — la unión hace la fuerza.",
        "register": "standard",
        "tags": ["colaboración", "unidad", "fuerza"],
    },
    {
        "id": "cada-uno-es-libre",
        "expression": "Cada uno en su casa y Dios en la de todos",
        "meaning": "Cada persona tiene derecho a vivir como quiera en su propio espacio sin que los demás interfieran.",
        "origin": "Refrán popular que defiende la autonomía personal y el respeto a la privacidad ajena.",
        "example": "No me gusta su estilo de vida, pero cada uno en su casa y Dios en la de todos.",
        "register": "standard",
        "tags": ["independencia", "respeto", "privacidad"],
    },
    {
        "id": "pueblo-pequeno-infierno-grande",
        "expression": "Pueblo pequeño, infierno grande",
        "meaning": "En las comunidades pequeñas hay más chismes, envidias y control social que en las ciudades.",
        "origin": "Refrán popular que refleja la experiencia de la vida rural española donde todo el mundo se conoce y nadie tiene privacidad.",
        "example": "Me mudé al pueblo y en una semana sabían todo de mí — pueblo pequeño, infierno grande.",
        "register": "informal",
        "tags": ["chismorreo", "privacidad", "comunidad"],
    },
    {
        "id": "en-el-pais-de-los-ciegos-el-tuerto-es-el-rey",
        "expression": "En el país de los ciegos, el tuerto es el rey",
        "meaning": "Alguien con habilidades modestas puede destacar o dominar en un entorno donde los demás tienen aún menos.",
        "origin": "Atribuido a Erasmo de Rotterdam. Popularizado en español desde el siglo XVI.",
        "example": "En esa empresa nadie sabe inglés, así que con su nivel básico ya es indispensable — en el país de los ciegos, el tuerto es el rey.",
        "register": "standard",
        "tags": ["habilidad", "contexto", "relatividad"],
    },
    {
        "id": "no-dejes-para-manana",
        "expression": "No dejes para mañana lo que puedas hacer hoy",
        "meaning": "Hay que actuar sin demora; la procrastinación lleva a acumular problemas.",
        "origin": "Consejo atribuido a Benjamin Franklin aunque ya aparece en autores clásicos griegos y latinos.",
        "example": "Empieza el informe ahora — no dejes para mañana lo que puedas hacer hoy.",
        "register": "standard",
        "tags": ["procrastinación", "trabajo", "tiempo"],
    },
    {
        "id": "al-mal-paso-darle-prisa",
        "expression": "Al mal paso, darle prisa",
        "meaning": "Ante una situación difícil o desagradable, es mejor resolverla cuanto antes para que dure lo menos posible.",
        "origin": "Refrán popular castellano; la imagen del 'mal paso' es un terreno difícil que conviene cruzar rápido.",
        "example": "La conversación va a ser incómoda, pero al mal paso darle prisa — mejor hablar hoy.",
        "register": "standard",
        "tags": ["dificultad", "resolución", "tiempo"],
    },
    {
        "id": "agua-pasada-no-mueve-molino",
        "expression": "Agua pasada no mueve molino",
        "meaning": "Lo que ya ha ocurrido no sirve de nada; hay que mirar al futuro y no al pasado.",
        "origin": "Imagen del molino de agua: solo funciona con el agua que pasa ahora, no con la que ya pasó.",
        "example": "Ya perdiste esa oportunidad — agua pasada no mueve molino, busca la siguiente.",
        "register": "standard",
        "tags": ["pasado", "futuro", "oportunidad", "agua"],
    },
    {
        "id": "a-lo-hecho-pecho",
        "expression": "A lo hecho, pecho",
        "meaning": "Hay que asumir las consecuencias de lo que se ha hecho y afrontarlas con valentía.",
        "origin": "Imagen física de sacar el pecho como señal de valentía para hacer frente a lo ocurrido.",
        "example": "Ya enviaste el correo sin revisar — a lo hecho, pecho, explícate y sigue adelante.",
        "register": "informal",
        "tags": ["responsabilidad", "valentía", "consecuencias"],
    },
    {
        "id": "no-es-lo-mismo-predicar-que-dar-trigo",
        "expression": "No es lo mismo predicar que dar trigo",
        "meaning": "Es fácil aconsejar o hablar, pero lo difícil es actuar consecuentemente y dar lo que se promete.",
        "origin": "Refrán popular que critica la diferencia entre el discurso y la acción; el trigo es el regalo concreto, el predicar solo palabras.",
        "example": "Dice que hay que ser generoso pero nunca ayuda — no es lo mismo predicar que dar trigo.",
        "register": "standard",
        "tags": ["hipocresía", "honestidad", "acción"],
    },
    {
        "id": "al-que-no-quiere-caldo-taza-y-media",
        "expression": "Al que no quiere caldo, taza y media",
        "meaning": "A quien rechaza algo o no lo desea, la vida le da más de eso mismo; la ironía del destino.",
        "origin": "Refrán popular que ironiza sobre cómo el destino parece dar más de lo que uno no quiere.",
        "example": "Quería evitar reuniones y le nombraron coordinador — al que no quiere caldo, taza y media.",
        "register": "informal",
        "tags": ["ironía", "destino", "suerte"],
    },
    {
        "id": "tanto-va-el-cantaro-a-la-fuente",
        "expression": "Tanto va el cántaro a la fuente que al fin se rompe",
        "meaning": "Quien abusa de algo o arriesga repetidamente acaba sufriendo las consecuencias.",
        "origin": "Refrán documentado desde el siglo XIII. El cántaro que va muchas veces a buscar agua acaba rompiéndose.",
        "example": "Siempre miente y sale bien parado, pero tanto va el cántaro a la fuente...",
        "register": "standard",
        "tags": ["riesgo", "consecuencias", "abuso"],
    },
    {
        "id": "el-que-la-hace-la-paga",
        "expression": "El que la hace, la paga",
        "meaning": "Todo el que comete una mala acción acaba sufriendo las consecuencias de la misma.",
        "origin": "Expresión popular de justicia poética; la idea de que los actos tienen consecuencias está en todas las culturas.",
        "example": "Le cogieron haciendo trampa — el que la hace, la paga.",
        "register": "standard",
        "tags": ["justicia", "consecuencias", "moral"],
    },
    {
        "id": "no-hay-peor-ciego-que-el-que-no-quiere-ver",
        "expression": "No hay peor ciego que el que no quiere ver",
        "meaning": "La peor ignorancia es la voluntaria; hay personas que se niegan a reconocer la realidad aunque la tengan delante.",
        "origin": "Refrán documentado desde el siglo XVI, con equivalente en latín ('Nemo tam caecus quam qui non vult videre').",
        "example": "Sabe que su socio le roba, pero no hace nada — no hay peor ciego que el que no quiere ver.",
        "register": "standard",
        "tags": ["ignorancia", "negación", "honestidad"],
    },
]

def main():
    conn = sqlite3.connect(DB_PATH)
    inserted = 0
    skipped = 0
    for expr in EXPRESSIONS:
        tags_json = json.dumps(expr["tags"], ensure_ascii=False)
        try:
            conn.execute(
                """INSERT OR IGNORE INTO expressions
                   (id, expression, meaning, origin, example, register, language, region, tags)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    expr["id"], expr["expression"], expr["meaning"],
                    expr["origin"], expr.get("example", ""),
                    expr.get("register", "standard"),
                    "es", "es", tags_json,
                ),
            )
            if conn.execute("SELECT changes()").fetchone()[0]:
                inserted += 1
            else:
                skipped += 1
        except Exception as e:
            print(f"  ERROR {expr['id']}: {e}")

    conn.commit()
    conn.close()
    print(f"Done — {inserted} inserted, {skipped} skipped (already exist).")
    print(f"Total Spanish expressions: {inserted}")

if __name__ == "__main__":
    main()
