#!/usr/bin/env python3
"""
normalize_tags_v2.py — Phase 2 tag normalization.

For each of the 643 tags missing an English translation:
  - If the slug is non-English → merge into the English equivalent (or rename if
    the English slug doesn't exist yet), then add EN entry to tag_names.
  - If the slug is already English → just add the EN tag_names entry.

Usage:
  python3 scripts/normalize_tags_v2.py           # dry-run (default)
  python3 scripts/normalize_tags_v2.py --apply   # apply changes
"""

import sys
from sqlalchemy import text
from config import engine

DRY_RUN = "--apply" not in sys.argv

# ─── Main mapping ────────────────────────────────────────────────────────────
# old_slug → new_english_slug
# The script merges old into new if new exists, or renames otherwise.
# EN display name is looked up from tag_names[new, 'en'] when merging,
# or from EN_NAMES below when renaming.

SLUG_MAP = {
    # ── French ───────────────────────────────────────────────────────────────
    "voyage":             "journey",
    "opportunité":        "opportunity",
    "problème":           "problem",
    "changement":         "change",
    "confiance":          "trust",
    "détermination":      "determination",
    "persévérance":       "perseverance",
    "réflexion":          "reflection",
    "clarté":             "clarity",
    "excès":              "excess",
    "indifférence":       "indifference",
    "indiscrétion":       "indiscretion",
    "morale":             "morality",
    "mémoire":            "memory",
    "pardon":             "forgiveness",
    "émotion":            "emotion",
    "évitement":          "avoidance",
    "apparence":          "appearance",
    "bêtise":             "foolishness",
    "chiffres":           "numbers",
    "comportement":       "behavior",
    "eau":                "water",
    "jeunes":             "youth",
    "verlan":             "verlan",       # keep slug — French cultural term
    "acharnement":        "tenacity",
    "aide":               "help",
    "attente":            "expectation",
    "désir":              "desire",
    "dévouement":         "devotion",
    "efficacité":         "efficiency",
    "empathie":           "empathy",
    "enfance":            "childhood",
    "engagement":         "commitment",
    "expérience":         "experience",
    "facilité":           "ease",
    "forme-physique":     "physical-fitness",
    "honneur":            "honor",
    "honnêteté":          "honesty",
    "humilité":           "humility",
    "humoristique":       "humorous",
    "humour":             "humor",
    "héritage":           "heritage",
    "implication":        "involvement",
    "intensité":          "intensity",
    "lâcheté":            "cowardice",
    "malchance":          "bad-luck",
    "orgueil":            "pride",
    "peine":              "sorrow",
    "pouvoir":            "power",
    "pragmatisme":        "pragmatism",
    "productivité":       "productivity",
    "précipitation":      "haste",
    "précision":          "precision",
    "richesse":           "wealth",
    "réalisme":           "realism",
    "réconciliation":     "reconciliation",
    "rêverie":            "daydreaming",
    "soin":               "care",
    "solidarité":         "solidarity",
    "souhait":            "wish",
    "soumission":         "submission",
    "soutien":            "support",
    "succès":             "success",
    "susceptibilité":     "sensitivity",
    "vitalité":           "vitality",
    "vitesse":            "speed",
    "épuisement":         "exhaustion",
    "abandon":            "abandonment",
    "agressivité":        "aggressiveness",
    "alcool":             "alcohol",
    "apprentissage":      "learning",
    "bonheur":            "happiness",
    "carrière":           "career",
    "certitude":          "certainty",
    "couple":             "couple",
    "défaite":            "defeat",
    "diplomatie":         "diplomacy",
    "directivité":        "directiveness",
    "discrétion":         "discretion",
    "dispersion":         "scattering",
    "ennui":              "boredom",
    "enthousiasme":       "enthusiasm",
    "espoir-déçu":        "disappointment",
    "euphémisme":         "euphemism",
    "exaspération":       "exasperation",
    "excentricité":       "eccentricity",
    "faim":               "hunger",
    "famille":            "family",
    "fatalité":           "fatality",
    "folie-légère":       "silliness",
    "froid":              "cold",
    "futilité":           "futility",
    "gratuité":           "freeness",
    "hostilité":          "hostility",
    "imprudence":         "recklessness",
    "incompréhension":    "misunderstanding",
    "indécision":         "indecision",
    "inefficacité":       "inefficiency",
    "injustice":          "injustice",
    "joie":               "joy",
    "manipulation":       "manipulation",
    "mauvaise-humeur":    "bad-mood",
    "médiocrité":         "mediocrity",
    "mélancolie":         "melancholy",
    "naïveté":            "naivety",
    "négociation":        "negotiation",
    "objectif":           "goal",
    "organisation":       "organization",
    "perte-de-contrôle":  "loss-of-control",
    "plantes":            "plants",
    "pluie":              "rain",
    "repos":              "rest",
    "résultat":           "result",
    "stratégie":          "strategy",
    "vanité":             "vanity",
    "danger":             "danger",
    "difficultés":        "difficulties",
    "regret":             "regret",
    "stress":             "stress",
    "suspicion":          "suspicion",
    "nature":             "nature",
    "talent":             "talent",
    "passion":            "passion",
    "respect":            "respect",
    "leadership":         "leadership",
    "justice":            "justice",
    "obstacle":           "obstacle",
    "concentration":      "concentration",
    "confusion":          "confusion",
    "conscience":         "conscience",
    "fatigue":            "fatigue",
    "humiliation":        "humiliation",
    "illusion":           "illusion",
    "surveillance":       "surveillance",
    "arrogance":          "arrogance",
    "intuition":          "intuition",
    "improvisation":      "improvisation",
    "introspection":      "introspection",
    "intrusion":          "intrusion",
    "progression":        "progression",
    "perception":         "perception",
    "endurance":          "endurance",
    "irritation":         "irritation",
    "adolescence":        "adolescence",
    "anticipation":       "anticipation",
    "admiration":         "admiration",
    "procrastination":    "procrastination",
    "satisfaction":       "satisfaction",
    "sacrifice":          "sacrifice",
    "superstition":       "superstition",
    "initiative":         "initiative",
    "absurde":            "absurdity",
    "accueil":            "welcome",
    "activité":           "activity",
    "admiration":         "admiration",
    "adolescence":        "adolescence",
    "affection":          "affection",
    "agacement":          "annoyance",
    "aisance":            "ease",
    "alerte":             "alert",
    "altruisme":          "altruism",
    "annulation":         "cancellation",
    "antipathie":         "antipathy",
    "appréciation":       "appreciation",
    "appétit":            "appetite",
    "ardeur":             "ardor",
    "arnaque":            "scam",
    "aubaine":            "windfall",
    "autodestruction":    "self-destruction",
    "autorité":           "authority",
    "avantage":           "advantage",
    "aversion":           "aversion",
    "bien-être":          "well-being",
    "bienveillance":      "kindness",
    "blocage":            "blockage",
    "bonne-affaire":      "good-deal",
    "bonne-foi":          "good-faith",
    "bonne-humeur":       "good-mood",
    "bouc-émissaire":     "scapegoat",
    "budget":             "budget",
    "bureaucratie":       "bureaucracy",
    "bêtises":            "nonsense",
    "calme":              "calm",
    "capacités":          "abilities",
    "chagrin":            "grief",
    "chaos":              "chaos",
    "choix":              "choice",
    "combativité":        "fighting-spirit",
    "comparaison":        "comparison",
    "complaisance":       "complacency",
    "complication-inutile": "unnecessary-complication",
    "compromis":          "compromise",
    "confort":            "comfort",
    "connaissance":       "knowledge",
    "contentement":       "contentment",
    "contrainte":         "constraint",
    "crise":              "crisis",
    "crépuscule":         "twilight",
    "cuisine":            "cooking",
    "cupidité":           "greed",
    "curiosité":          "curiosity",
    "cérémonie":          "ceremony",
    "dette":              "debt",
    "deuil":              "mourning",
    "dignité":            "dignity",
    "digression":         "digression",
    "dissimulation":      "concealment",
    "domination":         "domination",
    "don-naturel":        "natural-gift",
    "dramatisation":      "dramatization",
    "droits":             "rights",
    "duplicité":          "duplicity",
    "déchéance":          "downfall",
    "déclin":             "decline",
    "défense":            "defense",
    "dégradation":        "degradation",
    "délicatesse":        "delicacy",
    "délégation":         "delegation",
    "déni":               "denial",
    "dénonciation":       "denunciation",
    "dépendance":         "dependence",
    "dépense":            "spending",
    "dépression":         "depression",
    "dérision":           "derision",
    "désordre":           "disorder",
    "désorganisation":    "disorganization",
    "détachement":        "detachment",
    "détente":            "relaxation",
    "développement-personnel": "self-development",
    "économie":           "economy",
    "éducation":          "education",
    "égalité":            "equality",
    "évidence":           "evidence",
    "enchaînement":       "chain-of-events",
    "erreur-stratégique": "strategic-mistake",
    "espoir":             "hope",
    "excuses":            "apology",
    "exemple":            "example",
    "exigences":          "demands",
    "façade":             "facade",
    "fin":                "end",
    "folie":              "madness",
    "frisson":            "thrill",
    "froideur":           "coldness",
    "fête":               "celebration",
    "gastronomie":        "gastronomy",
    "gestion":            "management",
    "gloire":             "glory",
    "habileté":           "skill",
    "habitude":           "habit",
    "hausse":             "rise",
    "histoire":           "story",
    "hésitation":         "hesitation",
    "ignorance-volontaire": "willful-ignorance",
    "impact":             "impact",
    "imperfection":       "imperfection",
    "impuissance":        "helplessness",
    "incompétence":       "incompetence",
    "indépendance":       "independence",
    "ingérence":          "interference",
    "installation":       "installation",
    "intellectuel":       "intellectual",
    "interprétation":     "interpretation",
    "interrogation":      "questioning",
    "intrusion":          "intrusion",
    "intégrité":          "integrity",
    "intériorité":        "interiority",
    "intérêt-personnel":  "self-interest",
    "irritabilité":       "irritability",
    "irréalisme":         "unrealism",
    "jardinage":          "gardening",
    "jeu":                "play",
    "jeune":              "young",
    "jeunesse":           "youth",
    "jugement":           "judgment",
    "langage":            "language",
    "leçon":              "lesson",
    "logique":            "logic",
    "lâcher-prise":       "letting-go",
    "légèreté":           "lightness",
    "magie":              "magic",
    "malaise":            "unease",
    "malhonnêteté":       "dishonesty",
    "manque":             "lack",
    "manque-de-courage":  "lack-of-courage",
    "manque-de-jugement": "poor-judgment",
    "maturité":           "maturity",
    "mauvais-timing":     "bad-timing",
    "maîtrise-de-soi":    "self-control",
    "menace":             "threat",
    "mer":                "sea",
    "mesquinerie":        "pettiness",
    "moderne":            "modern",
    "modération":         "moderation",
    "mort":               "death",
    "musique":            "music",
    "méditation":         "meditation",
    "mépris":             "contempt",
    "nervosité":          "nervousness",
    "noblesse":           "nobility",
    "nuance":             "nuance",
    "nuit":               "night",
    "négligence":         "negligence",
    "obsession":          "obsession",
    "omission":           "omission",
    "ordre":              "order",
    "orientation":        "orientation",
    "ostentation":        "ostentation",
    "oubli":              "forgetfulness",
    "pauvreté":           "poverty",
    "pauvreté-relative":  "relative-poverty",
    "pensée":             "thought",
    "perplexité":         "perplexity",
    "perte":              "loss",
    "point-de-vue":       "point-of-view",
    "position":           "position",
    "pression":           "pressure",
    "prix-élevé":         "high-price",
    "promotion":          "promotion",
    "prononciation":      "pronunciation",
    "préférence":         "preference",
    "prématuré":          "premature",
    "préparation":        "preparation",
    "prévoyance":         "foresight",
    "raisonnement":       "reasoning",
    "ras-le-bol":         "fed-up",
    "rattrapage":         "catching-up",
    "refus":              "refusal",
    "relativisation":     "relativization",
    "remise-en-cause":    "self-questioning",
    "rendez-vous":        "appointment",
    "repas":              "meal",
    "reproche":           "reproach",
    "ressources":         "resources",
    "retenue":            "restraint",
    "rigueur":            "rigor",
    "rigueur-excessive":  "excessive-rigor",
    "risque-nul":         "zero-risk",
    "rivalité":           "rivalry",
    "robustesse":         "robustness",
    "rumeur":             "rumor",
    "rumination":         "rumination",
    "rupture":            "breakup",
    "réaction":           "reaction",
    "récit":              "narrative",
    "récompense":         "reward",
    "réconfort":          "comfort",
    "récupération":       "recovery",
    "réorganisation":     "reorganization",
    "réprimande":         "reprimand",
    "révélation":         "revelation",
    "sagacité":           "sagacity",
    "sang-froid":         "composure",
    "savoir-faire":       "know-how",
    "schadenfreude":      "schadenfreude",
    "sensibilité":        "sensitivity",
    "simplicité":         "simplicity",
    "situations":         "situations",
    "sociabilité":        "sociability",
    "spectacle":          "spectacle",
    "stabilité":          "stability",
    "surcharge":          "overload",
    "survie":             "survival",
    "sécurité":           "security",
    "sérénité":           "serenity",
    "talent-inné":        "innate-talent",
    "théâtralité":        "theatricality",
    "torpeur":            "torpor",
    "transaction":        "transaction",
    "transgression":      "transgression",
    "transparence":       "transparency",
    "triomphe":           "triumph",
    "urgence":            "urgency",
    "valeurs":            "values",
    "victime":            "victim",
    "victoire":           "victory",
    "vie":                "life",
    "vie-agitée":         "hectic-life",
    "vieillesse":         "old-age",
    "vigilance":          "vigilance",
    "voisinage":          "neighborhood",
    "voiture":            "car",
    "vulgarité":          "vulgarity",
    "vérité":             "truth",
    "âge":                "age",
    "école":              "school",
    "écouter":            "listening",
    "égocentrisme":       "egocentrism",
    "égoïsme":            "selfishness",
    "élimination":        "elimination",
    "élégance":           "elegance",
    "épargne":            "savings",
    "équilibre":          "balance",
    "évanouissement":     "fainting",
    "évasion":            "escape",
    "éveil":              "awakening",
    "agitation":          "agitation",
    "anxiété":            "anxiety",
    "apparences":         "appearances",
    "approbation":        "approval",
    "aptitude":           "aptitude",
    "aristocratie":       "aristocracy",
    "connexions":         "connections",
    "culpabilité":        "guilt",
    "dépenses":           "expenses",
    "dilapidation":       "dilapidation",
    "discours":           "speech",
    "distraction":        "distraction",
    "don":                "gift",
    "habitude":           "habit",
    "humeur":             "mood",
    "hypocrisie":         "hypocrisy",
    "imperfection":       "imperfection",
    "inattention":        "inattention",
    "incohérence":        "incoherence",
    "instant":            "instant",
    "intérêt-personnel":  "self-interest",
    "matin":              "morning",
    "méthode":            "method",
    "noblesse":           "nobility",
    "obsession":          "obsession",
    "origine":            "origin",
    "réactivité":         "reactivity",
    "réalité":            "reality",
    "retard":             "delay",
    "rigueur":            "rigor",
    "théâtre":            "theater",
    "transparence":       "transparency",
    "absurdo":            "absurdity",
    "abuso":              "abuse",
    "acción":             "action",
    "acumulación":        "accumulation",
    "actitud":            "attitude",
    "agotamiento":        "exhaustion",
    "agresividad":        "aggressiveness",
    "alegría":            "joy",
    "ambición":           "ambition",
    "amenaza":            "threat",
    "amor":               "love",
    "apariencia":         "appearance",
    "asombro":            "astonishment",
    "atención":           "attention",
    "atrevimiento":       "boldness",
    "amistad":            "friendship",
    "adaptación":         "adaptation",
    "agua":               "water",
    "autoridad":          "authority",
    "bienestar":          "well-being",
    "bloqueo":            "blockage",
    "burla":              "mockery",
    "calma":              "calm",
    "cansancio":          "tiredness",
    "carácter":           "character",
    "caro":               "expensive",
    "celebración":        "celebration",
    "certeza":            "certainty",
    "chismorreo":         "gossip",
    "claridad":           "clarity",
    "cobardía":           "cowardice",
    "colaboración":       "collaboration",
    "comida":             "food",
    "comodidad":          "comfort",
    "comparaison":        "comparison",
    "compatibilidad":     "compatibility",
    "competición":        "competition",
    "complicar":          "complicating",
    "complicidad":        "complicity",
    "comunidad":          "community",
    "concentración":      "concentration",
    "confusión":          "confusion",
    "conocimiento":       "knowledge",
    "consuelo":           "consolation",
    "contexto":           "context",
    "costumbres":         "customs",
    "culpa":              "guilt",
    "curación":           "healing",
    "curiosité":          "curiosity",
    "decisión":           "decision",
    "desconfianza":       "distrust",
    "destino":            "destiny",
    "destreza":           "skill",
    "determinación":      "determination",
    "diferente":          "different",
    "dificultad":         "difficulty",
    "dilema":             "dilemma",
    "dinero":             "money",
    "disimulo":           "concealment",
    "distracción":        "distraction",
    "dolor":              "pain",
    "economía":           "economy",
    "edad":               "age",
    "eficiencia":         "efficiency",
    "elogio":             "praise",
    "emociones":          "emotion",
    "equilibrio":         "balance",
    "esperanza":          "hope",
    "estado":             "state",
    "estrés":             "stress",
    "estudios":           "studies",
    "evasión":            "evasion",
    "evidencia":          "evidence",
    "exageración":        "exaggeration",
    "exceso":             "excess",
    "experiencia":        "experience",
    "facilidad":          "ease",
    "fama":               "fame",
    "familia":            "family",
    "fe":                 "faith",
    "felicidad":          "happiness",
    "firmeza":            "firmness",
    "fracaso":            "failure",
    "franqueza":          "frankness",
    "fraude":             "fraud",
    "frustración":        "frustration",
    "fuerza":             "strength",
    "futuro":             "future",
    "generosidad":        "generosity",
    "gratitud":           "gratitude",
    "habilidad":          "skill",
    "hartazgo":           "fed-up",
    "herencia":           "heritage",
    "hipocresía":         "hypocrisy",
    "ignorancia":         "ignorance",
    "ignorar":            "ignoring",
    "impertinencia":      "impertinence",
    "imposible":          "impossible",
    "imprudencia":        "recklessness",
    "incoherencia":       "incoherence",
    "incredulidad":       "disbelief",
    "independencia":      "independence",
    "indiferencia":       "indifference",
    "influencia":         "influence",
    "injusticia":         "injustice",
    "insomnio":           "insomnia",
    "insultos":           "insults",
    "intuición":          "intuition",
    "inutilidad":         "uselessness",
    "ironía":             "irony",
    "justicia":           "justice",
    "lectura":            "reading",
    "liderazgo":          "leadership",
    "límite":             "limit",
    "lobo":               "wolf",
    "locuacidad":         "talkativeness",
    "mala-suerte":        "bad-luck",
    "malhumor":           "bad-mood",
    "miedo":              "fear",
    "moral":              "morality",
    "motivación":         "motivation",
    "necesidad":          "need",
    "negación":           "denial",
    "nervios":            "nervousness",
    "nunca":              "never",
    "obvio":              "obvious",
    "olvido":             "forgetfulness",
    "oportunidad":        "opportunity",
    "optimismo":          "optimism",
    "paradoja":           "paradox",
    "pareja":             "couple",
    "pasado":             "past",
    "paciencia":          "patience",
    "pensamiento":        "thought",
    "permisividad":       "permissiveness",
    "perseverancia":      "perseverance",
    "perro":              "dog",
    "pez":                "fish",
    "pobreza":            "poverty",
    "poder":              "power",
    "precio":             "price",
    "privacidad":         "privacy",
    "problema":           "problem",
    "problemas":          "problem",
    "procrastinación":    "procrastination",
    "provecho":           "benefit",
    "pájaro":             "bird",
    "reacción":           "reaction",
    "realismo":           "realism",
    "reconocimiento":     "recognition",
    "regalo":             "gift",
    "relatividad":        "relativity",
    "repetición":         "repetition",
    "resistencia":        "resistance",
    "resolución":         "resolution",
    "responsabilidad":    "responsibility",
    "riesgo":             "risk",
    "rumores":            "rumors",
    "sabiduría":          "wisdom",
    "sencillo":           "simplicity",
    "sensatez":           "sensibleness",
    "silencio":           "silence",
    "similitud":          "similarity",
    "sin-salida":         "dead-end",
    "sinceridad":         "sincerity",
    "soledad":            "loneliness",
    "solución":           "solution",
    "sorpresa":           "surprise",
    "soñar":              "dreaming",
    "sueño":              "dream",
    "suerte":             "luck",
    "superación":         "overcoming",
    "talento":            "talent",
    "terquedad":          "stubbornness",
    "timidez":            "shyness",
    "torpeza":            "clumsiness",
    "unidad":             "unity",
    "valentía":           "bravery",
    "valor":              "bravery",
    "verdad":             "truth",
    "vergüenza":          "shame",
    "viajes":             "travel",
    "victoria":           "victory",
    "voluntad":           "willpower",
    "éxito":              "success",
}

# EN display names for slugs that don't exist yet (rename target is new)
EN_NAMES = {
    "verlan":                   "Verlan",
    "tenacity":                 "Tenacity",
    "devotion":                 "Devotion",
    "childhood":                "Childhood",
    "commitment":               "Commitment",
    "honesty":                  "Honesty",
    "humility":                 "Humility",
    "humorous":                 "Humorous",
    "heritage":                 "Heritage",
    "involvement":              "Involvement",
    "intensity":                "Intensity",
    "cowardice":                "Cowardice",
    "bad-luck":                 "Bad Luck",
    "sorrow":                   "Sorrow",
    "pragmatism":               "Pragmatism",
    "productivity":             "Productivity",
    "haste":                    "Haste",
    "realism":                  "Realism",
    "reconciliation":           "Reconciliation",
    "daydreaming":              "Daydreaming",
    "solidarity":               "Solidarity",
    "wish":                     "Wish",
    "submission":               "Submission",
    "vitality":                 "Vitality",
    "aggressiveness":           "Aggressiveness",
    "learning":                 "Learning",
    "career":                   "Career",
    "defeat":                   "Defeat",
    "diplomacy":                "Diplomacy",
    "directiveness":            "Directiveness",
    "scattering":               "Scattering",
    "boredom":                  "Boredom",
    "enthusiasm":               "Enthusiasm",
    "euphemism":                "Euphemism",
    "exasperation":             "Exasperation",
    "eccentricity":             "Eccentricity",
    "fatality":                 "Fatality",
    "silliness":                "Silliness",
    "cold":                     "Cold",
    "futility":                 "Futility",
    "freeness":                 "Freeness",
    "hostility":                "Hostility",
    "recklessness":             "Recklessness",
    "misunderstanding":         "Misunderstanding",
    "indecision":               "Indecision",
    "inefficiency":             "Inefficiency",
    "bad-mood":                 "Bad Mood",
    "mediocrity":               "Mediocrity",
    "melancholy":               "Melancholy",
    "naivety":                  "Naivety",
    "negotiation":              "Negotiation",
    "goal":                     "Goal",
    "loss-of-control":          "Loss of Control",
    "plants":                   "Plants",
    "strategy":                 "Strategy",
    "vanity":                   "Vanity",
    "difficulties":             "Difficulties",
    "welcome":                  "Welcome",
    "activity":                 "Activity",
    "annoyance":                "Annoyance",
    "alert":                    "Alert",
    "altruism":                 "Altruism",
    "cancellation":             "Cancellation",
    "antipathy":                "Antipathy",
    "appreciation":             "Appreciation",
    "appetite":                 "Appetite",
    "ardor":                    "Ardor",
    "scam":                     "Scam",
    "windfall":                 "Windfall",
    "self-destruction":         "Self-Destruction",
    "authority":                "Authority",
    "advantage":                "Advantage",
    "aversion":                 "Aversion",
    "well-being":               "Well-Being",
    "kindness":                 "Kindness",
    "blockage":                 "Blockage",
    "good-deal":                "Good Deal",
    "good-faith":               "Good Faith",
    "good-mood":                "Good Mood",
    "scapegoat":                "Scapegoat",
    "budget":                   "Budget",
    "bureaucracy":              "Bureaucracy",
    "nonsense":                 "Nonsense",
    "calm":                     "Calm",
    "abilities":                "Abilities",
    "grief":                    "Grief",
    "chaos":                    "Chaos",
    "choice":                   "Choice",
    "fighting-spirit":          "Fighting Spirit",
    "comparison":               "Comparison",
    "complacency":              "Complacency",
    "unnecessary-complication": "Unnecessary Complication",
    "compromise":               "Compromise",
    "comfort":                  "Comfort",
    "contentment":              "Contentment",
    "constraint":               "Constraint",
    "crisis":                   "Crisis",
    "twilight":                 "Twilight",
    "cooking":                  "Cooking",
    "greed":                    "Greed",
    "curiosity":                "Curiosity",
    "ceremony":                 "Ceremony",
    "debt":                     "Debt",
    "mourning":                 "Mourning",
    "dignity":                  "Dignity",
    "digression":               "Digression",
    "concealment":              "Concealment",
    "domination":               "Domination",
    "natural-gift":             "Natural Gift",
    "dramatization":            "Dramatization",
    "rights":                   "Rights",
    "duplicity":                "Duplicity",
    "downfall":                 "Downfall",
    "decline":                  "Decline",
    "defense":                  "Defense",
    "degradation":              "Degradation",
    "delicacy":                 "Delicacy",
    "delegation":               "Delegation",
    "denunciation":             "Denunciation",
    "dependence":               "Dependence",
    "spending":                 "Spending",
    "depression":               "Depression",
    "derision":                 "Derision",
    "disorder":                 "Disorder",
    "disorganization":          "Disorganization",
    "detachment":               "Detachment",
    "relaxation":               "Relaxation",
    "self-development":         "Self-Development",
    "economy":                  "Economy",
    "education":                "Education",
    "equality":                 "Equality",
    "evidence":                 "Evidence",
    "chain-of-events":          "Chain of Events",
    "strategic-mistake":        "Strategic Mistake",
    "apology":                  "Apology",
    "example":                  "Example",
    "demands":                  "Demands",
    "facade":                   "Facade",
    "end":                      "End",
    "madness":                  "Madness",
    "thrill":                   "Thrill",
    "coldness":                 "Coldness",
    "gastronomy":               "Gastronomy",
    "management":               "Management",
    "glory":                    "Glory",
    "habit":                    "Habit",
    "rise":                     "Rise",
    "story":                    "Story",
    "hesitation":               "Hesitation",
    "willful-ignorance":        "Willful Ignorance",
    "impact":                   "Impact",
    "imperfection":             "Imperfection",
    "helplessness":             "Helplessness",
    "incompetence":             "Incompetence",
    "interference":             "Interference",
    "installation":             "Installation",
    "intellectual":             "Intellectual",
    "interpretation":           "Interpretation",
    "questioning":              "Questioning",
    "integrity":                "Integrity",
    "interiority":              "Interiority",
    "self-interest":            "Self-Interest",
    "irritability":             "Irritability",
    "unrealism":                "Unrealism",
    "gardening":                "Gardening",
    "play":                     "Play",
    "young":                    "Young",
    "judgment":                 "Judgment",
    "language":                 "Language",
    "lesson":                   "Lesson",
    "logic":                    "Logic",
    "letting-go":               "Letting Go",
    "lightness":                "Lightness",
    "magic":                    "Magic",
    "unease":                   "Unease",
    "dishonesty":               "Dishonesty",
    "lack":                     "Lack",
    "lack-of-courage":          "Lack of Courage",
    "poor-judgment":            "Poor Judgment",
    "maturity":                 "Maturity",
    "bad-timing":               "Bad Timing",
    "self-control":             "Self-Control",
    "threat":                   "Threat",
    "sea":                      "Sea",
    "pettiness":                "Pettiness",
    "modern":                   "Modern",
    "moderation":               "Moderation",
    "death":                    "Death",
    "music":                    "Music",
    "meditation":               "Meditation",
    "contempt":                 "Contempt",
    "nervousness":              "Nervousness",
    "nobility":                 "Nobility",
    "nuance":                   "Nuance",
    "night":                    "Night",
    "negligence":               "Negligence",
    "omission":                 "Omission",
    "order":                    "Order",
    "orientation":              "Orientation",
    "ostentation":              "Ostentation",
    "relative-poverty":         "Relative Poverty",
    "perplexity":               "Perplexity",
    "loss":                     "Loss",
    "point-of-view":            "Point of View",
    "position":                 "Position",
    "pressure":                 "Pressure",
    "high-price":               "High Price",
    "promotion":                "Promotion",
    "pronunciation":            "Pronunciation",
    "preference":               "Preference",
    "premature":                "Premature",
    "preparation":              "Preparation",
    "foresight":                "Foresight",
    "reasoning":                "Reasoning",
    "fed-up":                   "Fed Up",
    "catching-up":              "Catching Up",
    "refusal":                  "Refusal",
    "relativization":           "Relativization",
    "self-questioning":         "Self-Questioning",
    "appointment":              "Appointment",
    "meal":                     "Meal",
    "reproach":                 "Reproach",
    "resources":                "Resources",
    "restraint":                "Restraint",
    "rigor":                    "Rigor",
    "excessive-rigor":          "Excessive Rigor",
    "zero-risk":                "Zero Risk",
    "rivalry":                  "Rivalry",
    "robustness":               "Robustness",
    "rumor":                    "Rumor",
    "rumination":               "Rumination",
    "breakup":                  "Breakup",
    "narrative":                "Narrative",
    "reward":                   "Reward",
    "recovery":                 "Recovery",
    "reorganization":           "Reorganization",
    "reprimand":                "Reprimand",
    "revelation":               "Revelation",
    "sagacity":                 "Sagacity",
    "composure":                "Composure",
    "know-how":                 "Know-How",
    "schadenfreude":            "Schadenfreude",
    "situations":               "Situations",
    "sociability":              "Sociability",
    "spectacle":                "Spectacle",
    "stability":                "Stability",
    "overload":                 "Overload",
    "survival":                 "Survival",
    "security":                 "Security",
    "serenity":                 "Serenity",
    "innate-talent":            "Innate Talent",
    "theatricality":            "Theatricality",
    "torpor":                   "Torpor",
    "transaction":              "Transaction",
    "transgression":            "Transgression",
    "transparency":             "Transparency",
    "triumph":                  "Triumph",
    "urgency":                  "Urgency",
    "values":                   "Values",
    "victim":                   "Victim",
    "life":                     "Life",
    "hectic-life":              "Hectic Life",
    "old-age":                  "Old Age",
    "vigilance":                "Vigilance",
    "neighborhood":             "Neighborhood",
    "car":                      "Car",
    "vulgarity":                "Vulgarity",
    "age":                      "Age",
    "school":                   "School",
    "listening":                "Listening",
    "egocentrism":              "Egocentrism",
    "selfishness":              "Selfishness",
    "elimination":              "Elimination",
    "elegance":                 "Elegance",
    "savings":                  "Savings",
    "fainting":                 "Fainting",
    "escape":                   "Escape",
    "awakening":                "Awakening",
    "agitation":                "Agitation",
    "anxiety":                  "Anxiety",
    "appearances":              "Appearances",
    "approval":                 "Approval",
    "aptitude":                 "Aptitude",
    "aristocracy":              "Aristocracy",
    "connections":              "Connections",
    "guilt":                    "Guilt",
    "expenses":                 "Expenses",
    "dilapidation":             "Dilapidation",
    "speech":                   "Speech",
    "gift":                     "Gift",
    "mood":                     "Mood",
    "hypocrisy":                "Hypocrisy",
    "inattention":              "Inattention",
    "incoherence":              "Incoherence",
    "instant":                  "Instant",
    "morning":                  "Morning",
    "method":                   "Method",
    "obsession":                "Obsession",
    "origin":                   "Origin",
    "reactivity":               "Reactivity",
    "reality":                  "Reality",
    "delay":                    "Delay",
    "theater":                  "Theater",
    "abuse":                    "Abuse",
    "action":                   "Action",
    "accumulation":             "Accumulation",
    "attitude":                 "Attitude",
    "astonishment":             "Astonishment",
    "boldness":                 "Boldness",
    "expensive":                "Expensive",
    "gossip":                   "Gossip",
    "compatibility":            "Compatibility",
    "competition":              "Competition",
    "complicating":             "Complicating",
    "community":                "Community",
    "context":                  "Context",
    "customs":                  "Customs",
    "healing":                  "Healing",
    "decision":                 "Decision",
    "destiny":                  "Destiny",
    "skill":                    "Skill",
    "different":                "Different",
    "dilemma":                  "Dilemma",
    "disbelief":                "Disbelief",
    "praise":                   "Praise",
    "state":                    "State",
    "studies":                  "Studies",
    "exaggeration":             "Exaggeration",
    "fame":                     "Fame",
    "faith":                    "Faith",
    "firmness":                 "Firmness",
    "frankness":                "Frankness",
    "fraud":                    "Fraud",
    "ambition":                 "Ambition",
    "influence":                "Influence",
    "insults":                  "Insults",
    "impertinence":             "Impertinence",
    "impossible":               "Impossible",
    "imprudencia":              "Recklessness",
    "talkativeness":            "Talkativeness",
    "never":                    "Never",
    "obvious":                  "Obvious",
    "benefit":                  "Benefit",
    "permissiveness":           "Permissiveness",
    "dreaming":                 "Dreaming",
    "overcoming":               "Overcoming",
    "stubbornness":             "Stubbornness",
    "shyness":                  "Shyness",
    "clumsiness":               "Clumsiness",
    "unity":                    "Unity",
    "bravery":                  "Bravery",
    "sensibleness":             "Sensibleness",
    "dead-end":                 "Dead End",
    "sincerity":                "Sincerity",
    "similarity":               "Similarity",
    "wolf":                     "Wolf",
    "dog":                      "Dog",
    "fish":                     "Fish",
    "privacy":                  "Privacy",
    "resolution":               "Resolution",
    "relativity":               "Relativity",
    "repetition":               "Repetition",
    "rumors":                   "Rumors",
    "absurdity":                "Absurdity",
    "ignoring":                 "Ignoring",
    "insomnia":                 "Insomnia",
    "uselessness":              "Uselessness",
    "reading":                  "Reading",
    "need":                     "Need",
    "shame":                    "Shame",
    "price":                    "Price",
    "consolation":              "Consolation",
    "collaboration":            "Collaboration",
    "complicity":               "Complicity",
    "physical-fitness":         "Physical Fitness",
}


def tag_exists(conn, slug: str) -> bool:
    return bool(conn.execute(text("SELECT 1 FROM tags WHERE id = :s"), {"s": slug}).scalar())


def run():
    with engine.begin() as conn:
        merges = renames = en_adds = skipped = 0

        for old_slug, new_slug in SLUG_MAP.items():
            # Fresh DB check each iteration — avoids stale cache when multiple old slugs
            # map to the same target (one rename creates it, next must merge into it).
            old_exists = tag_exists(conn, old_slug)
            if not old_exists:
                skipped += 1
                continue

            if old_slug == new_slug:
                # Slug is already English — just add EN tag_names entry if missing
                has_en = conn.execute(text(
                    "SELECT 1 FROM tag_names WHERE tag_id = :s AND locale = 'en'"
                ), {"s": old_slug}).scalar()
                if not has_en:
                    en_name = EN_NAMES.get(new_slug, new_slug.replace("-", " ").title())
                    print(f"  EN-only  {old_slug} → '{en_name}'")
                    if not DRY_RUN:
                        conn.execute(text(
                            "INSERT INTO tag_names (tag_id, locale, name) VALUES (:s, 'en', :n) "
                            "ON CONFLICT DO NOTHING"
                        ), {"s": old_slug, "n": en_name})
                    en_adds += 1
                continue

            new_exists = tag_exists(conn, new_slug)

            if new_exists:
                # Target exists → MERGE old into new.
                # FK order: update/delete child tables first, then delete the parent tag.
                print(f"  MERGE    {old_slug} → {new_slug}")
                if not DRY_RUN:
                    conn.execute(text(
                        "UPDATE expression_tags SET tag_id = :new WHERE tag_id = :old "
                        "AND NOT EXISTS ("
                        "  SELECT 1 FROM expression_tags e2"
                        "  WHERE e2.expression_id = expression_tags.expression_id AND e2.tag_id = :new"
                        ")"
                    ), {"new": new_slug, "old": old_slug})
                    conn.execute(text(
                        "DELETE FROM expression_tags WHERE tag_id = :old"
                    ), {"old": old_slug})
                    conn.execute(text("DELETE FROM tag_names WHERE tag_id = :old"), {"old": old_slug})
                    conn.execute(text("DELETE FROM tags WHERE id = :old"), {"old": old_slug})
                merges += 1
            else:
                # Target doesn't exist → RENAME.
                # FK on expression_tags and tag_names both reference tags.id with NO ACTION,
                # so we can't update children before the new PK exists, nor the PK while children
                # still reference the old one. Solution: INSERT new tag first, then migrate
                # children, then DELETE old tag.
                en_name = EN_NAMES.get(new_slug, new_slug.replace("-", " ").title())
                print(f"  RENAME   {old_slug} → {new_slug} ('{en_name}')")
                if not DRY_RUN:
                    # 1. Insert new tag row (new PK exists now)
                    conn.execute(text(
                        "INSERT INTO tags (id, slug) VALUES (:new, :new)"
                    ), {"new": new_slug})
                    # 2. Migrate child rows to new tag id
                    conn.execute(text(
                        "UPDATE expression_tags SET tag_id = :new WHERE tag_id = :old"
                    ), {"new": new_slug, "old": old_slug})
                    conn.execute(text(
                        "UPDATE tag_names SET tag_id = :new WHERE tag_id = :old"
                    ), {"new": new_slug, "old": old_slug})
                    # 3. Delete old tag (no more references)
                    conn.execute(text("DELETE FROM tags WHERE id = :old"), {"old": old_slug})
                    # 4. Add EN translation
                    conn.execute(text(
                        "INSERT INTO tag_names (tag_id, locale, name) VALUES (:s, 'en', :n) "
                        "ON CONFLICT DO NOTHING"
                    ), {"s": new_slug, "n": en_name})
                renames += 1

        print()
        print(f"{'DRY-RUN — ' if DRY_RUN else ''}Done.")
        print(f"  Merges   : {merges}")
        print(f"  Renames  : {renames}")
        print(f"  EN-only  : {en_adds}")
        print(f"  Skipped  : {skipped} (slug not found in DB)")
        if DRY_RUN:
            print()
            print("Run with --apply to execute.")


if __name__ == "__main__":
    run()
